<?php
if ( ! defined( 'ABSPATH' ) ) { exit; }
function emdo_cb_name($f){if(is_string($f))return $f;if(is_array($f))return (is_object($f[0])?get_class($f[0]):(string)$f[0]).'::'.$f[1];return $f instanceof Closure?'Closure':gettype($f);}
echo "=== NAV ACTION REGISTRATION ===\n"; global $wp_filter,$wpdb; foreach($wp_filter as $hook=>$obj){if(!is_object($obj)||empty($obj->callbacks))continue;foreach($obj->callbacks as $pri=>$cbs){foreach($cbs as $cb){$n=emdo_cb_name($cb['function']);if(stripos($n,'woostify_product_navigation')!==false)echo "$hook|$pri|$n\n";}}}
echo "=== DISABLED VENDORS ===\n";$disabled=function_exists('elmercado_wcfm_disabled_vendor_ids_010210')?elmercado_wcfm_disabled_vendor_ids_010210():[];echo 'ids='.json_encode($disabled)."\n";if($disabled){$in=implode(',',array_map('intval',$disabled));$rows=$wpdb->get_results("SELECT post_author,COUNT(*) c FROM {$wpdb->posts} WHERE post_type='product' AND post_status='publish' AND post_author IN ($in) GROUP BY post_author",ARRAY_A);echo json_encode($rows)."\n";}echo 'total_published='.$wpdb->get_var("SELECT COUNT(*) FROM {$wpdb->posts} WHERE post_type='product' AND post_status='publish'")."\n";
echo "=== CATEGORY DISTRIBUTION DISABLED/ACTIVE ===\n";$sql="SELECT t.term_id,t.name, SUM(CASE WHEN p.post_author IN (".($disabled?implode(',',array_map('intval',$disabled)):'0').") THEN 1 ELSE 0 END) disabled_count, SUM(CASE WHEN p.post_author NOT IN (".($disabled?implode(',',array_map('intval',$disabled)):'0').") THEN 1 ELSE 0 END) active_count FROM {$wpdb->term_relationships} tr JOIN {$wpdb->term_taxonomy} tt ON tt.term_taxonomy_id=tr.term_taxonomy_id AND tt.taxonomy='product_cat' JOIN {$wpdb->terms} t ON t.term_id=tt.term_id JOIN {$wpdb->posts} p ON p.ID=tr.object_id AND p.post_type='product' AND p.post_status='publish' GROUP BY t.term_id,t.name ORDER BY disabled_count DESC,active_count DESC LIMIT 30";foreach($wpdb->get_results($sql,ARRAY_A) as $r)echo implode('|',$r)."\n";
echo "=== BENCH NAVIGATION ===\n";
$ids=$wpdb->get_col("SELECT p.ID FROM {$wpdb->posts} p WHERE p.post_type='product' AND p.post_status='publish' ORDER BY p.post_date DESC LIMIT 12");
foreach($ids as $id){$GLOBALS['post']=get_post((int)$id);setup_postdata($GLOBALS['post']);$counts=['prev'=>0,'next'=>0,'visible'=>0];$fp=function($w)use(&$counts){$counts['prev']++;return $w;};$fn=function($w)use(&$counts){$counts['next']++;return $w;};$fv=function($v,$pid)use(&$counts){$counts['visible']++;return $v;};add_filter('get_previous_post_where',$fp,PHP_INT_MAX);add_filter('get_next_post_where',$fn,PHP_INT_MAX);add_filter('woocommerce_product_is_visible',$fv,PHP_INT_MAX,2);$t=microtime(true);$prev=woostify_get_prev_product();$tp=microtime(true)-$t;$t=microtime(true);$next=woostify_get_next_product();$tn=microtime(true)-$t;remove_filter('get_previous_post_where',$fp,PHP_INT_MAX);remove_filter('get_next_post_where',$fn,PHP_INT_MAX);remove_filter('woocommerce_product_is_visible',$fv,PHP_INT_MAX);echo 'ID='.$id.' author='.$GLOBALS['post']->post_author.' prev_s='.sprintf('%.4f',$tp).' next_s='.sprintf('%.4f',$tn).' prev_loops='.$counts['prev'].' next_loops='.$counts['next'].' visible_checks='.$counts['visible'].' prev_id='.($prev?$prev->get_id():0).' next_id='.($next?$next->get_id():0)."\n";}
wp_reset_postdata();
echo "=== RECENT ACCESS AROUND SLOWLOG ===\n";$log='/var/www/vhosts/system/elmercadodeorigen.com/logs/access_ssl_log';if(is_readable($log)){foreach(file($log,FILE_IGNORE_NEW_LINES|FILE_SKIP_EMPTY_LINES)?:[] as $line){if(preg_match('/\[14\/Aug\/2026:09:2[4-6]:/',$line))echo preg_replace('/^\S+/','<ip>',$line)."\n";}}
