<?php
if ( ! defined( 'ABSPATH' ) ) { exit; }

function cmd($c){$o=shell_exec($c.' 2>&1');return is_string($o)?trim($o):'';}
function inc(&$a,$k,$n=1){$a[$k]=($a[$k]??0)+$n;}
function topn($a,$n=20){arsort($a);return array_slice($a,0,$n,true);}
function gua($ua){$u=strtolower($ua);if(str_contains($u,'monitoring360'))return'360 Monitoring';if(str_contains($u,'facebook')||str_contains($u,'meta-external'))return'Meta/Facebook';if(str_contains($u,'applebot'))return'Applebot';if(str_contains($u,'googlebot'))return'Googlebot';if(str_contains($u,'bingbot'))return'Bingbot';if(str_contains($u,'gptbot')||str_contains($u,'oai-searchbot'))return'OpenAI';if(str_contains($u,'mentta/'))return'Mentta';if(str_contains($u,'headless'))return'Headless browser';if(str_contains($u,'bot')||str_contains($u,'crawler')||str_contains($u,'spider')||str_contains($u,'curl')||str_contains($u,'python')||str_contains($u,'scan'))return'Other bot/automation';return'Browser-like/unknown';}
function ep($path){$p=parse_url($path,PHP_URL_PATH)?:$path;if($p==='/'||$p==='')return'home';if(str_contains($p,'admin-ajax.php'))return'admin-ajax';if(str_contains($p,'wp-cron.php'))return'wp-cron';if(str_contains($p,'wp-login.php'))return'wp-login';if(str_contains($p,'xmlrpc.php'))return'xmlrpc';if(str_starts_with($p,'/wp-json/'))return'wp-json';if(str_contains($path,'wc-ajax'))return'wc-ajax';if(preg_match('~/producto/|/product/~',$p))return'product';if(preg_match('~/categoria-producto/|/product-category/~',$p))return'category';if(preg_match('~\.(css|js|jpg|jpeg|png|webp|gif|svg|woff2?|ico)(\?|$)~i',$path))return'static';return'other';}

$logdir='/var/www/vhosts/system/elmercadodeorigen.com/logs';
$files=[$logdir.'/access_ssl_log',$logdir.'/proxy_access_ssl_log'];
$cut=strtotime('2026-08-14 07:45:00 UTC');$end=strtotime('2026-08-14 08:02:24 UTC');
$s=['requests'=>0,'unique_ips'=>0,'per_minute'=>[],'dynamic_per_minute'=>[],'status'=>[],'agents'=>[],'endpoints'=>[],'paths'=>[],'uas'=>[],'ip_counts'=>[],'ip_agents'=>[],'ip_dyn'=>[]];$ips=[];$seen=[];
foreach($files as $file){if(!is_readable($file))continue;$fh=fopen($file,'rb');while(($line=fgets($fh))!==false){if(!preg_match('/^(\S+) \S+ \S+ \[([^\]]+)\] "(\S+) ([^ ]+) HTTP\/[^"]+" (\d{3}) \S+ "[^"]*" "([^"]*)"/',$line,$m))continue;$ts=strtotime($m[2]);if($ts===false||$ts<$cut||$ts>$end)continue;$sig=sha1($line);if(isset($seen[$sig]))continue;$seen[$sig]=1;$ip=$m[1];$path=$m[4];$st=$m[5];$ua=$m[6];$min=gmdate('H:i',$ts);$e=ep($path);$g=gua($ua);$s['requests']++;$ips[$ip]=1;inc($s['per_minute'],$min);inc($s['status'],$st);inc($s['agents'],$g);inc($s['endpoints'],$e);inc($s['paths'],$path);inc($s['uas'],$ua);inc($s['ip_counts'],$ip);if($e!=='static'){inc($s['dynamic_per_minute'],$min);inc($s['ip_dyn'],$ip);}if(!isset($s['ip_agents'][$ip]))$s['ip_agents'][$ip]=[];inc($s['ip_agents'][$ip],$g);}fclose($fh);}
$s['unique_ips']=count($ips);ksort($s['per_minute']);ksort($s['dynamic_per_minute']);$s['status']=topn($s['status'],10);$s['agents']=topn($s['agents'],15);$s['endpoints']=topn($s['endpoints'],15);$s['paths']=topn($s['paths'],30);$s['uas']=topn($s['uas'],20);$clients=[];foreach(topn($s['ip_counts'],20) as $ip=>$n){$ptr=@gethostbyaddr($ip);if(!$ptr||$ptr===$ip)$ptr='no-ptr';$clients[]=['id'=>substr(hash('sha256',$ip),0,10),'requests'=>$n,'dynamic'=>$s['ip_dyn'][$ip]??0,'ptr'=>$ptr,'agents'=>topn($s['ip_agents'][$ip]??[],4)];}unset($s['ip_counts'],$s['ip_dyn'],$s['ip_agents']);$s['top_clients']=$clients;
echo 'PRE_REBOOT_TRAFFIC_JSON '.json_encode($s,JSON_UNESCAPED_SLASHES|JSON_UNESCAPED_UNICODE)."\n";

echo "AGENT360_SAFE_START\n";
echo 'AGENT360_INFO ' . preg_replace('/(?i)(token|key|secret|password)\s*[:=]\s*\S+/','$1=<redacted>',cmd('agent360 info 2>/dev/null || /usr/local/bin/agent360 info 2>/dev/null || true')) . "\n";
foreach(['/etc/agent360.ini','/etc/agent360-custom.ini','/etc/agent360-token.ini'] as $f){if(!is_readable($f))continue;echo 'CONFIG_FILE '.basename($f).' bytes='.filesize($f)."\n";$lines=file($f,FILE_IGNORE_NEW_LINES);foreach($lines as $line){$t=trim($line);if($t===''||str_starts_with($t,'#')||str_starts_with($t,';'))continue;if(preg_match('/^\[([^\]]+)\]$/',$t,$m)){echo 'SECTION '.$m[1]."\n";continue;}if(preg_match('/^([^=:\s]+)\s*[=:]\s*(.*)$/',$t,$m)){$k=$m[1];$v=trim($m[2]);$lk=strtolower($k);$safe=(str_contains($lk,'serverid')||$lk==='server_id'||$lk==='host'||$lk==='hostname'||str_contains($lk,'url')||$lk==='endpoint');if($safe && !preg_match('/token|key|secret|pass/i',$lk)){if(preg_match('~https?://([^/]+)~',$v,$u))$v=$u[1];echo 'KEY '.$k.'='.$v."\n";}else{echo 'KEY '.$k.'=<redacted,len:'.strlen($v).">\n";}}}}
$alog='/var/log/agent360.log';if(is_readable($alog)){echo 'AGENT_LOG_META bytes='.filesize($alog).' mtime='.gmdate('c',filemtime($alog))."\n";$raw=cmd("grep -E '2026-08-14 (07:4[5-9]|07:5[0-9]|08:0[0-2])|Aug 14 (07:4[5-9]|07:5[0-9]|08:0[0-2])' ".escapeshellarg($alog)." | tail -n 120");$raw=preg_replace('/(?i)(token|key|secret|password)([=: ]+)[A-Za-z0-9._~+\/=:-]+/','$1$2<redacted>',$raw);$raw=preg_replace('/[A-Fa-f0-9]{32,}/','<redacted-id>',$raw);echo "AGENT_LOG_WINDOW\n$raw\n";}
echo "AGENT360_SAFE_END\n";
