<?php
/** Editorial de-duplication for the highest-risk nutrition and Iberian-labelling clusters. */
if (!defined('ABSPATH')) { exit; }
function emdo_pc_norm($s){$s=html_entity_decode(wp_strip_all_tags((string)$s),ENT_QUOTES|ENT_HTML5,'UTF-8');$s=remove_accents(mb_strtolower($s,'UTF-8'));return trim(preg_replace('/\s+/u',' ',preg_replace('/[^a-z0-9]+/u',' ',$s)));}
function emdo_pc_h2s($html){preg_match_all('/<h2\b[^>]*>.*?<\/h2>/isu',(string)$html,$m,PREG_OFFSET_CAPTURE);return $m[0]??[];}
function emdo_pc_bounds($html,$heading){$hs=emdo_pc_h2s($html);$want=emdo_pc_norm($heading);foreach($hs as $i=>$h){if(emdo_pc_norm($h[0])===$want){$start=$h[1];$end=isset($hs[$i+1])?$hs[$i+1][1]:strlen($html);return [$start,$end];}}return null;}
function emdo_pc_extract($html,$heading){$b=emdo_pc_bounds($html,$heading);return $b?substr($html,$b[0],$b[1]-$b[0]):'';}
function emdo_pc_replace($html,$heading,$new){$b=emdo_pc_bounds($html,$heading);if(!$b)return $html;return substr($html,0,$b[0]).$new.substr($html,$b[1]);}
function emdo_pc_cut($html,$heading,$append,$preserve=[]){$kept='';foreach($preserve as $h){$s=emdo_pc_extract($html,$h);if($s!=='')$kept.="\n".$s;} $b=emdo_pc_bounds($html,$heading);if(!$b)return $html;return rtrim(substr($html,0,$b[0]))."\n".$append.$kept;}
function emdo_pc_es($id,$label){return '<a href="'.esc_url(get_permalink($id)).'">'.esc_html($label).'</a>';}
function emdo_pc_en_url($id){$slug=trim((string)get_post_meta($id,'_en_US_post_name',true));return rtrim(home_url('/'),'/').'/en/'.trim($slug,'/').'/';}
function emdo_pc_en($id,$label){return '<a href="'.esc_url(emdo_pc_en_url($id)).'">'.esc_html($label).'</a>';}
function emdo_pc_words($html){preg_match_all('/[\p{L}\p{N}]+/u',wp_strip_all_tags((string)$html),$m);return count($m[0]);}
function emdo_pc_apply($id,$es,$en){
  $p=get_post($id); if(!$p||$p->post_status!=='publish') throw new Exception("post $id is not published");
  if(emdo_pc_words($es)<420||emdo_pc_words($en)<380) throw new Exception("post $id transformed content too short: ".emdo_pc_words($es).'/'.emdo_pc_words($en));
  wp_update_post(['ID'=>$id,'post_content'=>$es]);
  update_post_meta($id,'_en_US_post_content',$en);
  update_post_meta($id,'_en_US_ready','1'); update_post_meta($id,'_en_US_published','1');
  update_post_meta($id,'_emdo_perfection_20260902','core-v1');
  return ['id'=>$id,'es_words'=>emdo_pc_words($es),'en_words'=>emdo_pc_words($en)];
}
$results=[];

// 13694 — legumes iron ranking only; remove meat/bioavailability detour.
$id=13694;$es=(string)get_post_field('post_content',$id);$en=(string)get_post_meta($id,'_en_US_post_content',true);
$esAdd='<h2>Cómo comparar legumbres sin mezclar bases de cálculo</h2><p>Este ranking tiene una única misión: ordenar legumbres por su contenido de hierro. Para que la comparación sea útil hay que distinguir entre peso seco y peso cocido. El agua absorbida durante la cocción aumenta mucho el peso del alimento y, por tanto, reduce la cantidad de hierro expresada por cada 100 gramos aunque el mineral no haya desaparecido en la misma proporción.</p><p>Por eso no conviene enfrentar una cifra de lentejas secas con otra de garbanzos cocidos. Si quieres decidir qué legumbre aporta más hierro, compara siempre datos expresados en la misma base y, después, tradúcelos a la ración que realmente vas a comer.</p><h2>Qué explica las diferencias entre lentejas, garbanzos, alubias y soja</h2><p>Las especies, variedades, procedencia y composición del grano hacen que las cifras no sean idénticas entre bases de datos ni entre productos comerciales. El objetivo de una tabla nutricional es dar una referencia razonable, no prometer que cada paquete contiene exactamente la misma cantidad.</p><h2>Cómo usar este ranking en una compra real</h2><p>Si el hierro es tu criterio principal, utiliza esta página para comparar legumbres entre sí. Para saber cómo mejorar el aprovechamiento del hierro vegetal, consulta '.emdo_pc_es(13734,'la guía específica sobre absorción del hierro de las legumbres').'. Si quieres comparar legumbres con carne o verduras, ve a '.emdo_pc_es(13728,'la comparativa general de alimentos ricos en hierro').'. Separar esas preguntas evita que un mismo artículo intente responder a tres búsquedas distintas.</p><h2>Preguntas centradas en el ranking</h2><h3>¿Debo comparar 100 g secos o cocidos?</h3><p>Cualquiera de las dos bases sirve si todos los alimentos de la tabla están expresados del mismo modo. Para una compra, el peso seco permite comparar el producto tal como se vende; para una comida, la ración cocida suele ser más intuitiva.</p><h3>¿La legumbre con más hierro es automáticamente la mejor?</h3><p>No. Esta página ordena un nutriente concreto. Proteína, fibra, energía, tolerancia digestiva, precio y uso culinario son criterios distintos.</p>';
$enAdd='<h2>How to compare legumes without mixing calculation bases</h2><p>This ranking has one job: compare the iron content of legumes. Dry and cooked weights must not be mixed. Cooking adds a great deal of water, increasing food weight and lowering the iron figure shown per 100 grams even though the mineral has not vanished in the same proportion.</p><p>A dry-lentil value should therefore not be compared with a cooked-chickpea value. Use figures expressed on the same basis first, then convert them into the serving you actually eat.</p><h2>Why lentils, chickpeas, beans and soy do not give identical figures</h2><p>Species, varieties, growing conditions and the composition of each batch can produce modest differences between food databases and commercial labels. Nutrition tables are useful reference points rather than a promise that every packet contains an identical number.</p><h2>How to use this ranking when shopping</h2><p>If iron content is your main criterion, use this page to compare legumes with one another. For ways to improve plant-iron availability, use '.emdo_pc_en(13734,'our dedicated guide to improving iron absorption from legumes').'. To compare legumes with meat and vegetables, use '.emdo_pc_en(13728,'the broader iron-rich foods comparison').'. Keeping these questions separate gives each page a clear search intent.</p><h2>Questions about the ranking</h2><h3>Should I compare dry or cooked values?</h3><p>Either basis can work as long as every food in the comparison uses the same basis. Dry weight is useful for comparing products as sold; cooked servings are often more intuitive at mealtime.</p><h3>Is the legume with the most iron automatically the best choice?</h3><p>No. This page ranks one nutrient. Protein, fibre, energy, digestibility, price and culinary use are separate considerations.</p>';
$es=emdo_pc_cut($es,'El hierro de las legumbres no se absorbe igual que el de la carne',$esAdd,['Fuentes consultadas','Legumbres']);$en=emdo_pc_cut($en,'Iron from legumes is not absorbed in the same way as iron from meat',$enAdd,['Sources','Legumes']);$results[]=emdo_pc_apply($id,$es,$en);

// 13718 — vegetable ranking, no meat comparison or absorption tutorial.
$id=13718;$es=(string)get_post_field('post_content',$id);$en=(string)get_post_meta($id,'_en_US_post_content',true);
$esAdd='<h2>Por 100 gramos y por ración no obtendrás siempre el mismo orden</h2><p>Una tabla por 100 gramos permite comparar alimentos con una regla común, pero una ración habitual puede cambiar la importancia práctica del dato. Algunas verduras se comen en cantidades grandes y otras en porciones pequeñas. Por eso esta guía usa el ranking como punto de partida y no como una clasificación absoluta de qué verdura “conviene” más.</p><h2>Crudo, cocido y agua de cocción</h2><p>Los minerales son relativamente estables frente al calor, pero una parte puede pasar al agua cuando se hierve un alimento. Si ese líquido se descarta, la cantidad que queda en el plato puede cambiar. Vapor, salteado y hervido no producen exactamente el mismo resultado, y la concentración por 100 gramos también cambia cuando una verdura pierde o gana agua.</p><h2>Qué mirar al elegir verduras por su hierro</h2><p>Usa esta página para saber qué verduras destacan dentro del propio grupo. Si buscas una comparación entre hierro vegetal y hierro de la carne, esa pregunta se desarrolla en '.emdo_pc_es(13730,'la guía sobre hierro de carne frente a legumbres').'. Para estrategias concretas de absorción del hierro vegetal, consulta '.emdo_pc_es(13734,'la guía de aprovechamiento del hierro de las legumbres').'. Así esta página permanece centrada en verduras, cantidades y preparación.</p><h2>Preguntas sobre verduras e hierro</h2><h3>¿Cocer destruye el hierro?</h3><p>No se destruye como una vitamina sensible al calor, aunque parte puede trasladarse al agua de cocción. El método de preparación y si consumes o descartas ese líquido importan.</p><h3>¿Las espinacas son la única verdura interesante?</h3><p>No. El ranking muestra que hay varias opciones y que conviene mirar también la ración real y el conjunto de nutrientes de cada alimento.</p>';
$enAdd='<h2>Per 100 grams and per serving can produce a different order</h2><p>A per-100-gram table gives every food the same measuring stick, but typical serving sizes can change the practical importance of the result. Some vegetables are eaten in large portions and others in much smaller amounts, so this ranking is a starting point rather than a universal list of the “best” vegetables.</p><h2>Raw, cooked and cooking water</h2><p>Minerals are relatively stable to heat, but some can move into cooking water when vegetables are boiled. If that liquid is discarded, the amount remaining on the plate can change. Steaming, sautéing and boiling are not identical, and values per 100 grams also shift as vegetables gain or lose water.</p><h2>What to look at when choosing vegetables for iron</h2><p>Use this page to see which vegetables stand out within the vegetable group. For a direct comparison between animal and plant iron, see '.emdo_pc_en(13730,'our meat-versus-legume iron guide').'. For practical absorption strategies, use '.emdo_pc_en(13734,'the guide to improving iron availability from legumes').'. This keeps the present page focused on vegetables, serving size and preparation.</p><h2>Questions about vegetables and iron</h2><h3>Does cooking destroy iron?</h3><p>Iron is not destroyed like a heat-sensitive vitamin, although some may move into the cooking liquid. Preparation method and whether that liquid is eaten or discarded both matter.</p><h3>Is spinach the only vegetable worth considering?</h3><p>No. Several vegetables contribute iron, and the real serving plus the rest of the food’s nutrient profile are more useful than a single headline number.</p>';
$es=emdo_pc_cut($es,'Hierro vegetal vs hierro de la carne',$esAdd,['Fuentes']);$en=emdo_pc_cut($en,'Plant iron versus meat iron',$enAdd,['Sources','Related vegetables']);$results[]=emdo_pc_apply($id,$es,$en);

// 13727 — beef iron numbers only; remove legumes comparison.
$id=13727;$es=(string)get_post_field('post_content',$id);$en=(string)get_post_meta($id,'_en_US_post_content',true);
$esAdd='<h2>Por qué no existe una cifra única para toda la ternera</h2><p>Las tablas de composición usan alimentos de referencia. Un solomillo magro, una pieza con más grasa y una carne picada no tienen una composición idéntica. También influyen el recorte de grasa, el porcentaje de agua y el método de cocción. Por eso es más riguroso trabajar con un intervalo razonable y con la ficha nutricional del producto cuando esté disponible que presentar una cifra como universal.</p><h2>Cómo calcular el hierro de una ración</h2><p>Si una fuente da el dato por 100 gramos, el cálculo para una porción es proporcional. Lo importante es usar el peso en el mismo estado que la tabla: no conviene aplicar un dato de carne cruda al peso final de una pieza que ha perdido agua durante la cocción sin hacer la corrección correspondiente.</p><h2>Qué guía utilizar si tu pregunta es comparativa</h2><p>Esta página responde cuánto hierro aporta la ternera. Para enfrentar carne y legumbres desde el punto de vista del tipo de hierro y su aprovechamiento, utiliza '.emdo_pc_es(13730,'la comparativa de hierro de carne y legumbres').'. Para un panorama que incluya también verduras, consulta '.emdo_pc_es(13728,'alimentos ricos en hierro comparados').'.</p><h2>Preguntas específicas sobre ternera</h2><h3>¿Todos los cortes tienen exactamente el mismo hierro?</h3><p>No. Las diferencias no suelen justificar tratar cada corte como un alimento completamente distinto, pero sí explican por qué dos tablas pueden mostrar valores diferentes.</p><h3>¿La cocción elimina el hierro?</h3><p>El hierro es un mineral y no desaparece por alcanzar la temperatura de cocción. Lo que cambia con frecuencia es el peso por pérdida de agua, de modo que la concentración por 100 gramos puede parecer distinta.</p>';
$enAdd='<h2>Why there is no single iron figure for all beef</h2><p>Food-composition tables use reference foods. A lean fillet, a fattier cut and minced beef do not have identical composition. Trimming, water content and cooking method also matter. It is therefore more accurate to use a reasonable range and the product’s own nutrition information when available than to treat one number as universal.</p><h2>How to calculate iron in a serving</h2><p>If a source gives iron per 100 grams, a serving can be calculated proportionally. The important detail is to use weight in the same state as the reference table. A raw-food figure should not be applied directly to the final cooked weight after substantial water loss without accounting for that change.</p><h2>Which guide to use for comparisons</h2><p>This page answers how much iron beef provides. To compare meat and legumes by iron type and availability, use '.emdo_pc_en(13730,'the meat-versus-legume iron guide').'. For a broader view that also includes vegetables, see '.emdo_pc_en(13728,'our comparison of iron-rich foods').'.</p><h2>Beef-specific questions</h2><h3>Do all cuts contain exactly the same iron?</h3><p>No. The differences do not make every cut a completely different food, but they help explain why two reliable tables can show somewhat different values.</p><h3>Does cooking remove iron?</h3><p>Iron is a mineral and is not destroyed at normal cooking temperatures. What often changes is food weight through water loss, which can make the value per 100 grams appear more concentrated.</p>';
$es=emdo_pc_cut($es,'Ternera, lentejas y garbanzos: por qué los miligramos no cuentan toda la historia',$esAdd,['Fuentes consultadas','Productos relacionados']);$en=emdo_pc_cut($en,'Beef versus lentils and chickpeas',$enAdd,['Sources','Related products']);$results[]=emdo_pc_apply($id,$es,$en);

// 13728 — cross-category hub; point to specialists instead of re-explaining them.
$id=13728;$es=(string)get_post_field('post_content',$id);$en=(string)get_post_meta($id,'_en_US_post_content',true);
$esAdd='<h2>Cómo interpretar esta comparativa sin convertirla en otra guía de absorción</h2><p>Esta página funciona como mapa entre grupos de alimentos. La cantidad de hierro es una parte de la comparación; el tipo de hierro y el contexto de la comida son otra. Aquí basta con tener presente esa diferencia. El desarrollo sobre hierro hemo y no hemo está en '.emdo_pc_es(13730,'la guía específica de carne frente a legumbres').', mientras que las estrategias para favorecer el hierro vegetal están en '.emdo_pc_es(13734,'la guía de absorción del hierro de las legumbres').'.</p><h2>Tres preguntas distintas, tres páginas distintas</h2><ul><li><strong>¿Qué legumbre contiene más hierro?</strong> Consulta '.emdo_pc_es(13694,'el ranking de legumbres').'.</li><li><strong>¿Qué verduras destacan?</strong> Consulta '.emdo_pc_es(13718,'el ranking de verduras con más hierro').'.</li><li><strong>¿Cuánto hierro tiene la ternera?</strong> Consulta '.emdo_pc_es(13727,'la guía específica de ternera').'.</li></ul><p>El objetivo de este artículo no es repetir esas tablas, sino ayudarte a orientarte entre categorías.</p><h2>Cómo usar el mapa en una dieta real</h2><p>En una alimentación variada no hace falta escoger un ganador absoluto. Carne, legumbres y verduras cumplen papeles diferentes y normalmente se consumen en raciones distintas. Al comparar, mira la cantidad que realmente comes, la frecuencia, el resto de nutrientes del alimento y el conjunto de la comida.</p><h2>Qué significa realmente “rico en hierro”</h2><p>Una cifra alta por 100 gramos puede ser interesante, pero no resume la utilidad nutricional de un alimento. La ración, la forma de preparación y el patrón alimentario completo son más informativos que una clasificación aislada. Por eso esta página debe leerse como un índice comparativo y no como una recomendación de sustituir un grupo por otro.</p>';
$enAdd='<h2>How to read this comparison without turning it into another absorption guide</h2><p>This page is a map between food groups. The amount of iron is one part of the comparison; iron type and meal context are another. The detailed explanation of heme and non-heme iron belongs in '.emdo_pc_en(13730,'our meat-versus-legume guide').', while practical strategies for plant iron belong in '.emdo_pc_en(13734,'the legume iron-absorption guide').'.</p><h2>Three different questions, three specialist pages</h2><ul><li><strong>Which legume contains the most iron?</strong> Use '.emdo_pc_en(13694,'the legume ranking').'.</li><li><strong>Which vegetables stand out?</strong> Use '.emdo_pc_en(13718,'the high-iron vegetable ranking').'.</li><li><strong>How much iron is in beef?</strong> Use '.emdo_pc_en(13727,'the beef-specific guide').'.</li></ul><p>The purpose here is not to reproduce those tables but to help you navigate between categories.</p><h2>Using the map in a real diet</h2><p>A varied diet does not require one absolute winner. Meat, legumes and vegetables play different roles and are usually eaten in different serving sizes. Compare the amount you actually eat, frequency, the rest of the nutrient profile and the whole meal rather than one number in isolation.</p><h2>What “iron-rich” really tells you</h2><p>A high figure per 100 grams can be useful information, but it does not summarise the nutritional value of a food. Serving size, preparation and the overall eating pattern provide more context. This page is therefore a comparative index, not an instruction to replace one food group with another.</p>';
$es=emdo_pc_cut($es,'Hierro hemo y no hemo: la diferencia que cambia la comparación',$esAdd,['Fuentes consultadas','Productos relacionados']);$en=emdo_pc_cut($en,'Heme versus non-heme iron',$enAdd,['Sources','Related products']);$results[]=emdo_pc_apply($id,$es,$en);

// 13730 — mechanism comparison; send practical tactics elsewhere.
$id=13730;$es=(string)get_post_field('post_content',$id);$en=(string)get_post_meta($id,'_en_US_post_content',true);
$esAdd='<h2>La pregunta central no es qué alimento gana por miligramos</h2><p>La utilidad de esta comparación está en entender que dos alimentos pueden mostrar cifras parecidas o incluso invertidas en una tabla y, aun así, no entregar el hierro al organismo del mismo modo. El hierro de origen animal incluye hierro hemo; el de las legumbres es no hemo y responde más al contexto de la comida.</p><p>Eso no convierte una fuente en “buena” y la otra en “mala”. Significa que una comparación rigurosa debe separar contenido y biodisponibilidad.</p><h2>Qué dejamos fuera deliberadamente de esta página</h2><p>Las técnicas para favorecer el hierro de las legumbres —combinaciones de alimentos, preparación, remojo o fermentación— tienen una intención de búsqueda propia. Están desarrolladas en '.emdo_pc_es(13734,'cómo mejorar la absorción del hierro de las legumbres').'. Del mismo modo, si solo quieres conocer cifras de ternera, ve a '.emdo_pc_es(13727,'cuánto hierro tiene la carne de ternera').'.</p><h2>Cómo elegir la guía correcta</h2><ul><li>Usa esta página para entender <strong>por qué el hierro animal y el vegetal se comportan de manera diferente</strong>.</li><li>Usa '.emdo_pc_es(13728,'el mapa de alimentos ricos en hierro').' para comparar grupos.</li><li>Usa '.emdo_pc_es(13694,'el ranking de legumbres').' o '.emdo_pc_es(13718,'el ranking de verduras').' cuando tu pregunta sea únicamente “cuál tiene más”.</li></ul><h2>Idea final</h2><p>Carne y legumbres no necesitan competir para que la comparación sea útil. La diferencia relevante es química y fisiológica: el tipo de hierro cambia su disponibilidad y el contexto de la comida importa especialmente para el hierro no hemo.</p>';
$enAdd='<h2>The central question is not which food wins on milligrams</h2><p>The value of this comparison is understanding that two foods can show similar—or even reversed—numbers in a table while delivering iron to the body differently. Animal foods include heme iron; legume iron is non-heme and responds more strongly to the context of the meal.</p><p>That does not make one source “good” and the other “bad”. It means a rigorous comparison must separate iron content from bioavailability.</p><h2>What this page deliberately leaves to specialist guides</h2><p>Practical ways to improve iron availability from legumes—food pairings, preparation, soaking or fermentation—have their own search intent and are covered in '.emdo_pc_en(13734,'how to improve iron absorption from legumes').'. If you only need beef figures, use '.emdo_pc_en(13727,'how much iron is in beef').'.</p><h2>Choosing the right guide</h2><ul><li>Use this page to understand <strong>why animal and plant iron behave differently</strong>.</li><li>Use '.emdo_pc_en(13728,'the iron-rich foods map').' to compare food groups.</li><li>Use '.emdo_pc_en(13694,'the legume ranking').' or '.emdo_pc_en(13718,'the vegetable ranking').' when the question is simply which food contains more.</li></ul><h2>Bottom line</h2><p>Meat and legumes do not need to compete for the comparison to be useful. The important distinction is chemical and physiological: iron type changes availability, and meal context matters particularly for non-heme iron.</p>';
$es=emdo_pc_cut($es,'Cómo comparar de forma justa una ración',$esAdd,['Fuentes consultadas','Productos relacionados']);$en=emdo_pc_cut($en,'How to compare real servings',$enAdd,['Sources','Related products']);$results[]=emdo_pc_apply($id,$es,$en);

// 13734 — practical absorption page starts with its practical goal rather than repeating the comparison article.
$id=13734;$es=(string)get_post_field('post_content',$id);$en=(string)get_post_meta($id,'_en_US_post_content',true);
$esNew='<h2>Objetivo de esta guía: aprovechar mejor el hierro de un plato de legumbres</h2><p>Aquí no vamos a ordenar alimentos por cantidad de hierro ni a decidir si carne o legumbres “ganan”. La pregunta es práctica: una vez has elegido lentejas, garbanzos o alubias, ¿qué decisiones de preparación y acompañamiento pueden favorecer la disponibilidad de su hierro no hemo? Para la explicación comparativa del hierro animal y vegetal, consulta '.emdo_pc_es(13730,'la guía de carne frente a legumbres').'.</p>';
$enNew='<h2>Goal of this guide: make better use of iron in a legume meal</h2><p>This page does not rank foods by iron content or decide whether meat or legumes “win”. It answers a practical question: once you have chosen lentils, chickpeas or beans, which preparation and meal choices can support the availability of their non-heme iron? For the animal-versus-plant comparison, use '.emdo_pc_en(13730,'our meat-versus-legume iron guide').'.</p>';
$es=emdo_pc_replace($es,'Hierro hemo y hierro no hemo: la diferencia básica',$esNew);$en=emdo_pc_replace($en,'Haem and non-haem iron',$enNew);$results[]=emdo_pc_apply($id,$es,$en);

// 13720 — broad beef nutrient profile: protein is a signpost, not a duplicate protein guide.
$id=13720;$es=(string)get_post_field('post_content',$id);$en=(string)get_post_meta($id,'_en_US_post_content',true);
$es=emdo_pc_replace($es,'Proteína de la ternera','<h2>Proteína: un nutriente importante, con guía propia</h2><p>La ternera aporta proteína de alto valor biológico, pero esta página no necesita repetir una explicación completa sobre gramos por corte, raciones y efecto de la cocción. Para esa intención concreta está '.emdo_pc_es(13721,'cuánta proteína tiene la carne de ternera').'. Aquí la proteína se entiende como una pieza más del perfil nutricional junto con hierro, zinc, vitaminas y grasa.</p>');
$en=emdo_pc_replace($en,'Protein in beef','<h2>Protein: an important nutrient with its own guide</h2><p>Beef provides high-quality protein, but this broad nutrient profile does not need to repeat the full discussion of grams by serving, cut and cooking state. That question is covered in '.emdo_pc_en(13721,'how much protein is in beef').'. Here, protein is one part of the overall profile alongside iron, zinc, vitamins and fat.</p>');
$es=emdo_pc_replace($es,'Crudo y cocinado: cuidado con los 100 gramos','<h2>Por qué una tabla de ternera necesita contexto</h2><p>Los valores por 100 gramos cambian según el corte, el recorte de grasa y si la referencia corresponde al alimento crudo o cocinado. Cocinar modifica sobre todo agua y concentración; por eso una tabla debe leerse como referencia y no como una etiqueta idéntica para cualquier pieza de ternera.</p>');
$en=emdo_pc_replace($en,'Raw and cooked: be careful with 100 grams','<h2>Why a beef nutrition table needs context</h2><p>Values per 100 grams vary with cut, fat trimming and whether the reference food is raw or cooked. Cooking changes water content and concentration in particular, so a table should be read as a reference rather than an identical label for every piece of beef.</p>');$results[]=emdo_pc_apply($id,$es,$en);

// 12924 — colour seals only; breed percentage becomes a signpost.
$id=12924;$es=(string)get_post_field('post_content',$id);$en=(string)get_post_meta($id,'_en_US_post_content',true);
$es=emdo_pc_replace($es,'El porcentaje racial: el dato que hay que leer junto al color','<h2>El color no sustituye al porcentaje racial</h2><p>El precinto responde sobre todo a la categoría comercial ligada a alimentación y manejo. El porcentaje 50 %, 75 % o 100 % ibérico responde a otra pregunta: la raza. Para no duplicar explicaciones, la genealogía y el significado exacto de cada porcentaje se desarrollan en '.emdo_pc_es(13086,'la guía de 50 %, 75 % y 100 % ibérico').'. En esta página basta con recordar que color y porcentaje deben leerse juntos.</p>');
$en=emdo_pc_replace($en,'Breed percentage: the figure to read alongside the colour','<h2>Seal colour does not replace breed percentage</h2><p>The seal primarily identifies the commercial category linked to feeding and production system. A 50%, 75% or 100% Iberian figure answers a different question: breed. The exact meaning of those percentages is therefore kept in '.emdo_pc_en(13086,'our 50%, 75% and 100% Iberian guide').'. On this page, the key point is simply that colour and breed percentage must be read together.</p>');$results[]=emdo_pc_apply($id,$es,$en);

// 12971 — black-seal product intent, not a second full label guide.
$id=12971;$es=(string)get_post_field('post_content',$id);$en=(string)get_post_meta($id,'_en_US_post_content',true);
$esAdd='<h2>Qué hace especial a la denominación completa “de bellota 100 % ibérico”</h2><p>La expresión combina dos dimensiones que en otros productos pueden variar por separado: alimentación/manejo de montanera y pureza racial. Por eso la brida negra identifica una combinación concreta y no un simple sinónimo de “jamón bueno”.</p><h2>Cómo comprobar un producto de brida negra sin convertir la compra en un examen</h2><ol><li>Comprueba que la denominación de venta incluye <strong>de bellota 100 % ibérico</strong>.</li><li>Verifica el precinto negro oficial.</li><li>Distingue jamón de paleta y formato entero de loncheado: son decisiones de compra distintas.</li><li>Compara productor, curación, peso, formato y conservación después de confirmar la categoría.</li></ol><p>Si necesitas entender todos los colores, consulta '.emdo_pc_es(12924,'la guía de bridas negra, roja, verde y blanca').'. Si tu duda es exclusivamente genealógica, consulta '.emdo_pc_es(13086,'qué significan 50 %, 75 % y 100 % ibérico').'.</p><h2>Lo que la brida negra no promete por sí sola</h2><p>No fija que dos piezas tengan idéntico sabor, porcentaje de grasa, tiempo exacto de curación o rendimiento. Dentro de una misma categoría siguen existiendo diferencias de productor, pieza y proceso. La etiqueta verifica una categoría regulada; la experiencia sensorial depende de más variables.</p><h2>Una forma útil de pensar en “pata negra”</h2><p>En el marco normativo del ibérico, la expresión se reserva para productos de bellota 100 % ibéricos. Aun así, en una compra conviene buscar la denominación legal completa y el precinto en lugar de depender de una expresión coloquial.</p>';
$enAdd='<h2>What is distinctive about the full “acorn-fed 100% Iberian” designation</h2><p>The expression combines two dimensions that can vary independently in other Iberian products: feeding/production system and breed purity. The black seal therefore identifies a specific combination rather than acting as a loose synonym for “good ham”.</p><h2>How to check a black-seal product without turning shopping into an exam</h2><ol><li>Check that the legal sales name states <strong>acorn-fed 100% Iberian</strong>.</li><li>Verify the official black seal.</li><li>Distinguish ham from shoulder and whole-piece formats from sliced packs.</li><li>Only then compare producer, curing, weight, format and storage.</li></ol><p>For all seal colours, use '.emdo_pc_en(12924,'our black, red, green and white seal guide').'. For breed percentage alone, see '.emdo_pc_en(13086,'what 50%, 75% and 100% Iberian mean').'.</p><h2>What the black seal does not promise by itself</h2><p>It does not make two pieces taste identical or fix one exact fat level, curing time or yield. Producer, individual piece and process still create differences. The seal verifies a regulated category; sensory quality involves more variables.</p><h2>A useful way to understand “pata negra”</h2><p>Under the Iberian standard, the expression is reserved for acorn-fed 100% Iberian products. When buying, however, the full legal designation and official seal are more precise than relying on a colloquial phrase.</p>';
$es=emdo_pc_cut($es,'Qué información mirar además del precinto',$esAdd,['Jamones y paletas relacionados','Fuentes y referencias']);$en=emdo_pc_cut($en,'What to check beyond the seal',$enAdd,['Related hams and shoulders','Sources and references']);$results[]=emdo_pc_apply($id,$es,$en);

// 13086 — breed percentages only; colour seals become a short cross-reference.
$id=13086;$es=(string)get_post_field('post_content',$id);$en=(string)get_post_meta($id,'_en_US_post_content',true);
$es=emdo_pc_replace($es,'Cómo encajan las bridas negra, roja, verde y blanca','<h2>El porcentaje racial y el color del precinto son dos capas distintas</h2><p>El 50 %, 75 % o 100 % describe el porcentaje racial ibérico; el color del precinto clasifica la categoría comercial según alimentación y manejo. No hace falta repetir aquí las cuatro bridas: están explicadas una por una en '.emdo_pc_es(12924,'la guía de colores del jamón ibérico').'. Esta página se centra en genealogía, porcentaje y cómo leer ese dato.</p>');
// English article has a different structure; insert a scope note after the first H2 section.
$en=emdo_pc_replace($en,'Breed and feeding answer two different questions','<h2>Breed percentage and seal colour are two separate layers</h2><p>The 50%, 75% or 100% figure describes Iberian breed percentage; seal colour classifies the commercial category linked to feeding and production system. The four colours are explained individually in '.emdo_pc_en(12924,'our Iberian seal-colour guide').'. This page stays focused on genealogy, percentage and how to interpret that figure.</p>');$results[]=emdo_pc_apply($id,$es,$en);

echo "EMDO_PERFECTION_CORE_BEGIN\n".wp_json_encode(['updated'=>$results,'count'=>count($results)],JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES)."\nEMDO_PERFECTION_CORE_END\n";
