<?php
/** De-template PDO/regional clusters while preserving their canonical URLs and source sections. */
if (!defined('ABSPATH')) { exit; }
function emdo_po_norm($s){$s=html_entity_decode(wp_strip_all_tags((string)$s),ENT_QUOTES|ENT_HTML5,'UTF-8');$s=remove_accents(mb_strtolower($s,'UTF-8'));return trim(preg_replace('/\s+/u',' ',preg_replace('/[^a-z0-9]+/u',' ',$s)));}
function emdo_po_h2s($html){preg_match_all('/<h2\b[^>]*>.*?<\/h2>/isu',(string)$html,$m,PREG_OFFSET_CAPTURE);return $m[0]??[];}
function emdo_po_bounds($html,$heading){$hs=emdo_po_h2s($html);$want=emdo_po_norm($heading);foreach($hs as $i=>$h){if(emdo_po_norm($h[0])===$want){$start=$h[1];$end=isset($hs[$i+1])?$hs[$i+1][1]:strlen($html);return [$start,$end];}}return null;}
function emdo_po_extract($html,$heading){$b=emdo_po_bounds($html,$heading);return $b?substr($html,$b[0],$b[1]-$b[0]):'';}
function emdo_po_replace($html,$heading,$new){$b=emdo_po_bounds($html,$heading);if(!$b)return $html;return substr($html,0,$b[0]).$new.substr($html,$b[1]);}
function emdo_po_cut($html,$heading,$append,$preserve=[]){$kept='';foreach($preserve as $h){$s=emdo_po_extract($html,$h);if($s!=='')$kept.="\n".$s;} $b=emdo_po_bounds($html,$heading);if(!$b)return $html;return rtrim(substr($html,0,$b[0]))."\n".$append.$kept;}
function emdo_po_es($id,$label){return '<a href="'.esc_url(get_permalink($id)).'">'.esc_html($label).'</a>';}
function emdo_po_en_url($id){$slug=trim((string)get_post_meta($id,'_en_US_post_name',true));return rtrim(home_url('/'),'/').'/en/'.trim($slug,'/').'/';}
function emdo_po_en($id,$label){return '<a href="'.esc_url(emdo_po_en_url($id)).'">'.esc_html($label).'</a>';}
function emdo_po_words($html){preg_match_all('/[\p{L}\p{N}]+/u',wp_strip_all_tags((string)$html),$m);return count($m[0]);}
function emdo_po_apply($id,$es,$en){$p=get_post($id);if(!$p||$p->post_status!=='publish')throw new Exception("post $id is not published");if(emdo_po_words($es)<400||emdo_po_words($en)<360)throw new Exception("post $id too short after transform: ".emdo_po_words($es).'/'.emdo_po_words($en));wp_update_post(['ID'=>$id,'post_content'=>$es]);update_post_meta($id,'_en_US_post_content',$en);update_post_meta($id,'_en_US_ready','1');update_post_meta($id,'_en_US_published','1');update_post_meta($id,'_emdo_perfection_20260902','origin-v1');return ['id'=>$id,'es_words'=>emdo_po_words($es),'en_words'=>emdo_po_words($en)];}
$results=[];

// Iberian ham PDO hub.
$id=13852;$es=(string)get_post_field('post_content',$id);$en=(string)get_post_meta($id,'_en_US_post_content',true);
$esAdd='<h2>Mapa de las cuatro DOP: usa esta página como índice</h2><p>La utilidad de una guía general no está en repetir cuatro artículos específicos, sino en mostrar cómo se organiza el mapa. Guijuelo, Jabugo, Dehesa de Extremadura y Los Pedroches protegen nombres geográficos diferentes, con sus propios pliegos y organismos de control. Ninguna funciona como un “nivel” superior a las demás.</p><table><thead><tr><th>DOP</th><th>Qué buscar en la guía específica</th></tr></thead><tbody><tr><td>Guijuelo</td><td>Zona de elaboración, clima y reconocimiento de la certificación</td></tr><tr><td>Jabugo</td><td>Relación entre sierra, dehesa, elaboración y nombre protegido</td></tr><tr><td>Dehesa de Extremadura</td><td>Territorio extremeño, control y lectura de la etiqueta</td></tr><tr><td>Los Pedroches</td><td>Marco territorial cordobés y requisitos de la denominación</td></tr></tbody></table><p>Puedes continuar con '.emdo_po_es(13853,'DOP Guijuelo').', '.emdo_po_es(13854,'DOP Jabugo').', '.emdo_po_es(13855,'DOP Dehesa de Extremadura').' y '.emdo_po_es(13293,'DOP Los Pedroches').'.</p><h2>Cuándo mirar la DOP y cuándo mirar la brida</h2><p>La DOP te habla de una certificación geográfica y de un pliego; la brida del ibérico clasifica otra dimensión del producto. Al comprar, ambas informaciones se complementan. Para entender los colores del precinto, utiliza '.emdo_po_es(12924,'la guía de bridas del jamón ibérico').'.</p><h2>Qué no pretende responder este índice</h2><p>No intenta decidir cuál DOP “sabe mejor”, ni sustituye las páginas dedicadas a cada territorio. Tampoco presupone que todo jamón producido en una provincia pertenezca a una denominación. Su función SEO y editorial es clara: responder a la búsqueda general sobre denominaciones y conducir a la entidad concreta cuando el usuario ya sabe cuál quiere investigar.</p>';
$enAdd='<h2>Map of the four PDOs: use this page as an index</h2><p>A general guide should not repeat four specialist articles. Its job is to explain the map. Guijuelo, Jabugo, Dehesa de Extremadura and Los Pedroches protect different geographical names under their own specifications and control systems. None is simply a higher “quality level” than another.</p><table><thead><tr><th>PDO</th><th>What the specialist guide covers</th></tr></thead><tbody><tr><td>Guijuelo</td><td>Processing area, climate and certification</td></tr><tr><td>Jabugo</td><td>Mountain territory, dehesa, processing and the protected name</td></tr><tr><td>Dehesa de Extremadura</td><td>Extremaduran territory, controls and label reading</td></tr><tr><td>Los Pedroches</td><td>The Córdoba territory and the designation requirements</td></tr></tbody></table><p>Continue with '.emdo_po_en(13853,'Guijuelo PDO').', '.emdo_po_en(13854,'Jabugo PDO').', '.emdo_po_en(13855,'Dehesa de Extremadura PDO').' or '.emdo_po_en(13293,'Los Pedroches PDO').'.</p><h2>When to look at the PDO and when to look at the seal</h2><p>The PDO concerns geographical certification and a product specification; the Iberian colour seal classifies another dimension of the product. Both pieces of information can matter when buying. For the seal system, use '.emdo_po_en(12924,'our Iberian ham colour-seal guide').'.</p><h2>What this index deliberately does not answer</h2><p>It does not rank PDOs by taste, and it does not replace the dedicated territory pages. Nor does it imply that every ham made in a province belongs to a PDO. Its editorial role is to answer the broad designation query and then route readers to the specific entity they want to investigate.</p>';
$es=emdo_po_cut($es,'Cómo leer esta información en la práctica',$esAdd,['Fuentes y referencias']);$en=emdo_po_cut($en,'How to use this information in practice',$enAdd,['Sources and references']);$results[]=emdo_po_apply($id,$es,$en);

// Guijuelo.
$id=13853;$es=(string)get_post_field('post_content',$id);$en=(string)get_post_meta($id,'_en_US_post_content',true);
$esAdd='<h2>Preguntas específicas sobre Guijuelo</h2><h3>¿“Guijuelo” describe la alimentación del cerdo?</h3><p>No. Es un nombre geográfico protegido. La categoría de alimentación y manejo se identifica por la denominación de venta y el sistema de precintos del ibérico.</p><h3>¿Todo jamón elaborado cerca de Guijuelo pertenece a la DOP?</h3><p>No. Para usar la denominación protegida el producto debe estar certificado conforme a su pliego y controles. La proximidad geográfica por sí sola no sustituye la certificación.</p><h3>¿Por qué se habla tanto del clima?</h3><p>Porque la historia de la curación de la zona está ligada a condiciones ambientales concretas. Eso ayuda a entender la tradición productiva, pero no significa que el clima por sí solo determine el sabor final de cada pieza.</p><h2>Qué comparar entre dos productos Guijuelo certificados</h2><p>Una vez confirmada la DOP, compara categoría del ibérico, pieza —jamón o paleta—, peso, formato, productor y datos de curación disponibles. La denominación fija un marco común; dentro de ese marco sigue habiendo diversidad.</p><h2>Guías que complementan esta página</h2><p>Para comparar Guijuelo con las otras denominaciones, vuelve al '.emdo_po_es(13852,'mapa de DOP del jamón ibérico').'. Para entender el papel del clima sin limitarlo a una DOP, consulta '.emdo_po_es(13857,'cómo influye el clima en la curación').'.</p>';
$enAdd='<h2>Guijuelo-specific questions</h2><h3>Does “Guijuelo” describe how the pig was fed?</h3><p>No. It is a protected geographical name. Feeding and production category are identified through the legal sales designation and the Iberian seal system.</p><h3>Does every ham made near Guijuelo belong to the PDO?</h3><p>No. The protected name requires certification under the PDO specification and controls. Geographic proximity alone is not certification.</p><h3>Why is climate mentioned so often?</h3><p>The area’s curing tradition developed under particular environmental conditions. That context helps explain production history, but climate alone does not predetermine the flavour of every finished ham.</p><h2>What to compare between two certified Guijuelo products</h2><p>Once PDO certification is confirmed, compare the Iberian category, ham versus shoulder, weight, format, producer and available curing information. The PDO creates a common framework while still allowing meaningful diversity between products.</p><h2>Guides that complement this page</h2><p>To compare Guijuelo with other designations, return to '.emdo_po_en(13852,'the Iberian ham PDO map').'. For climate as a curing factor beyond one PDO, see '.emdo_po_en(13857,'how climate affects Iberian ham curing').'.</p>';
$es=emdo_po_cut($es,'Cómo leer esta información en la práctica',$esAdd,['Fuentes y referencias']);$en=emdo_po_cut($en,'How to use this information in practice',$enAdd,['Sources and references']);$results[]=emdo_po_apply($id,$es,$en);

// Jabugo.
$id=13854;$es=(string)get_post_field('post_content',$id);$en=(string)get_post_meta($id,'_en_US_post_content',true);
$esAdd='<h2>Preguntas que solo tienen sentido en una guía de Jabugo</h2><h3>¿Jabugo es solo el nombre de un pueblo?</h3><p>Jabugo es una localidad, pero en el etiquetado alimentario la DOP identifica una denominación protegida con territorio y condiciones definidas. Conviene distinguir el uso geográfico cotidiano del uso certificado.</p><h3>¿La palabra Jabugo sustituye a la categoría del ibérico?</h3><p>No. La DOP y la clasificación del ibérico aportan información diferente. Para una compra completa hay que leer ambas capas.</p><h3>¿La sierra explica por sí sola el sabor?</h3><p>No. El territorio forma parte del contexto de producción, pero genética, alimentación, pieza, salado, secado, bodega y tiempo también intervienen.</p><h2>Cómo reconocer que estás ante la DOP y no ante una referencia geográfica vaga</h2><p>Busca la identificación oficial de la denominación y la información de certificación correspondiente. Un nombre comercial que recuerde a la sierra o a Huelva no equivale automáticamente a producto amparado.</p><h2>Jabugo dentro del mapa ibérico</h2><p>Si quieres comparar esta denominación con Guijuelo, Dehesa de Extremadura y Los Pedroches sin repetir contenidos, utiliza '.emdo_po_es(13852,'la guía general de DOP del jamón ibérico').'.</p>';
$enAdd='<h2>Questions that belong specifically in a Jabugo guide</h2><h3>Is Jabugo only the name of a town?</h3><p>Jabugo is a town, but on food labels the PDO is a protected designation with a defined territory and specification. Everyday geographic usage should be distinguished from certified use of the name.</p><h3>Does the word Jabugo replace the Iberian category?</h3><p>No. PDO information and the Iberian commercial classification answer different questions. A complete purchase decision reads both layers.</p><h3>Does the mountain setting determine flavour by itself?</h3><p>No. Territory is part of the production context, but genetics, feeding, the individual cut, salting, drying, cellar ageing and time also matter.</p><h2>How to distinguish the PDO from a vague geographic reference</h2><p>Look for official designation identification and the corresponding certification information. A commercial name that evokes the mountains or Huelva is not automatically a PDO-certified product.</p><h2>Jabugo within the Iberian map</h2><p>To compare this designation with Guijuelo, Dehesa de Extremadura and Los Pedroches without duplicating four articles, use '.emdo_po_en(13852,'the general Iberian ham PDO guide').'.</p>';
$es=emdo_po_cut($es,'Cómo leer esta información en la práctica',$esAdd,['Fuentes y referencias']);$en=emdo_po_cut($en,'How to use this information in practice',$enAdd,['Sources and references']);$results[]=emdo_po_apply($id,$es,$en);

// Dehesa de Extremadura.
$id=13855;$es=(string)get_post_field('post_content',$id);$en=(string)get_post_meta($id,'_en_US_post_content',true);
$esAdd='<h2>Qué hace distinta la pregunta “Dehesa de Extremadura”</h2><p>Esta DOP obliga a separar dos conceptos que a menudo se mezclan: la dehesa como sistema agroganadero y Dehesa de Extremadura como nombre protegido. La existencia de dehesa en una explotación no convierte automáticamente cualquier jamón en producto DOP.</p><h2>Preguntas específicas</h2><h3>¿Toda pieza extremeña puede llevar la DOP?</h3><p>No. La procedencia regional no sustituye los requisitos, registros y controles de la denominación.</p><h3>¿La DOP significa que todas las piezas tienen el mismo perfil?</h3><p>No. Comparte un marco de certificación, pero la categoría del ibérico, el productor, la pieza y el proceso siguen generando diferencias.</p><h3>¿Dehesa de Extremadura y “jamón de Extremadura” son expresiones equivalentes?</h3><p>No conviene tratarlas como equivalentes. Una es una denominación protegida; la otra puede ser solo una referencia geográfica genérica.</p><h2>Cómo seguir investigando</h2><p>Para comprender la dehesa como sistema productivo, sin centrarte en una DOP, ve a '.emdo_po_es(13858,'la guía sobre dehesa y territorio').'. Para situar esta denominación junto a las otras tres, utiliza '.emdo_po_es(13852,'el mapa de DOP del jamón ibérico').'.</p>';
$enAdd='<h2>What makes the “Dehesa de Extremadura” question different</h2><p>This PDO requires a clear distinction between the dehesa as an agro-livestock system and Dehesa de Extremadura as a protected name. The presence of dehesa land does not automatically make any ham a PDO product.</p><h2>Specific questions</h2><h3>Can every ham from Extremadura carry the PDO?</h3><p>No. Regional origin alone does not replace the designation’s requirements, registration and controls.</p><h3>Does PDO status make every product taste the same?</h3><p>No. Products share a certification framework, but Iberian category, producer, individual piece and processing still create differences.</p><h3>Are “Dehesa de Extremadura” and “ham from Extremadura” equivalent terms?</h3><p>They should not be treated as equivalent. One is a protected designation; the other can be a generic geographical description.</p><h2>Where to continue</h2><p>For the dehesa as a production system rather than one PDO, see '.emdo_po_en(13858,'our guide to dehesa and territory').'. To place this designation beside the other three, use '.emdo_po_en(13852,'the Iberian ham PDO map').'.</p>';
$es=emdo_po_cut($es,'Cómo leer esta información en la práctica',$esAdd,['Fuentes y referencias']);$en=emdo_po_cut($en,'How to use this information in practice',$enAdd,['Sources and references']);$results[]=emdo_po_apply($id,$es,$en);

// Climate versus process cluster.
$id=13857;$es=(string)get_post_field('post_content',$id);$en=(string)get_post_meta($id,'_en_US_post_content',true);
$esAdd='<h2>Qué variables climáticas importan realmente</h2><p>Temperatura y humedad condicionan el intercambio de agua entre la pieza y el ambiente. También importa cómo cambian a lo largo del tiempo, porque la curación no es una fotografía de un día concreto. Históricamente, la ventilación natural y las estaciones ayudaban a modular ese proceso; hoy el elaborador puede apoyarse además en instalaciones con mayor capacidad de control.</p><h2>Clima no es lo mismo que secadero</h2><p>Esta página explica el entorno. Para entender qué decisiones se toman dentro del secadero y qué cambia después en bodega, utiliza '.emdo_po_es(13859,'la guía específica de secadero y bodega').'. Separar ambas preguntas evita atribuir al clima lo que depende del manejo del elaborador.</p><h2>Tres errores al interpretar el clima</h2><ul><li>Pensar que una provincia garantiza por sí sola un sabor concreto.</li><li>Suponer que más frío o más sequedad significan automáticamente más calidad.</li><li>Ignorar que la pieza, la grasa, el salado, el tiempo y el control del proceso interactúan con el ambiente.</li></ul><h2>Qué debe quedarse el lector</h2><p>El clima ha sido parte de la lógica histórica de la curación, pero actúa como una variable del sistema, no como una marca de calidad independiente.</p>';
$enAdd='<h2>Which climate variables actually matter</h2><p>Temperature and humidity influence water exchange between the ham and the surrounding air. Their evolution over time matters too because curing is not a snapshot of one day. Historically, natural ventilation and seasonal change helped modulate the process; modern producers can also use facilities with greater environmental control.</p><h2>Climate is not the same as the drying room</h2><p>This page explains the environment. For the decisions made inside the drying room and what later changes in the cellar, use '.emdo_po_en(13859,'our dedicated drying-room and cellar guide').'. Separating the questions prevents us from attributing to climate what actually depends on producer management.</p><h2>Three mistakes when interpreting climate</h2><ul><li>Assuming a province automatically guarantees one flavour.</li><li>Assuming colder or drier always means higher quality.</li><li>Ignoring the interaction between the piece, fat, salting, time, process control and environment.</li></ul><h2>What to remember</h2><p>Climate is part of the historical logic of curing, but it acts as one variable within a system rather than an independent quality mark.</p>';
$es=emdo_po_cut($es,'Cómo leer esta información en la práctica',$esAdd,['Fuentes y referencias']);$en=emdo_po_cut($en,'How to use this information in practice',$enAdd,['Sources and references']);$results[]=emdo_po_apply($id,$es,$en);

$id=13859;$es=(string)get_post_field('post_content',$id);$en=(string)get_post_meta($id,'_en_US_post_content',true);
$esAdd='<h2>El recorrido de la pieza: de controlar el secado a desarrollar madurez</h2><p>El secadero y la bodega cumplen funciones relacionadas pero no idénticas. En las primeras fases preocupa especialmente que la pérdida de agua sea progresiva y compatible con la evolución de la pieza. En bodega gana peso el tiempo de afinamiento, la transformación de aromas y la evaluación del elaborador.</p><h2>Qué controla el elaborador y qué observa</h2><p>No todo se reduce a fijar una temperatura. Se observa la evolución del peso, la grasa, la superficie, los aromas y el comportamiento general de la pieza. El conocimiento del lote permite decidir cuánto tiempo necesita y cuándo está listo.</p><h2>La cala pertenece al control del producto, no a una clasificación geográfica</h2><p>La cala y otras comprobaciones sensoriales ayudan a valorar la evolución de una pieza. No sustituyen la trazabilidad ni convierten un jamón en DOP. Son herramientas del proceso.</p><h2>Para entender el papel del ambiente exterior</h2><p>Esta página se centra en instalaciones y manejo. Si tu pregunta es por qué se habla de inviernos, humedad, ventilación o estaciones en las zonas jamoneras, consulta '.emdo_po_es(13857,'cómo influye el clima en la curación del jamón ibérico').'.</p>';
$enAdd='<h2>The journey of the ham: from controlled drying to mature development</h2><p>The drying room and cellar are related but not identical stages. Early on, gradual moisture loss and the physical evolution of the piece are central. In the cellar, extended maturation, aroma development and producer assessment become increasingly important.</p><h2>What the producer controls and what the producer observes</h2><p>The process is not reduced to setting one temperature. Weight change, fat, surface condition, aroma and the overall behaviour of each batch are observed. Experience helps determine how long a piece needs and when it is ready.</p><h2>The cala belongs to product assessment, not geographical classification</h2><p>The cala and other sensory checks help assess the evolution of a ham. They do not replace traceability or turn a ham into a PDO product. They are process tools.</p><h2>For the role of the external environment</h2><p>This page focuses on facilities and producer management. If your question is why winters, humidity, ventilation and seasons are so often discussed in ham-producing areas, see '.emdo_po_en(13857,'how climate affects Iberian ham curing').'.</p>';
$es=emdo_po_cut($es,'Cómo leer esta información en la práctica',$esAdd,['Fuentes y referencias']);$en=emdo_po_cut($en,'How to use this information in practice',$enAdd,['Sources and references']);$results[]=emdo_po_apply($id,$es,$en);

// Olive-oil PDO hub.
$id=13861;$es=(string)get_post_field('post_content',$id);$en=(string)get_post_meta($id,'_en_US_post_content',true);
$esAdd='<h2>Cómo usar esta guía: DOP como mapa, no como catálogo de sabores</h2><p>España reúne numerosas denominaciones oleícolas. Una página general debe ayudarte a interpretar qué protege una DOP y cómo llegar a la zona que te interesa, no copiar la ficha de cada consejo regulador.</p><h2>Cinco ejemplos para aprender a leer el mapa</h2><ul><li>'.emdo_po_es(13862,'Priego de Córdoba').': útil para entender la convivencia de Picuda, Hojiblanca y Picual.</li><li>'.emdo_po_es(13863,'Baena').': un ejemplo de diversidad varietal dentro de un territorio cordobés.</li><li>'.emdo_po_es(13864,'Sierra de Cazorla').': Picual y Royal permiten ver por qué una DOP no tiene por qué equivaler a una única variedad.</li><li>'.emdo_po_es(13865,'Sierra Mágina').': un caso donde relieve, Picual y territorio se leen juntos.</li><li>'.emdo_po_es(13866,'Montes de Toledo').': ayuda a entender la fuerte asociación entre Cornicabra y un área productora.</li></ul><h2>Qué información pertenece a una ficha DOP y qué información pertenece al AOVE</h2><p>La DOP acredita origen y cumplimiento de un pliego. La condición de virgen extra responde a requisitos de categoría del aceite. Variedad, cosecha, filtrado, fecha, conservación y perfil sensorial añaden otras capas. Leer una botella bien consiste en juntar esas piezas sin convertir una sola de ellas en garantía absoluta.</p><h2>Cuándo abandonar el hub y entrar en una guía específica</h2><p>En cuanto tu búsqueda incluya el nombre de una denominación concreta, la página especializada debe ser la referencia principal. Este hub queda deliberadamente más panorámico para no competir con ellas.</p>';
$enAdd='<h2>How to use this guide: PDO as a map, not a flavour catalogue</h2><p>Spain has many olive-oil designations. A general page should explain what a PDO protects and help readers reach the territory they care about, rather than copying every regulatory council’s profile.</p><h2>Five examples for learning to read the map</h2><ul><li>'.emdo_po_en(13862,'Priego de Córdoba').': a useful example of Picuda, Hojiblanca and Picual sharing one PDO.</li><li>'.emdo_po_en(13863,'Baena').': shows varietal diversity within a Córdoba territory.</li><li>'.emdo_po_en(13864,'Sierra de Cazorla').': Picual and Royal show why one PDO need not equal one variety.</li><li>'.emdo_po_en(13865,'Sierra Mágina').': a case where relief, Picual and territory are read together.</li><li>'.emdo_po_en(13866,'Montes de Toledo').': helps explain the close association between Cornicabra and a producing area.</li></ul><h2>What belongs to PDO information and what belongs to EVOO information</h2><p>The PDO certifies origin and compliance with a specification. Extra-virgin status concerns the oil category. Variety, harvest, filtration, date, storage and sensory profile add further layers. Good label reading means combining those layers rather than treating one as an absolute guarantee.</p><h2>When to leave the hub and open a specialist guide</h2><p>As soon as a search includes the name of a specific designation, the specialist page should become the primary reference. This hub is deliberately panoramic so it does not compete with those entity pages.</p>';
$es=emdo_po_cut($es,'Cómo leer esta información en la práctica',$esAdd,['Fuentes y referencias']);$en=emdo_po_cut($en,'How to use this information in practice',$enAdd,['Sources and references']);$results[]=emdo_po_apply($id,$es,$en);

// Priego.
$id=13862;$es=(string)get_post_field('post_content',$id);$en=(string)get_post_meta($id,'_en_US_post_content',true);
$esAdd='<h2>Preguntas específicas de Priego de Córdoba</h2><h3>¿La DOP Priego de Córdoba significa “aceite Picuda”?</h3><p>No. Picuda es especialmente representativa, pero la denominación se entiende mejor junto con Hojiblanca y Picual. La composición varietal de un aceite concreto debe leerse en su información de producto.</p><h3>¿Todos los AOVE de la provincia de Córdoba son Priego de Córdoba?</h3><p>No. La DOP corresponde a un territorio y pliego determinados. Córdoba tiene además otras denominaciones oleícolas.</p><h3>¿La altitud fija un sabor único?</h3><p>No. Pendiente y altitud forman parte del contexto agronómico, pero cosecha, madurez de la aceituna, elaboración y mezcla varietal influyen en el perfil final.</p><h2>Qué mirar en una botella de esta DOP</h2><p>Primero verifica la certificación; después mira variedades declaradas, campaña o cosecha cuando figure, formato y condiciones de conservación. Para situar Priego dentro del conjunto nacional, vuelve a '.emdo_po_es(13861,'la guía de DOP del aceite de oliva en España').'.</p>';
$enAdd='<h2>Priego de Córdoba-specific questions</h2><h3>Does Priego de Córdoba PDO simply mean “Picuda oil”?</h3><p>No. Picuda is highly representative, but the designation is better understood alongside Hojiblanca and Picual. The varietal composition of a particular oil should be read on that product’s information.</p><h3>Are all EVOOs from Córdoba province Priego de Córdoba?</h3><p>No. The PDO applies to a defined territory and specification, and Córdoba also contains other olive-oil designations.</p><h3>Does altitude create one fixed flavour?</h3><p>No. Slope and altitude are part of the agronomic context, but harvest timing, fruit maturity, milling and varietal composition all affect the finished profile.</p><h2>What to check on a bottle</h2><p>First verify certification; then look at declared varieties, harvest information when available, format and storage. To place Priego within the national picture, return to '.emdo_po_en(13861,'our Spanish olive-oil PDO guide').'.</p>';
$es=emdo_po_cut($es,'Cómo leer esta información en la práctica',$esAdd,['Fuentes y referencias']);$en=emdo_po_cut($en,'How to use this information in practice',$enAdd,['Sources and references']);$results[]=emdo_po_apply($id,$es,$en);

// Baena.
$id=13863;$es=(string)get_post_field('post_content',$id);$en=(string)get_post_meta($id,'_en_US_post_content',true);
$esAdd='<h2>Baena se entiende mejor como territorio varietal que como un sabor único</h2><p>Una de las claves de esta denominación es no reducirla a una sola aceituna. Picudo tiene una identidad clara en la zona, pero convive con otras variedades. Esa diversidad permite aceites con equilibrios diferentes sin dejar de pertenecer a la misma DOP.</p><h2>Preguntas específicas de Baena</h2><h3>¿Picudo y Picual son lo mismo?</h3><p>No. Son variedades distintas y no conviene tratarlas como variantes de un mismo nombre.</p><h3>¿Un coupage de varias variedades puede pertenecer a la DOP?</h3><p>La pertenencia depende del cumplimiento del pliego, no de que el aceite sea obligatoriamente monovarietal. La composición concreta debe comprobarse en el producto.</p><h3>¿Amargor significa defecto?</h3><p>No por sí mismo. En un aceite virgen, amargor y picor pueden formar parte del perfil sensorial; los defectos se evalúan bajo criterios específicos.</p><h2>Baena dentro del mapa de Córdoba</h2><p>Para no confundir esta denominación con Priego de Córdoba u otras zonas, utiliza '.emdo_po_es(13861,'el mapa general de DOP españolas').' como índice y mantén esta página para consultas específicas sobre Baena.</p>';
$enAdd='<h2>Baena is better understood as a varietal territory than as one fixed flavour</h2><p>A key to this designation is avoiding reduction to a single olive. Picudo has a strong identity in the area, but it coexists with other varieties. That diversity allows different balances and styles within the same PDO.</p><h2>Baena-specific questions</h2><h3>Are Picudo and Picual the same variety?</h3><p>No. They are distinct varieties and should not be treated as alternative names for the same olive.</p><h3>Can a multi-variety blend belong to the PDO?</h3><p>PDO status depends on compliance with the specification, not on being automatically monovarietal. The composition of a specific oil should be checked on that product.</p><h3>Does bitterness mean a defect?</h3><p>Not by itself. In virgin olive oil, bitterness and pungency can be legitimate sensory attributes; defects are assessed under specific criteria.</p><h2>Baena within the Córdoba map</h2><p>To avoid confusing this designation with Priego de Córdoba or other areas, use '.emdo_po_en(13861,'the general Spanish PDO map').' as the index and keep this page for Baena-specific questions.</p>';
$es=emdo_po_cut($es,'Cómo leer esta información en la práctica',$esAdd,['Fuentes y referencias']);$en=emdo_po_cut($en,'How to use this information in practice',$enAdd,['Sources and references']);$results[]=emdo_po_apply($id,$es,$en);

// Sierra de Cazorla.
$id=13864;$es=(string)get_post_field('post_content',$id);$en=(string)get_post_meta($id,'_en_US_post_content',true);
$esAdd='<h2>Por qué Royal merece una pregunta propia dentro de Sierra de Cazorla</h2><p>Picual domina buena parte del paisaje jiennense, pero Royal ayuda a entender la singularidad de esta DOP. Encontrar un aceite con Royal no significa que vaya a tener un sabor predeterminado; sí señala una variedad local que merece leerse de forma diferenciada.</p><h2>Preguntas específicas de Cazorla</h2><h3>¿Todo aceite de la DOP es monovarietal Picual?</h3><p>No debe darse por supuesto. Revisa la composición declarada del producto y el marco del pliego.</p><h3>¿Royal es una categoría de calidad?</h3><p>No. Es una variedad de aceituna, no un nivel superior o inferior a Picual.</p><h3>¿“Sierra de Cazorla” equivale a cualquier aceite producido en la comarca?</h3><p>No. El uso de la DOP exige certificación y cumplimiento de sus requisitos.</p><h2>Cómo seguir</h2><p>Si tu interés es el conjunto provincial, entra en '.emdo_po_es(14096,'la guía de aceites de Jaén').'. Si quieres comparar denominaciones españolas, utiliza '.emdo_po_es(13861,'el hub de DOP del aceite de oliva').'.</p>';
$enAdd='<h2>Why Royal deserves its own question within Sierra de Cazorla</h2><p>Picual dominates much of Jaén’s olive landscape, but Royal helps explain what makes this PDO distinctive. Finding Royal on a label does not predetermine flavour, but it does identify a local variety worth reading separately.</p><h2>Cazorla-specific questions</h2><h3>Is every PDO oil a monovarietal Picual?</h3><p>That should not be assumed. Check the product’s declared composition and the PDO specification.</p><h3>Is Royal a quality category?</h3><p>No. It is an olive variety, not a higher or lower quality level than Picual.</p><h3>Does “Sierra de Cazorla” mean any oil made in the area?</h3><p>No. Use of the PDO requires certification and compliance with its rules.</p><h2>Where to continue</h2><p>For the province-wide picture, use '.emdo_po_en(14096,'our guide to oils from Jaén').'. To compare Spanish designations, use '.emdo_po_en(13861,'the olive-oil PDO hub').'.</p>';
$es=emdo_po_cut($es,'Cómo leer esta información en la práctica',$esAdd,['Fuentes y referencias']);$en=emdo_po_cut($en,'How to use this information in practice',$enAdd,['Sources and references']);$results[]=emdo_po_apply($id,$es,$en);

// Sierra Magina.
$id=13865;$es=(string)get_post_field('post_content',$id);$en=(string)get_post_meta($id,'_en_US_post_content',true);
$esAdd='<h2>Sierra Mágina no es simplemente “otro Picual de Jaén”</h2><p>Picual es central, pero el interés de una DOP territorial está precisamente en leer variedad y lugar conjuntamente. Relieve, orientación, manejo del olivar y campaña forman un contexto que no se resume con una sola palabra en la etiqueta.</p><h2>Preguntas específicas de Mágina</h2><h3>¿Manzanillo de Jaén sustituye a Picual como variedad principal?</h3><p>No. Su presencia ayuda a explicar diversidad local, mientras Picual sigue siendo una referencia estructural de la zona.</p><h3>¿Un olivar en pendiente produce automáticamente un aceite más intenso?</h3><p>No. La pendiente condiciona cultivo y manejo, pero el perfil sensorial depende también de variedad, madurez, cosecha y elaboración.</p><h3>¿Las notas verdes garantizan que un aceite sea de Sierra Mágina?</h3><p>No. Son descriptores sensoriales y pueden aparecer en aceites de muchos orígenes.</p><h2>Qué página usar según tu búsqueda</h2><p>Para otras DOP jiennenses y la IGP provincial, consulta '.emdo_po_es(14096,'aceites de Jaén').'. Para la lógica general de las denominaciones, vuelve a '.emdo_po_es(13861,'DOP del aceite de oliva en España').'.</p>';
$enAdd='<h2>Sierra Mágina is not simply “another Picual from Jaén”</h2><p>Picual is central, but the point of a territorial PDO is to read variety and place together. Relief, orientation, grove management and the specific harvest form a context that cannot be reduced to one word on the label.</p><h2>Mágina-specific questions</h2><h3>Does Manzanillo de Jaén replace Picual as the main variety?</h3><p>No. Its presence helps explain local diversity while Picual remains a structural reference in the area.</p><h3>Does a hillside grove automatically produce a more intense oil?</h3><p>No. Slope affects cultivation and management, but sensory profile also depends on variety, maturity, harvest and milling.</p><h3>Do green tasting notes prove Sierra Mágina origin?</h3><p>No. They are sensory descriptors and can occur in oils from many origins.</p><h2>Which page to use for which search</h2><p>For other Jaén designations and the province-wide PGI, use '.emdo_po_en(14096,'our oils of Jaén guide').'. For the general designation system, return to '.emdo_po_en(13861,'Spanish olive-oil PDOs').'.</p>';
$es=emdo_po_cut($es,'Cómo leer esta información en la práctica',$esAdd,['Fuentes y referencias']);$en=emdo_po_cut($en,'How to use this information in practice',$enAdd,['Sources and references']);$results[]=emdo_po_apply($id,$es,$en);

// Montes de Toledo.
$id=13866;$es=(string)get_post_field('post_content',$id);$en=(string)get_post_meta($id,'_en_US_post_content',true);
$esAdd='<h2>Cornicabra como eje, no como sinónimo automático de la DOP</h2><p>Cornicabra es fundamental para entender Montes de Toledo, pero variedad y denominación no son conceptos intercambiables. Puede existir Cornicabra fuera de esta DOP, y un aceite solo puede usar el nombre protegido cuando cumple el pliego y está certificado.</p><h2>Preguntas específicas de Montes de Toledo</h2><h3>¿Todo Cornicabra es Montes de Toledo?</h3><p>No. La variedad puede cultivarse en otros lugares.</p><h3>¿El nombre “Montes de Toledo” describe solo la provincia de Toledo?</h3><p>La denominación responde a su zona geográfica definida y no debe deducirse únicamente de los límites administrativos sugeridos por el nombre.</p><h3>¿Cornicabra tiene siempre el mismo amargor y picor?</h3><p>No. Variedad, madurez, cosecha, elaboración y conservación modifican la expresión sensorial.</p><h2>Cómo colocar esta DOP en el mapa</h2><p>Para ampliar a otras zonas de Castilla-La Mancha, utiliza '.emdo_po_es(14098,'la guía regional de aceites de Castilla-La Mancha').'. Para comparar la función de las DOP en España, consulta '.emdo_po_es(13861,'el hub nacional').'.</p>';
$enAdd='<h2>Cornicabra as the axis, not an automatic synonym for the PDO</h2><p>Cornicabra is fundamental to understanding Montes de Toledo, but variety and designation are not interchangeable concepts. Cornicabra can exist outside this PDO, and an oil can use the protected name only when it meets the specification and is certified.</p><h2>Montes de Toledo-specific questions</h2><h3>Is every Cornicabra oil Montes de Toledo?</h3><p>No. The variety can be grown elsewhere.</p><h3>Does the name describe only Toledo province?</h3><p>The PDO follows its defined geographical area and should not be inferred solely from the administrative boundaries suggested by the name.</p><h3>Does Cornicabra always have the same bitterness and pungency?</h3><p>No. Variety interacts with maturity, harvest, milling and storage to shape sensory expression.</p><h2>Placing this PDO on the map</h2><p>For other Castilla-La Mancha areas, use '.emdo_po_en(14098,'our regional oils of Castilla-La Mancha guide').'. To compare the role of PDOs across Spain, use '.emdo_po_en(13861,'the national hub').'.</p>';
$es=emdo_po_cut($es,'Cómo leer esta información en la práctica',$esAdd,['Fuentes y referencias']);$en=emdo_po_cut($en,'How to use this information in practice',$enAdd,['Sources and references']);$results[]=emdo_po_apply($id,$es,$en);

// Murcia regional hub: become a decision map instead of repeating two PDO pages.
$id=14022;$es=(string)get_post_field('post_content',$id);$en=(string)get_post_meta($id,'_en_US_post_content',true);
$esAdd='<h2>Tres expresiones para orientarse, no tres artículos dentro del mismo artículo</h2><table><thead><tr><th>Qué buscas</th><th>Ruta más útil</th></tr></thead><tbody><tr><td>Queso fresco, húmedo y de consumo rápido</td><td>Queso de Murcia fresco</td></tr><tr><td>Una versión madurada de la DOP Queso de Murcia</td><td>Queso de Murcia curado</td></tr><tr><td>Una corteza trabajada mediante baños de vino</td><td>Murcia al Vino DOP</td></tr></tbody></table><p>Este cuadro sirve para elegir una ruta. Los detalles de elaboración, requisitos y reconocimiento pertenecen a las páginas específicas.</p><h2>Cuándo abrir cada guía específica</h2><p>Para Queso de Murcia fresco y curado, ve a '.emdo_po_es(13963,'Queso de Murcia DOP').'. Para el producto de corteza vínica, utiliza '.emdo_po_es(13907,'Queso de Murcia al Vino DOP').'. De este modo el hub regional responde “qué quesos protegidos hay en Murcia y cómo se relacionan”, mientras cada artículo de entidad responde “qué es exactamente esta DOP”.</p><h2>Una cata murciana que sí muestra diferencias</h2><p>Si pruebas las tres expresiones, ordénalas desde la más húmeda y delicada hasta la más madurada o aromáticamente marcada. El objetivo no es declarar un ganador, sino percibir cómo una misma base caprina puede dar resultados distintos cuando cambian humedad, maduración y trabajo de corteza.</p><h2>Qué mirar al comprar queso murciano</h2><p>No utilices “queso de cabra de Murcia” como sinónimo automático de DOP. Comprueba el nombre protegido cuando esa certificación sea importante para ti y, después, elige formato y maduración según el uso.</p>';
$enAdd='<h2>Three expressions to navigate, not three full articles inside one hub</h2><table><thead><tr><th>What you want</th><th>Most useful route</th></tr></thead><tbody><tr><td>A fresh, high-moisture cheese for quick consumption</td><td>Fresh Queso de Murcia</td></tr><tr><td>A matured expression of Queso de Murcia PDO</td><td>Cured Queso de Murcia</td></tr><tr><td>A rind developed through wine washing</td><td>Murcia al Vino PDO</td></tr></tbody></table><p>The table helps choose a route. Detailed production rules, requirements and identification belong on the specialist pages.</p><h2>When to open each specialist guide</h2><p>For fresh and cured Queso de Murcia, use '.emdo_po_en(13963,'Queso de Murcia PDO').'. For the wine-washed product, use '.emdo_po_en(13907,'Murcia al Vino PDO').'. The regional hub now answers “which protected Murcia cheeses are there and how do they relate?”, while the entity pages answer “what exactly is this PDO?”.</p><h2>A Murcia tasting that actually shows the differences</h2><p>If tasting the three expressions, move from the most moist and delicate towards the more matured or aromatically marked. The point is not to name a winner, but to notice how the same broad goat-milk tradition can produce different results as moisture, maturation and rind treatment change.</p><h2>What to check when buying Murcia cheese</h2><p>Do not use “goat cheese from Murcia” as an automatic synonym for PDO status. Verify the protected name when certification matters, then choose format and maturation according to use.</p>';
$es=emdo_po_cut($es,'Queso de Murcia fresco: humedad y delicadeza',$esAdd,['Fuentes y referencias']);$en=emdo_po_cut($en,'Fresh Queso de Murcia: moisture and delicacy',$enAdd,['Sources and references']);$results[]=emdo_po_apply($id,$es,$en);

// Andalusia hub versus Grazalema child page.
$id=14088;$es=(string)get_post_field('post_content',$id);$en=(string)get_post_meta($id,'_en_US_post_content',true);
$es=emdo_po_replace($es,'Denominaciones, nombres tradicionales y sellos','<h2>Cómo leer los nombres queseros en una región tan amplia</h2><p>Andalucía combina nombres tradicionales, razas ganaderas, zonas de producción, marcas comerciales y figuras de calidad. No todos esos nombres tienen el mismo valor legal. En una guía regional conviene explicar el mapa sin convertir cada tradición local en una supuesta DOP o IGP.</p>');
$en=emdo_po_replace($en,'Protected names, traditional names and labels','<h2>How to read cheese names across such a large region</h2><p>Andalusia combines traditional names, livestock breeds, producing areas, commercial brands and quality schemes. Those names do not all have the same legal meaning. A regional guide should explain the map without turning every local tradition into an assumed PDO or PGI.</p>');
$es=emdo_po_replace($es,'Dónde encaja Grazalema dentro del conjunto andaluz','<h2>Grazalema es una subzona importante, pero no resume Andalucía</h2><p>La Sierra de Grazalema merece una guía propia por la presencia de la cabra Payoya, la Merina de Grazalema y una tradición quesera muy reconocible. Para esos detalles utiliza '.emdo_po_es(14089,'la guía específica de quesos de la Sierra de Grazalema').'. Aquí el foco permanece en el conjunto andaluz: Cádiz, Málaga y otras áreas no deben quedar reducidas a una sola sierra.</p>');
$en=emdo_po_replace($en,'Where Grazalema fits inside the Andalusian picture','<h2>Grazalema is important, but it does not summarise Andalusia</h2><p>Sierra de Grazalema deserves its own guide because of the Payoya goat, Merina de Grazalema sheep and a recognisable cheese tradition. For those details, use '.emdo_po_en(14089,'our dedicated Sierra de Grazalema cheese guide').'. This page remains regional in scope: Cádiz, Málaga and other Andalusian areas should not be reduced to a single mountain zone.</p>');
$esAdd='<h2>Cómo recorrer el mapa andaluz sin repetir una guía local</h2><p>Empieza por la leche y el territorio: cabra en diferentes sistemas, oveja en áreas serranas y quesos de mezcla cuando corresponda. Después mira textura y maduración. Esta secuencia permite comparar estilos regionales sin convertir “queso andaluz” en un sabor único.</p><h2>Qué pregunta responde esta página</h2><p>Responde qué diversidad quesera existe en Andalucía y cómo orientarse por zonas y estilos. Cuando la consulta se vuelve local —Grazalema, Payoya, una raza o una elaboración concreta— la guía especializada debe asumir el protagonismo.</p>';
$enAdd='<h2>How to explore the Andalusian map without repeating a local guide</h2><p>Start with milk and territory: goat cheeses from different production systems, sheep cheeses in mountain areas and mixed-milk styles where relevant. Then compare texture and maturation. This sequence lets readers understand regional diversity without pretending that “Andalusian cheese” has one fixed flavour.</p><h2>What question this page answers</h2><p>It answers what kinds of cheese diversity exist across Andalusia and how to navigate areas and styles. Once the query becomes local—Grazalema, Payoya, a breed or a specific production tradition—the specialist guide should take over.</p>';
$es=emdo_po_cut($es,'Preguntas relacionadas',$esAdd,['Fuentes y referencias']);$en=emdo_po_cut($en,'Related questions',$enAdd,['Sources and references']);$results[]=emdo_po_apply($id,$es,$en);

$id=14089;$es=(string)get_post_field('post_content',$id);$en=(string)get_post_meta($id,'_en_US_post_content',true);
$es=emdo_po_replace($es,'Denominaciones, nombres tradicionales y sellos','<h2>Qué está protegido, qué es raza y qué es tradición local</h2><p>En Grazalema es especialmente importante no mezclar categorías. Payoya es una raza caprina; “Payoyo” puede aparecer como referencia comercial y no debe convertirse en nombre genérico de una DOP inexistente. Merina de Grazalema es una raza ovina. Los quesos de la sierra pueden apoyarse en estas identidades sin que todos compartan una única figura de protección.</p>');
$en=emdo_po_replace($en,'Protected names, traditional names and labels','<h2>What is protected, what is a breed and what is local tradition</h2><p>In Grazalema it is especially important not to mix categories. Payoya is a goat breed; “Payoyo” may appear commercially and should not be turned into the generic name of a non-existent PDO. Merina de Grazalema is a sheep breed. Cheeses from the mountains can draw on these identities without all sharing one protection scheme.</p>');
$esAdd='<h2>Por qué esta sierra produce una búsqueda distinta de “quesos de Andalucía”</h2><p>Aquí el usuario normalmente quiere bajar de escala: Villaluenga del Rosario, ganadería de montaña, cabra Payoya, Merina de Grazalema y estilos asociados a una comarca concreta. Por eso esta página entra en el detalle local y deja el panorama autonómico en '.emdo_po_es(14088,'la guía de quesos de Andalucía').'.</p><h2>Cómo comparar quesos de Grazalema</h2><p>No uses únicamente la palabra “payoya” como criterio. Comprueba especie de leche, posible mezcla, tratamiento de la leche, maduración, corteza y productor. Dos quesos de la misma sierra pueden ser deliberadamente distintos.</p><h2>Un itinerario de degustación local</h2><p>Una cata útil puede empezar por piezas más jóvenes y húmedas, continuar con maduraciones medias y terminar con estilos más firmes o intensos. Si incluyes cabra y oveja, prueba a mantener maduraciones comparables para percibir mejor qué aporta cada leche.</p>';
$enAdd='<h2>Why this mountain area creates a different search from “cheeses of Andalusia”</h2><p>Here the reader usually wants to zoom in: Villaluenga del Rosario, mountain livestock, Payoya goats, Merina de Grazalema sheep and styles associated with a specific area. This page therefore goes local and leaves the autonomous-region panorama to '.emdo_po_en(14088,'our cheeses of Andalusia guide').'.</p><h2>How to compare Grazalema cheeses</h2><p>Do not use the word “Payoya” as the only criterion. Check milk species, possible blends, milk treatment, maturation, rind and producer. Two cheeses from the same mountains can be intentionally very different.</p><h2>A local tasting sequence</h2><p>A useful tasting can begin with younger, moister cheeses, move through medium maturation and finish with firmer or more intense styles. If comparing goat and sheep milk, keeping maturation broadly similar can make the milk differences easier to notice.</p>';
$es=emdo_po_cut($es,'Preguntas relacionadas',$esAdd,['Fuentes y referencias']);$en=emdo_po_cut($en,'Related questions',$enAdd,['Sources and references']);$results[]=emdo_po_apply($id,$es,$en);

echo "EMDO_PERFECTION_ORIGIN_BEGIN\n".wp_json_encode(['updated'=>$results,'count'=>count($results)],JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES)."\nEMDO_PERFECTION_ORIGIN_END\n";
