<?php
/** Production deploy: remaining commercial SEO structure for legumes, cured meats, preserves and packs. */
if (!defined('ABSPATH')) { fwrite(STDERR, "WordPress is not loaded.\n"); exit(1); }

function emdo_ec_norm($s){ return trim(preg_replace('/\s+/', ' ', remove_accents(mb_strtolower((string)$s)))); }
function emdo_ec_term($slug){ $t=get_term_by('slug',$slug,'product_cat'); if(!$t||is_wp_error($t)) throw new Exception('Missing category '.$slug); return $t; }
function emdo_ec_products($term_id){
  $q=new WP_Query(array('post_type'=>'product','post_status'=>'publish','posts_per_page'=>-1,'fields'=>'ids','no_found_rows'=>true,'tax_query'=>array(array('taxonomy'=>'product_cat','field'=>'term_id','terms'=>array((int)$term_id),'include_children'=>false)),'orderby'=>'title','order'=>'ASC'));
  $ids=array(); foreach($q->posts as $id){ $p=wc_get_product($id); if($p&&$p->is_in_stock()) $ids[]=(int)$id; } return array_values(array_unique($ids));
}
function emdo_ec_filter($ids,$include,$exclude=array()){
  $out=array(); foreach($ids as $id){ $hay=emdo_ec_norm(get_the_title($id).' '.get_post_field('post_name',$id)); $ok=false; foreach($include as $n){ if(strpos($hay,emdo_ec_norm($n))!==false){$ok=true;break;} } if(!$ok) continue; $bad=false; foreach($exclude as $n){ if(strpos($hay,emdo_ec_norm($n))!==false){$bad=true;break;} } if(!$bad) $out[]=(int)$id; } return array_values(array_unique($out));
}
function emdo_ec_shortcode($ids){ $live=array(); foreach(array_unique(array_map('intval',$ids)) as $id){ if(get_post_status($id)==='publish') $live[]=$id; } return $live?'[products ids="'.implode(',',$live).'" columns="3" orderby="post__in"]':''; }
function emdo_ec_aioseo($post_id,$title,$desc){ global $wpdb; $table=$wpdb->prefix.'aioseo_posts'; if($wpdb->get_var($wpdb->prepare('SHOW TABLES LIKE %s',$table))!==$table)return; $rid=(int)$wpdb->get_var($wpdb->prepare("SELECT id FROM `{$table}` WHERE post_id=%d LIMIT 1",$post_id)); if($rid)$wpdb->update($table,array('title'=>$title,'description'=>$desc),array('id'=>$rid),array('%s','%s'),array('%d')); }
function emdo_ec_page_id($key){ $ids=get_posts(array('post_type'=>'page','post_status'=>array('publish','draft','private'),'posts_per_page'=>1,'fields'=>'ids','no_found_rows'=>true,'meta_key'=>'_emdo_ec_landing_key','meta_value'=>$key)); return $ids?(int)$ids[0]:0; }
function emdo_ec_upsert($c){
  if(count($c['products'])<2) return null; $sc=emdo_ec_shortcode($c['products']); if($sc==='') return null;
  $es=str_replace('{{PRODUCTS}}',$sc,$c['es_content']); $en=str_replace('{{PRODUCTS}}',$sc,$c['en_content']);
  $id=emdo_ec_page_id($c['key']); if(!$id){$e=get_page_by_path($c['es_slug'],OBJECT,'page'); if($e instanceof WP_Post)$id=(int)$e->ID;}
  $a=array('post_type'=>'page','post_status'=>'publish','post_title'=>$c['es_title'],'post_name'=>$c['es_slug'],'post_content'=>$es,'post_excerpt'=>$c['es_meta'],'comment_status'=>'closed','ping_status'=>'closed'); if($id)$a['ID']=$id;
  $saved=wp_insert_post(wp_slash($a),true); if(is_wp_error($saved))throw new Exception($saved->get_error_message()); $id=(int)$saved;
  update_post_meta($id,'_emdo_ec_landing_key',$c['key']); update_post_meta($id,'_en_US_post_title','<span data-no-translation>'.$c['en_title'].'</span>'); update_post_meta($id,'_en_US_post_name',$c['en_slug']); update_post_meta($id,'_en_US_post_excerpt',$c['en_meta']); update_post_meta($id,'_en_US_post_content','<span data-no-translation>'.$en.'</span>'); update_post_meta($id,'_en_US_published','1'); emdo_ec_aioseo($id,$c['seo_title'],$c['es_meta']);
  return array('key'=>$c['key'],'groups'=>$c['groups'],'id'=>$id,'es_title'=>$c['es_title'],'en_title'=>$c['en_title'],'es_url'=>home_url('/'.$c['es_slug'].'/'),'en_url'=>home_url('/en/'.$c['en_slug'].'/'),'products'=>array_values(array_map('intval',$c['products'])));
}
function emdo_ec_category_block($term,$es_heading,$es_text,$en_heading,$en_text,$links){
  $start='<!-- emdo-ec-commercial-start -->'; $end='<!-- emdo-ec-commercial-end -->'; $pattern='/\s*'.preg_quote($start,'/').'.*?'.preg_quote($end,'/').'\s*/s';
  $es=preg_replace($pattern,"\n",(string)$term->description); $en=preg_replace($pattern,"\n",(string)get_term_meta((int)$term->term_id,'_en_US_description',true));
  $es_links=array();$en_links=array(); foreach($links as $p){ if(!$p)continue; $es_links[]='<a href="'.esc_url($p['es_url']).'">'.esc_html($p['es_title']).'</a>'; $en_links[]='<a href="'.esc_url($p['en_url']).'">'.esc_html($p['en_title']).'</a>'; }
  $es_block=$start.'<section class="emdo-commercial-category"><h2>'.esc_html($es_heading).'</h2><p>'.$es_text.'</p>'.($es_links?'<p><strong>Explora por tipo:</strong> '.implode(' · ',$es_links).'</p>':'').'</section>'.$end;
  $r=wp_update_term((int)$term->term_id,'product_cat',array('description'=>trim($es)."\n\n".$es_block)); if(is_wp_error($r))throw new Exception($r->get_error_message());
  $en_block=$start.'<section class="emdo-commercial-category"><h2>'.esc_html($en_heading).'</h2><p>'.$en_text.'</p>'.($en_links?'<p><strong>Shop by type:</strong> '.implode(' · ',$en_links).'</p>':'').'</section>'.$end;
  update_term_meta((int)$term->term_id,'_en_US_description',trim($en)."\n\n".$en_block);
}
function emdo_ec_existing_page($slug,$es_title,$en_title,$en_slug){ $p=get_page_by_path($slug,OBJECT,'page'); if(!$p)return null; return array('es_title'=>$es_title,'en_title'=>$en_title,'es_url'=>home_url('/'.$slug.'/'),'en_url'=>home_url('/en/'.$en_slug.'/')); }

$leg=emdo_ec_term('legumbres'); $emb=emdo_ec_term('embutidos-y-curados'); $con=emdo_ec_term('conservas'); $packs=emdo_ec_term('packs-y-lotes');
$leg_ids=emdo_ec_products($leg->term_id); $emb_ids=emdo_ec_products($emb->term_id); $con_ids=emdo_ec_products($con->term_id); $pack_ids=emdo_ec_products($packs->term_id);
$groups=array(
 'chorizo'=>emdo_ec_filter($emb_ids,array('chorizo'),array('pack','surtido')),
 'salchichon'=>emdo_ec_filter($emb_ids,array('salchichon'),array('pack','surtido')),
 'lomo'=>emdo_ec_filter($emb_ids,array('lomo','lomito'),array('pack','surtido')),
 'loncheados'=>emdo_ec_filter($emb_ids,array('sobres')),
 'surtidos'=>emdo_ec_filter($pack_ids,array('bellota','iberico')),
 'pimientos_conserva'=>emdo_ec_filter($con_ids,array('pimiento'),array('mermelada','confitura')),
 'mermeladas'=>emdo_ec_filter($con_ids,array('mermelada','confitura')),
 'packs_12'=>emdo_ec_filter($con_ids,array('12 tarros')),
 'picantes'=>emdo_ec_filter($con_ids,array('picante','guindilla','hot sauce')),
);

$configs=array();
$configs[]=array('key'=>'chorizo-bellota','groups'=>array('embutidos'),'es_slug'=>'chorizo-bellota-100-iberico','en_slug'=>'100-iberian-acorn-fed-chorizo','es_title'=>'Chorizo de Bellota 100% Ibérico','en_title'=>'100% Iberian Acorn-Fed Chorizo','seo_title'=>'Comprar Chorizo de Bellota 100% Ibérico','es_meta'=>'Compra chorizo de bellota 100% ibérico de Hidalgo de la Jara. Compara pieza y formato loncheado en sobres.','en_meta'=>'Buy 100% Iberian acorn-fed chorizo from Hidalgo de la Jara. Compare whole-piece and sliced formats.','products'=>$groups['chorizo'],
'es_content'=>'<p>El <strong>chorizo de bellota 100% ibérico</strong> combina carne de cerdo ibérico, curación y el perfil especiado característico del chorizo. En esta selección puedes comparar el formato en pieza con la opción ya loncheada en sobres.</p>{{PRODUCTS}}<h2>Pieza o chorizo loncheado</h2><p>La pieza permite cortar el grosor al gusto y encaja bien cuando se consume de forma progresiva. Los sobres son más cómodos para servir cantidades pequeñas y mantener el resto cerrado.</p><h2>Qué revisar antes de comprar</h2><p>Compara formato, peso, conservación y número de sobres. Ambas referencias proceden de Hidalgo de la Jara y pertenecen a la gama de bellota 100% ibérica.</p><h2>Preguntas frecuentes</h2><h3>¿Hay chorizo ya cortado?</h3><p>Sí, el catálogo incluye una referencia loncheada a máquina en sobres.</p><h3>¿También se vende en pieza?</h3><p>Sí. Puedes elegir el formato tradicional en pieza según la disponibilidad de cada ficha.</p>{{PRODUCTS}}',
'en_content'=>'<p><strong>100% Iberian acorn-fed chorizo</strong> combines Iberian pork, curing and the characteristic seasoned profile of Spanish chorizo. Compare a whole-piece format with a ready-sliced option.</p>{{PRODUCTS}}<h2>Whole piece or sliced chorizo</h2><p>A whole piece lets you control slice thickness, while individual packs are convenient for smaller servings and portion control.</p><h2>What to compare</h2><p>Check format, weight, storage and pack quantity. Both products come from Hidalgo de la Jara.</p><h2>Frequently asked questions</h2><h3>Is sliced chorizo available?</h3><p>Yes, there is a machine-sliced format packed in individual portions.</p><h3>Can I buy a whole piece?</h3><p>Yes, subject to the current product availability.</p>{{PRODUCTS}}');
$configs[]=array('key'=>'salchichon-bellota','groups'=>array('embutidos'),'es_slug'=>'salchichon-bellota-100-iberico','en_slug'=>'100-iberian-acorn-fed-salchichon','es_title'=>'Salchichón de Bellota 100% Ibérico','en_title'=>'100% Iberian Acorn-Fed Salchichón','seo_title'=>'Comprar Salchichón de Bellota 100% Ibérico','es_meta'=>'Compra salchichón de bellota 100% ibérico de Hidalgo de la Jara. Elige entre pieza y sobres loncheados.','en_meta'=>'Buy 100% Iberian acorn-fed salchichón from Hidalgo de la Jara in whole-piece or sliced formats.','products'=>$groups['salchichon'],
'es_content'=>'<p>El <strong>salchichón de bellota 100% ibérico</strong> es un embutido curado de perfil especiado más suave que el chorizo. Aquí puedes comparar la pieza tradicional con el formato loncheado en sobres.</p>{{PRODUCTS}}<h2>Cómo elegir formato</h2><p>La pieza es adecuada si prefieres cortar al momento; los sobres facilitan servir raciones pequeñas sin abrir todo el producto.</p><h2>Para tablas, aperitivos y bocadillos</h2><p>Puede servirse solo o junto a lomo, chorizo, jamón y otros curados. La elección entre pieza y loncheado depende sobre todo de la frecuencia y cantidad de consumo.</p><h2>Preguntas frecuentes</h2><h3>¿Hay salchichón loncheado?</h3><p>Sí, existe una opción en sobres de 100 g.</p><h3>¿Quién lo produce?</h3><p>Las referencias de esta selección proceden de Hidalgo de la Jara.</p>{{PRODUCTS}}',
'en_content'=>'<p><strong>100% Iberian acorn-fed salchichón</strong> is a cured sausage with a gentler spice profile than chorizo. Compare a traditional whole piece with ready-sliced packs.</p>{{PRODUCTS}}<h2>Choosing the format</h2><p>Choose a whole piece for slicing to order, or individual packs for convenient small servings.</p><h2>For boards and appetisers</h2><p>Serve it alone or with loin, chorizo, ham and other cured products. Format mainly depends on how often and how much you plan to serve.</p><h2>Frequently asked questions</h2><h3>Is sliced salchichón available?</h3><p>Yes, there is a 100 g sliced-pack option.</p><h3>Who produces it?</h3><p>These products come from Hidalgo de la Jara.</p>{{PRODUCTS}}');
$configs[]=array('key'=>'lomo-lomito-bellota','groups'=>array('embutidos'),'es_slug'=>'lomo-lomito-bellota-100-iberico','en_slug'=>'100-iberian-acorn-fed-loin-and-lomito','es_title'=>'Lomo y Lomito de Bellota 100% Ibérico','en_title'=>'100% Iberian Acorn-Fed Loin and Lomito','seo_title'=>'Lomo y Lomito de Bellota 100% Ibérico | Comprar Online','es_meta'=>'Compara lomo, lomo loncheado y lomito de bellota 100% ibérico de Hidalgo de la Jara.','en_meta'=>'Compare 100% Iberian acorn-fed loin, sliced loin and lomito from Hidalgo de la Jara.','products'=>$groups['lomo'],
'es_content'=>'<p><strong>Lomo y lomito de bellota 100% ibérico</strong> no son exactamente la misma pieza. El lomo procede de la cinta de lomo, mientras que el lomito o caña de presa parte de la presa ibérica y ofrece una infiltración diferente.</p>{{PRODUCTS}}<h2>Lomo o lomito</h2><p>El lomo suele presentar una forma más regular y un corte magro con infiltración. El lomito es una pieza más pequeña vinculada a la presa y puede ofrecer una textura más untuosa.</p><h2>Pieza o loncheado</h2><p>Además de las piezas, el catálogo incluye lomo cortado a máquina en sobres para quien prioriza comodidad y raciones preparadas.</p><h2>Preguntas frecuentes</h2><h3>¿Lomo y lomito son lo mismo?</h3><p>No. Proceden de cortes distintos del cerdo ibérico.</p><h3>¿Hay lomo loncheado?</h3><p>Sí, existe una referencia preparada en sobres.</p>{{PRODUCTS}}',
'en_content'=>'<p><strong>100% Iberian acorn-fed loin and lomito</strong> come from different cuts. Loin is made from the loin muscle, while lomito is associated with presa and has a different fat distribution.</p>{{PRODUCTS}}<h2>Loin or lomito</h2><p>Loin is generally more regular and lean, while lomito is smaller and can feel richer because of its marbling.</p><h2>Whole or sliced</h2><p>The catalogue also includes machine-sliced loin in individual packs.</p><h2>Frequently asked questions</h2><h3>Are loin and lomito the same?</h3><p>No. They come from different Iberian pork cuts.</p><h3>Is sliced loin available?</h3><p>Yes, a pre-sliced pack format is available.</p>{{PRODUCTS}}');
$configs[]=array('key'=>'embutidos-loncheados','groups'=>array('embutidos'),'es_slug'=>'embutidos-ibericos-loncheados-bellota','en_slug'=>'sliced-iberian-acorn-fed-cured-meats','es_title'=>'Embutidos Ibéricos Loncheados de Bellota','en_title'=>'Sliced Iberian Acorn-Fed Cured Meats','seo_title'=>'Embutidos Ibéricos Loncheados | Chorizo, Salchichón y Lomo','es_meta'=>'Compra embutidos ibéricos loncheados de bellota: chorizo, salchichón y lomo en sobres preparados para servir.','en_meta'=>'Buy sliced Iberian acorn-fed cured meats: chorizo, salchichón and loin in ready-to-serve packs.','products'=>$groups['loncheados'],
'es_content'=>'<p>Los <strong>embutidos ibéricos loncheados</strong> permiten servir chorizo, salchichón y lomo sin tener que abrir y cortar una pieza completa. Esta selección reúne formatos de bellota 100% ibéricos preparados en sobres.</p>{{PRODUCTS}}<h2>Cuándo compensa el formato loncheado</h2><p>Es especialmente práctico para aperitivos, tablas pequeñas, viajes o hogares donde el consumo es más gradual.</p><h2>Qué incluye esta selección</h2><p>Puedes comparar chorizo, salchichón y lomo loncheados. Revisa cada ficha para confirmar número de sobres, peso total y conservación.</p><h2>Preguntas frecuentes</h2><h3>¿Los sobres vienen listos para servir?</h3><p>Sí, aunque conviene seguir las indicaciones de conservación y atemperado de la ficha concreta.</p><h3>¿Puedo combinar varios embutidos?</h3><p>Sí. Esta página está pensada precisamente para comparar los tres tipos.</p>{{PRODUCTS}}',
'en_content'=>'<p><strong>Sliced Iberian cured meats</strong> make it easy to serve chorizo, salchichón and loin without opening and cutting a whole piece. This selection brings together 100% Iberian acorn-fed sliced formats.</p>{{PRODUCTS}}<h2>When sliced packs are useful</h2><p>They work particularly well for appetisers, smaller boards, travel or households with gradual consumption.</p><h2>What is included</h2><p>Compare sliced chorizo, salchichón and loin. Check each product for pack count, total weight and storage instructions.</p><h2>Frequently asked questions</h2><h3>Are the packs ready to serve?</h3><p>Yes, while following the specific storage and serving guidance.</p><h3>Can I compare several cured meats?</h3><p>Yes. This page groups the three main sliced options.</p>{{PRODUCTS}}');
$configs[]=array('key'=>'surtidos-ibericos-bellota','groups'=>array('embutidos','packs'),'es_slug'=>'surtidos-packs-ibericos-bellota','en_slug'=>'iberian-acorn-fed-assortment-packs','es_title'=>'Surtidos y Packs Ibéricos de Bellota','en_title'=>'Iberian Acorn-Fed Assortment Packs','seo_title'=>'Surtidos y Packs Ibéricos de Bellota | Comprar Online','es_meta'=>'Compra surtidos ibéricos de bellota con lomo, chorizo, salchichón y opciones de cata con jamón y paleta.','en_meta'=>'Buy Iberian acorn-fed assortment packs with loin, chorizo, salchichón and tasting options including ham and shoulder.','products'=>$groups['surtidos'],
'es_content'=>'<p>Los <strong>surtidos y packs ibéricos de bellota</strong> agrupan varios curados en una sola compra. Son una alternativa práctica para preparar una tabla, probar distintas piezas o hacer un regalo sin elegir cada producto por separado.</p>{{PRODUCTS}}<h2>Surtido de embutidos o pack de cata</h2><p>El surtido se centra en lomo, salchichón y chorizo. El pack de cata amplía la selección con jamón y paleta, por lo que encaja mejor cuando se quiere comparar un abanico más amplio de ibéricos.</p><h2>Para regalo o para compartir</h2><p>Antes de elegir, compara los productos incluidos, formato, cantidad total y número de sobres o piezas.</p><h2>Preguntas frecuentes</h2><h3>¿Todos los packs incluyen jamón?</h3><p>No. El surtido de embutidos no es igual que el pack de cata; revisa la composición de cada ficha.</p><h3>¿Sirven como regalo?</h3><p>Sí, especialmente si buscas variedad en una única compra.</p>{{PRODUCTS}}',
'en_content'=>'<p><strong>Iberian acorn-fed assortment packs</strong> combine several cured products in one order. They work well for tasting boards, gifts or comparing different Iberian products.</p>{{PRODUCTS}}<h2>Cured-meat assortment or tasting pack</h2><p>The cured-meat assortment focuses on loin, salchichón and chorizo, while the tasting pack adds Iberian ham and shoulder.</p><h2>For gifting or sharing</h2><p>Compare the exact contents, total quantity and format before choosing.</p><h2>Frequently asked questions</h2><h3>Do all packs include ham?</h3><p>No. Check each product because the compositions are different.</p><h3>Are they suitable as gifts?</h3><p>Yes, especially when variety in a single purchase is useful.</p>{{PRODUCTS}}');
$configs[]=array('key'=>'pimientos-conserva','groups'=>array('conservas'),'es_slug'=>'pimientos-en-conserva-artesanos','en_slug'=>'artisan-preserved-peppers-spain','es_title'=>'Pimientos en Conserva Artesanos','en_title'=>'Artisan Preserved Peppers from Spain','seo_title'=>'Comprar Pimientos en Conserva Artesanos','es_meta'=>'Compra pimientos en conserva artesanos: asados, agridulces, fritos, picantes y en vinagre, en tarro individual o cajas.','en_meta'=>'Buy artisan preserved peppers from Spain: roasted, sweet-and-sour, fried, spicy and pickled formats.','products'=>$groups['pimientos_conserva'],
'es_content'=>'<p>Los <strong>pimientos en conserva artesanos</strong> permiten tener disponibles distintas elaboraciones sin depender de la temporada del producto fresco. En esta selección hay pimientos asados, fritos, agridulces, picantes y en vinagre.</p>{{PRODUCTS}}<h2>Asados, fritos o en vinagre</h2><p>Elige según el uso: los asados funcionan bien como guarnición o ensalada; los fritos pueden acompañar carnes y huevos; las opciones picantes y en vinagre aportan un perfil más intenso.</p><h2>Tarro individual o cajas</h2><p>Algunas referencias se ofrecen también en cajas de 12 tarros, pensadas para consumo frecuente o compras de mayor volumen.</p><h2>Preguntas frecuentes</h2><h3>¿Hay pimientos dulces y picantes?</h3><p>Sí. El catálogo incluye ambos perfiles.</p><h3>¿Se venden cajas completas?</h3><p>Sí, varias elaboraciones tienen formato de 12 tarros.</p>{{PRODUCTS}}',
'en_content'=>'<p><strong>Artisan preserved peppers</strong> make several pepper preparations available beyond the fresh season. Compare roasted, fried, sweet-and-sour, spicy and pickled options.</p>{{PRODUCTS}}<h2>Roasted, fried or pickled</h2><p>Choose by use: roasted peppers work as sides and salads, fried peppers pair well with savoury dishes, while spicy and pickled options add more intensity.</p><h2>Single jars or cases</h2><p>Several products are also sold as 12-jar cases for higher-volume purchases.</p><h2>Frequently asked questions</h2><h3>Are sweet and spicy peppers available?</h3><p>Yes, both styles are represented.</p><h3>Can I buy a full case?</h3><p>Yes, several products have 12-jar options.</p>{{PRODUCTS}}');
$configs[]=array('key'=>'mermeladas-verduras','groups'=>array('conservas'),'es_slug'=>'mermeladas-confituras-artesanas-verduras','en_slug'=>'artisan-vegetable-jams-and-confitures','es_title'=>'Mermeladas y Confituras Artesanas de Verduras','en_title'=>'Artisan Vegetable Jams and Confitures','seo_title'=>'Mermeladas y Confituras Artesanas de Verduras','es_meta'=>'Compra mermeladas y confituras artesanas de pimiento, tomate y puerro, en tarro individual o cajas de 12 unidades.','en_meta'=>'Buy artisan vegetable jams and confitures made with pepper, tomato and leek, in single jars or 12-jar cases.','products'=>$groups['mermeladas'],
'es_content'=>'<p>Las <strong>mermeladas y confituras artesanas de verduras</strong> ofrecen un uso distinto al de una conserva tradicional. En el catálogo puedes comparar elaboraciones de pimiento, tomate y puerro.</p>{{PRODUCTS}}<h2>Para quesos, carnes y aperitivos</h2><p>Su perfil dulce y vegetal permite utilizarlas en tablas de queso, tostadas, carnes, hamburguesas y aperitivos, ajustando la cantidad al resto de sabores.</p><h2>Formatos disponibles</h2><p>Además del tarro individual, algunas elaboraciones tienen formato de 12 unidades.</p><h2>Preguntas frecuentes</h2><h3>¿Qué sabores hay?</h3><p>Pimiento, tomate y puerro.</p><h3>¿Son lo mismo mermelada y conserva al natural?</h3><p>No. La elaboración y el uso culinario son diferentes.</p>{{PRODUCTS}}',
'en_content'=>'<p><strong>Artisan vegetable jams and confitures</strong> offer a different use from vegetables preserved in brine or oil. Compare pepper, tomato and leek preparations.</p>{{PRODUCTS}}<h2>For cheese, meat and appetisers</h2><p>The sweet-and-vegetal profile works with cheese boards, toast, meat, burgers and appetisers.</p><h2>Available formats</h2><p>Some products are available as both individual jars and 12-jar cases.</p><h2>Frequently asked questions</h2><h3>Which flavours are available?</h3><p>Pepper, tomato and leek.</p><h3>Is vegetable jam the same as a natural preserve?</h3><p>No. They use different preparations and suit different culinary uses.</p>{{PRODUCTS}}');
$configs[]=array('key'=>'conservas-12-tarros','groups'=>array('conservas'),'es_slug'=>'conservas-vegetales-packs-12-tarros','en_slug'=>'vegetable-preserves-12-jar-cases','es_title'=>'Conservas Vegetales en Packs de 12 Tarros','en_title'=>'Vegetable Preserves in 12-Jar Cases','seo_title'=>'Conservas Vegetales en Packs de 12 Tarros','es_meta'=>'Compra cajas de 12 tarros de conservas vegetales artesanas: pimientos, puerros, fritada y confituras de verduras.','en_meta'=>'Buy 12-jar cases of artisan vegetable preserves including peppers, leeks, tomato fritada and vegetable confitures.','products'=>$groups['packs_12'],
'es_content'=>'<p>Los <strong>packs de 12 tarros de conservas vegetales</strong> están pensados para quienes consumen una misma elaboración con frecuencia o prefieren comprar varias unidades de una vez.</p>{{PRODUCTS}}<h2>Qué productos se ofrecen en caja</h2><p>La selección incluye distintas preparaciones de pimiento, puerros, fritada de tomate y confituras de verduras, según la disponibilidad actual.</p><h2>Cuándo compensa comprar 12 unidades</h2><p>Antes de elegir, valora frecuencia de consumo, espacio de almacenamiento, fecha de consumo preferente y precio total frente al tarro individual.</p><h2>Preguntas frecuentes</h2><h3>¿Todos los productos tienen caja de 12?</h3><p>No. Solo aparecen aquí las referencias que disponen de ese formato.</p><h3>¿Son tarros iguales dentro de cada caja?</h3><p>Sí, cada referencia corresponde a una caja del mismo producto salvo que la ficha indique expresamente otra composición.</p>{{PRODUCTS}}',
'en_content'=>'<p><strong>12-jar cases of vegetable preserves</strong> are intended for frequent use or customers who prefer buying several units of the same preparation at once.</p>{{PRODUCTS}}<h2>Products available by the case</h2><p>The selection includes peppers, leeks, tomato fritada and vegetable confitures depending on current availability.</p><h2>When a 12-jar case makes sense</h2><p>Compare consumption frequency, storage space, best-before information and total price against individual jars.</p><h2>Frequently asked questions</h2><h3>Does every preserve have a 12-jar case?</h3><p>No. Only products currently sold in that format appear here.</p><h3>Are all jars in a case the same product?</h3><p>Yes, unless the individual product page explicitly states otherwise.</p>{{PRODUCTS}}');
$configs[]=array('key'=>'conservas-picantes','groups'=>array('conservas'),'es_slug'=>'conservas-picantes-encurtidos-artesanos','en_slug'=>'artisan-spicy-preserves-and-pickles','es_title'=>'Conservas Picantes y Encurtidos Artesanos','en_title'=>'Artisan Spicy Preserves and Pickles','seo_title'=>'Conservas Picantes y Encurtidos Artesanos','es_meta'=>'Compra conservas picantes y encurtidos artesanos: guindillas, pimientos picantes, pimiento verde en vinagre y salsa muy picante.','en_meta'=>'Buy artisan spicy preserves and pickles including chillies, spicy peppers, pickled green peppers and hot sauce.','products'=>$groups['picantes'],
'es_content'=>'<p>Las <strong>conservas picantes y encurtidos artesanos</strong> permiten añadir acidez, picor o ambos a aperitivos y platos sin tener que preparar cada elaboración desde cero.</p>{{PRODUCTS}}<h2>Guindillas, pimientos y salsa picante</h2><p>La selección reúne guindillas en vinagre, pimientos asados o verdes picantes y una salsa de mayor intensidad. No todos tienen el mismo nivel de picor.</p><h2>Cómo elegir</h2><p>Para acompañamiento directo suelen funcionar bien los encurtidos; para integrar en bocadillos, carnes o salsas puede resultar más práctico un pimiento preparado o una salsa picante.</p><h2>Preguntas frecuentes</h2><h3>¿Todo lo de esta página pica igual?</h3><p>No. La intensidad depende de cada elaboración.</p><h3>¿Hay opciones en vinagre?</h3><p>Sí, entre ellas guindillas y pimiento verde picante.</p>{{PRODUCTS}}',
'en_content'=>'<p><strong>Artisan spicy preserves and pickles</strong> add acidity, heat or both to appetisers and savoury dishes without preparing each item from scratch.</p>{{PRODUCTS}}<h2>Chillies, peppers and hot sauce</h2><p>The selection includes pickled chillies, spicy roasted or green peppers and a stronger hot sauce. Heat levels vary by product.</p><h2>How to choose</h2><p>Pickles work well as direct accompaniments, while prepared peppers and hot sauce are easy to add to sandwiches, meat and sauces.</p><h2>Frequently asked questions</h2><h3>Are all products equally hot?</h3><p>No. Heat level varies between preparations.</p><h3>Are pickled options available?</h3><p>Yes, including chillies and spicy green peppers.</p>{{PRODUCTS}}');

$created=array(); foreach($configs as $c){$p=emdo_ec_upsert($c); if($p)$created[]=$p;}
$by=array('embutidos'=>array(),'conservas'=>array(),'packs'=>array()); foreach($created as $p){foreach($p['groups'] as $g){if(isset($by[$g]))$by[$g][]=$p;}}
$alubia=emdo_ec_existing_page('comprar-alubias-secas-online','Comprar Alubias Secas Online','Buy Dried Beans Online from Spain','buy-dried-beans-online-spain');
$packs_carne=emdo_ec_existing_page('packs-lotes-carne','Packs y Lotes de Carne','Beef Boxes and Meat Packs','beef-boxes-and-meat-packs');

emdo_ec_category_block($leg,'Comprar legumbres online: alubias, garbanzos y lentejas','Aquí puedes comprar <strong>legumbres secas online</strong> directamente del productor: alubia blanca, canela y pinta, garbanzo pedrosillano y lenteja pardina. La categoría funciona como página principal para comparar las cinco referencias; solo creamos landings adicionales cuando existe variedad suficiente para que la página aporte algo distinto.','Buy dried pulses online: beans, chickpeas and lentils','Shop dried pulses from the producer, including white, canela and pinto beans, Pedrosillano chickpeas and Pardina lentils. This category is the main comparison page for all five products; additional landing pages are only used where the catalogue has enough depth.',array($alubia));
emdo_ec_category_block($emb,'Comprar embutidos ibéricos y curados','Compara <strong>embutidos ibéricos de bellota</strong> de Hidalgo de la Jara en pieza, loncheados y surtidos. La categoría reúne chorizo, salchichón, lomo, lomito, morcón, sobrasada y packs; las páginas específicas ayudan a elegir por tipo y formato sin duplicar la categoría principal.','Buy Iberian cured meats online','Compare acorn-fed Iberian cured meats from Hidalgo de la Jara as whole pieces, sliced packs and assortments. The category includes chorizo, salchichón, loin, lomito, morcón, sobrasada and mixed packs.', $by['embutidos']);
emdo_ec_category_block($con,'Comprar conservas vegetales artesanas online','Esta categoría reúne <strong>conservas vegetales artesanas</strong> en distintos formatos: pimientos, puerros, fritada de tomate, ajetes, guindillas, mermeladas, confituras y opciones picantes. Usa las selecciones específicas para comparar elaboraciones con un mismo uso o formato.','Buy artisan vegetable preserves online','This category brings together artisan vegetable preserves including peppers, leeks, tomato fritada, young garlic, chillies, vegetable jams, confitures and spicy options. Use the curated selections to compare products with the same purpose or format.', $by['conservas']);
$pack_links=$by['packs']; if($packs_carne)array_unshift($pack_links,$packs_carne);
emdo_ec_category_block($packs,'Packs y lotes para carne e ibéricos','La categoría de <strong>packs y lotes</strong> reúne dos familias diferentes: lotes de carne de Tolecarnes para familias, parejas o barbacoa, y surtidos ibéricos de bellota para cata, regalo o aperitivo. Separarlas en páginas específicas facilita comparar productos con una intención de compra más concreta.','Meat boxes and Iberian assortment packs','This category combines two different families: Tolecarnes meat boxes for families, couples and barbecues, plus Iberian acorn-fed assortments for tasting, gifting and appetisers.', $pack_links);

$verified=count($created)>=8; foreach($created as $p){if(get_post_status($p['id'])!=='publish'||count($p['products'])<2||(string)get_post_meta($p['id'],'_en_US_published',true)!=='1')$verified=false;}
echo wp_json_encode(array('verified'=>$verified,'count'=>count($created),'category_counts'=>array('legumbres'=>count($leg_ids),'embutidos'=>count($emb_ids),'conservas'=>count($con_ids),'packs'=>count($pack_ids)),'groups'=>array_map('array_values',$groups),'pages'=>$created,'category_urls'=>array('legumbres'=>get_term_link($leg),'embutidos'=>get_term_link($emb),'conservas'=>get_term_link($con),'packs'=>get_term_link($packs))),JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES).PHP_EOL;
