<?php
/**
 * Production deploy: curated Aceites + Carnes commercial SEO landings.
 * Spanish native pages + reviewed English aliases/content in _en_US_* metadata.
 * Idempotent by _emdo_ac_landing_key.
 */
if (!defined('ABSPATH')) { fwrite(STDERR, "WordPress is not loaded.\n"); exit(1); }

function emdo_ac_products_shortcode(array $ids): string {
    $ids = array_values(array_unique(array_filter(array_map('intval', $ids), static fn($id) => get_post_status($id) === 'publish')));
    if (!$ids) return '';
    return '[products ids="'.implode(',', $ids).'" columns="3" orderby="post__in"]';
}

function emdo_ac_aioseo(int $post_id, string $title, string $description): void {
    global $wpdb;
    $table = $wpdb->prefix . 'aioseo_posts';
    if ($wpdb->get_var($wpdb->prepare('SHOW TABLES LIKE %s', $table)) !== $table) return;
    $row_id = (int) $wpdb->get_var($wpdb->prepare("SELECT id FROM `{$table}` WHERE post_id=%d LIMIT 1", $post_id));
    if ($row_id) $wpdb->update($table, array('title'=>$title,'description'=>$description), array('id'=>$row_id), array('%s','%s'), array('%d'));
}

function emdo_ac_page_id(string $key): int {
    $ids = get_posts(array('post_type'=>'page','post_status'=>array('publish','draft','private'),'posts_per_page'=>2,'fields'=>'ids','no_found_rows'=>true,'meta_key'=>'_emdo_ac_landing_key','meta_value'=>$key));
    return $ids ? (int)$ids[0] : 0;
}

function emdo_ac_render(array $cfg, string $lang, string $products): string {
    $d = $cfg[$lang];
    $html = '';
    foreach ($d['intro'] as $p) $html .= '<p>'.$p.'</p>\n';
    $html .= $products."\n";
    foreach ($d['sections'] as $heading => $paragraphs) {
        $html .= '<h2>'.$heading.'</h2>\n';
        foreach ($paragraphs as $p) $html .= '<p>'.$p.'</p>\n';
    }
    if (!empty($d['bullets'])) {
        foreach ($d['bullets'] as $heading => $items) {
            $html .= '<h2>'.$heading.'</h2><ul>';
            foreach ($items as $item) $html .= '<li>'.$item.'</li>';
            $html .= '</ul>\n';
        }
    }
    $html .= '<h2>'.$d['faq_title'].'</h2>\n';
    foreach ($d['faq'] as $q => $a) $html .= '<h3>'.$q.'</h3><p>'.$a.'</p>\n';
    $html .= $products."\n";
    return $html;
}

function emdo_ac_upsert(array $cfg): array {
    $products = emdo_ac_products_shortcode($cfg['products']);
    if ($products === '') throw new Exception('No live products for '.$cfg['key']);
    $id = emdo_ac_page_id($cfg['key']);
    if (!$id) {
        $existing = get_page_by_path($cfg['es_slug'], OBJECT, 'page');
        if ($existing instanceof WP_Post) $id = (int)$existing->ID;
    }
    $es_content = emdo_ac_render($cfg, 'es', $products);
    $en_content = emdo_ac_render($cfg, 'en', $products);
    $args = array('post_type'=>'page','post_status'=>'publish','post_title'=>$cfg['es_title'],'post_name'=>$cfg['es_slug'],'post_content'=>$es_content,'post_excerpt'=>$cfg['es_meta'],'comment_status'=>'closed','ping_status'=>'closed');
    if ($id) $args['ID'] = $id;
    $saved = wp_insert_post(wp_slash($args), true);
    if (is_wp_error($saved)) throw new Exception($saved->get_error_message());
    $id = (int)$saved;
    update_post_meta($id, '_emdo_ac_landing_key', $cfg['key']);
    update_post_meta($id, '_en_US_post_title', '<span data-no-translation>'.$cfg['en_title'].'</span>');
    update_post_meta($id, '_en_US_post_name', $cfg['en_slug']);
    update_post_meta($id, '_en_US_post_excerpt', $cfg['en_meta']);
    update_post_meta($id, '_en_US_post_content', '<span data-no-translation>'.$en_content.'</span>');
    update_post_meta($id, '_en_US_published', '1');
    emdo_ac_aioseo($id, $cfg['seo_title'], $cfg['es_meta']);
    return array('key'=>$cfg['key'],'group'=>$cfg['group'],'id'=>$id,'es_url'=>home_url('/'.$cfg['es_slug'].'/'),'en_url'=>home_url('/en/'.$cfg['en_slug'].'/'),'products'=>array_values(array_filter(array_map('intval',$cfg['products']), static fn($pid)=>get_post_status($pid)==='publish')));
}

function emdo_ac_link_category(string $slug, array $pages): void {
    $term = get_term_by('slug', $slug, 'product_cat');
    if (!$term || is_wp_error($term)) throw new Exception('Missing product category '.$slug);
    $start='<!-- emdo-ac-landings-start -->'; $end='<!-- emdo-ac-landings-end -->';
    $pattern='/\\s*'.preg_quote($start,'/').'.*?'.preg_quote($end,'/').'\\s*/s';
    $es=(string)$term->description; $es=preg_replace($pattern,"\n",$es);
    $en=(string)get_term_meta((int)$term->term_id,'_en_US_description',true); if($en!=='') $en=preg_replace($pattern,"\n",$en);
    $es_links=array(); $en_links=array();
    foreach($pages as $p){
        $es_links[]='<a href="'.esc_url($p['es_url']).'">'.esc_html($p['es_title']).'</a>';
        $en_links[]='<a href="'.esc_url($p['en_url']).'">'.esc_html($p['en_title']).'</a>';
    }
    $es_block=$start.'<div class="emdo-seo-landings"><p><strong>Explora también:</strong> '.implode(' · ',$es_links).'</p></div>'.$end;
    $r=wp_update_term((int)$term->term_id,'product_cat',array('description'=>trim($es)."\n\n".$es_block));
    if(is_wp_error($r)) throw new Exception($r->get_error_message());
    if($en!==''){
        $en_block=$start.'<div class="emdo-seo-landings"><p><strong>Explore also:</strong> '.implode(' · ',$en_links).'</p></div>'.$end;
        update_term_meta((int)$term->term_id,'_en_US_description',trim($en)."\n\n".$en_block);
    }
}

$pages = array(
array(
'key'=>'aove-cordoba-almazara','group'=>'aceites','es_slug'=>'aove-cordoba-directo-almazara','en_slug'=>'cordoba-extra-virgin-olive-oil-direct-from-mill','es_title'=>'AOVE de Córdoba Directo de Almazara','en_title'=>'Córdoba Extra Virgin Olive Oil Direct from the Mill','seo_title'=>'AOVE de Córdoba Directo de Almazara | El Mercado de Origen','es_meta'=>'Compra AOVE de Córdoba directamente de una almazara familiar. Compara formatos y variedades de 1957, con aceite elaborado y envasado en origen.','en_meta'=>'Buy Córdoba extra virgin olive oil direct from a family olive mill. Compare formats and varieties from producer 1957.',
'products'=>array(1056,1599,1590),
'es'=>array('intro'=>array('Comprar <strong>AOVE de Córdoba directamente de almazara</strong> permite elegir el aceite conociendo quién lo elabora, de dónde procede y en qué formatos está disponible. En El Mercado de Origen trabajamos con 1957, una familia vinculada al olivar y a la elaboración de aceite durante tres generaciones.','Sus aceites se elaboran en Córdoba y se obtienen mediante procedimientos mecánicos, con extracción en frío. La gama permite elegir distintos formatos y variedades según el uso y la intensidad de sabor que se busque.'),'sections'=>array('AOVE con origen y productor identificados'=>array('El origen no sustituye a la categoría del aceite, pero aporta contexto. Saber qué almazara está detrás permite conocer el proceso, las variedades y la forma de trabajar antes de comprar.','1957 mantiene el vínculo entre olivar, almazara y envasado y dispone de AOVE en formatos pensados tanto para consumo habitual como para hogares que prefieren comprar varias unidades.'),'Qué formato elegir'=>array('La elección depende del consumo. El formato de 5 litros resulta práctico cuando el AOVE se utiliza a diario en cocina; los formatos de 500 ml y 1 litro facilitan el manejo, el reparto entre varias botellas y un consumo más gradual.','Conviene comparar el precio total, los litros incluidos y la frecuencia con la que se utiliza aceite en casa, en lugar de fijarse únicamente en el tamaño del envase.'),'Arbequina, Picual y otras opciones'=>array('Dentro de los productos disponibles pueden seleccionarse variedades como Arbequina o Marteña, nombre con el que el productor comercializa su Picual, además de otras opciones según el formato.','La variedad influye especialmente en el perfil aromático y en la intensidad. Una Arbequina suele resultar más suave, mientras que un Picual ofrece normalmente mayor carácter.')),'bullets'=>array('Qué revisar antes de comprar AOVE online'=>array('Categoría: aceite de oliva virgen extra.','Origen y productor.','Variedad de aceituna.','Formato y litros totales.','Tipo de elaboración y conservación.')),'faq_title'=>'Preguntas frecuentes','faq'=>array('¿El AOVE de 1957 procede de Córdoba?'=>'Sí. El productor trabaja con aceite vinculado a su olivar y almazara en Córdoba.','¿Se puede comprar en formatos grandes?'=>'Sí. La gama incluye formatos de 5 litros y packs de varias botellas.','¿Qué variedad elegir?'=>'Depende del perfil buscado: Arbequina suele ser más suave y Picual o Marteña presenta normalmente mayor intensidad.')),
'en'=>array('intro'=>array('Buying <strong>Córdoba extra virgin olive oil direct from the mill</strong> makes it possible to choose oil while knowing who produces it, where it comes from and which formats are available. El Mercado de Origen works with 1957, a family connected with olive growing and oil production across three generations.','Their oils are produced in Córdoba using mechanical methods and cold extraction. The range includes several pack sizes and olive varieties for different cooking and tasting preferences.'),'sections'=>array('EVOO with a visible producer and origin'=>array('Origin does not replace the legal olive-oil category, but it provides useful context. Knowing the mill behind the oil helps you understand its varieties, production approach and available formats before buying.','1957 maintains a direct link between olive grove, mill and bottling, with formats suited to regular household use and multi-bottle purchases.'),'Choosing the right format'=>array('A 5-litre format is practical for frequent everyday cooking, while 500 ml and 1-litre bottles are easier to handle and allow the total quantity to be divided across several containers.','Compare total litres, pack size and your normal consumption rather than looking only at the individual container.'),'Arbequina, Picual and other options'=>array('Available products include Arbequina and Marteña, the producer’s name for its Picual option, together with other selections depending on the format.','Arbequina is generally milder and more delicate, while Picual usually offers a more assertive flavour profile.')),'bullets'=>array('What to check before buying EVOO online'=>array('Extra virgin olive oil category.','Producer and origin.','Olive variety.','Pack size and total litres.','Production and storage information.')),'faq_title'=>'Frequently asked questions','faq'=>array('Is 1957 EVOO produced in Córdoba?'=>'Yes. The producer is linked to olive groves and a mill in Córdoba, Spain.','Can I buy larger formats?'=>'Yes. The range includes 5-litre formats and multi-bottle packs.','Which variety should I choose?'=>'Arbequina is usually milder, while Picual or Marteña normally has a stronger profile.'))
),
array(
'key'=>'aove-arbequina','group'=>'aceites','es_slug'=>'aove-arbequina','en_slug'=>'arbequina-extra-virgin-olive-oil','es_title'=>'AOVE Arbequina','en_title'=>'Arbequina Extra Virgin Olive Oil','seo_title'=>'Comprar AOVE Arbequina | Aceite de Oliva Virgen Extra','es_meta'=>'Compra AOVE Arbequina directo de almazara. Compara formatos de 1957 y elige una variedad suave y aromática para cocina y consumo en crudo.','en_meta'=>'Buy Arbequina extra virgin olive oil direct from the mill. Compare 1957 formats for a mild, aromatic EVOO.',
'products'=>array(1056,1599,1590),
'es'=>array('intro'=>array('El <strong>AOVE Arbequina</strong> es una opción especialmente apreciada por quienes buscan un aceite de oliva virgen extra de perfil suave, aromático y fácil de integrar en numerosos platos.','En los productos de 1957 puedes seleccionar Arbequina en distintos formatos, desde envases grandes para consumo frecuente hasta packs de botellas más manejables.'),'sections'=>array('Cómo es un AOVE Arbequina'=>array('La variedad Arbequina suele ofrecer un perfil más delicado que variedades de mayor intensidad. Esto la hace versátil para tostadas, ensaladas, salsas, repostería y elaboraciones en las que se quiere aportar aceite sin dominar el resto de sabores.','Como en cualquier AOVE, el carácter concreto cambia con la cosecha, el estado del fruto y la elaboración, por lo que la variedad orienta pero no sustituye a la información del productor.'),'Arbequina para cocinar o para tomar en crudo'=>array('No es necesario reservar el AOVE Arbequina únicamente para aliñar. Puede utilizarse también para cocinar, aunque su suavidad hace que destaque especialmente en usos en crudo y recetas donde interesa un perfil menos intenso.','Para un consumo diario elevado puede resultar conveniente un formato grande; si se utiliza de forma más puntual, los envases pequeños facilitan el manejo.'),'Directo de la almazara 1957'=>array('1957 elabora sus AOVEs en Córdoba y mantiene un proceso de extracción en frío. Al comprar a través de El Mercado de Origen puedes identificar al productor y escoger el formato y la variedad dentro de cada ficha.')),'bullets'=>array('Cuándo elegir Arbequina'=>array('Si prefieres sabores suaves.','Para tostadas y desayunos.','Para ensaladas y salsas.','Para repostería con aceite de oliva.','Cuando quieres un AOVE versátil para toda la casa.')),'faq_title'=>'Preguntas frecuentes','faq'=>array('¿Arbequina significa que sea mejor que Picual?'=>'No. Son variedades con perfiles diferentes; la elección depende del gusto y del uso.','¿Puedo cocinar con AOVE Arbequina?'=>'Sí. Puede utilizarse tanto en crudo como en cocina.','¿Hay varios formatos?'=>'Sí. Los productos disponibles permiten elegir Arbequina en distintos tamaños y packs.')),
'en'=>array('intro'=>array('<strong>Arbequina extra virgin olive oil</strong> is a popular choice for people looking for a mild, aromatic EVOO that works easily across many dishes.','1957 offers Arbequina as a selectable variety in several formats, from larger containers for frequent use to smaller multi-bottle packs.'),'sections'=>array('What Arbequina EVOO tastes like'=>array('Arbequina generally has a more delicate profile than stronger olive varieties. It works well on toast, salads, sauces, baking and dishes where the oil should complement rather than dominate other flavours.','The exact profile still changes with harvest and production, so variety is a useful guide rather than a complete description of every oil.'),'Arbequina for cooking and raw use'=>array('Arbequina EVOO does not need to be kept only for dressings. It can also be used for cooking, while its mild style makes it particularly attractive for raw uses and recipes that benefit from a softer olive-oil character.','Larger formats suit frequent use; smaller bottles may be easier for occasional consumption.'),'Direct from 1957 olive mill'=>array('1957 produces its EVOOs in Córdoba using cold extraction. Through El Mercado de Origen you can identify the producer and select the desired format and variety on each product page.')),'bullets'=>array('When Arbequina is a good choice'=>array('If you prefer milder flavours.','For toast and breakfast.','For salads and sauces.','For baking with olive oil.','For a versatile everyday EVOO.')),'faq_title'=>'Frequently asked questions','faq'=>array('Is Arbequina better than Picual?'=>'No. They are different varieties with different flavour profiles.','Can Arbequina EVOO be used for cooking?'=>'Yes. It works for both raw and cooked uses.','Are different formats available?'=>'Yes. Arbequina can be selected across several available 1957 formats.'))
),
array(
'key'=>'aove-picual','group'=>'aceites','es_slug'=>'aove-picual','en_slug'=>'picual-extra-virgin-olive-oil','es_title'=>'AOVE Picual','en_title'=>'Picual Extra Virgin Olive Oil','seo_title'=>'Comprar AOVE Picual | Aceite de Oliva Virgen Extra','es_meta'=>'Compra AOVE Picual, comercializado por 1957 como variedad Marteña. Compara formatos y elige un aceite con mayor intensidad y personalidad.','en_meta'=>'Buy Picual extra virgin olive oil, offered by 1957 as Marteña. Compare formats for a more intense, distinctive EVOO.',
'products'=>array(1056,1599,1590),
'es'=>array('intro'=>array('El <strong>AOVE Picual</strong> es una de las variedades más reconocibles del aceite de oliva español. En la gama de 1957 aparece también bajo la denominación <strong>Marteña</strong>, utilizada por el productor para esta variedad.','Es una alternativa adecuada para quien busca un aceite con más personalidad que una Arbequina y quiere disponer de distintos formatos para consumo habitual.'),'sections'=>array('Perfil del aceite Picual'=>array('El Picual suele presentar un carácter más marcado, con sensaciones verdes, amargas o picantes que pueden variar en intensidad según la campaña y la elaboración.','Ese perfil permite utilizarlo tanto en crudo como en cocina, especialmente cuando interesa que el aceite tenga presencia propia en el plato.'),'Picual o Arbequina'=>array('No se trata de decidir cuál es mejor, sino cuál encaja mejor con el gusto y la receta. Arbequina suele ser más suave; Picual suele resultar más intenso y estructurado.','Tener ambas variedades en casa también permite elegir una u otra según el uso, en lugar de buscar un único aceite para todo.'),'Formatos disponibles de 1957'=>array('La variedad Marteña o Picual puede seleccionarse en diferentes productos de 1957. Esto permite adaptar la compra al consumo, desde formatos grandes hasta packs de botellas de 500 ml o 1 litro.')),'bullets'=>array('Usos habituales del AOVE Picual'=>array('Carnes y pescados.','Verduras asadas.','Tostadas con un aceite de sabor intenso.','Guisos y cocina diaria.','Aliños donde se quiere notar el aceite.')),'faq_title'=>'Preguntas frecuentes','faq'=>array('¿Marteña y Picual son lo mismo en estos productos?'=>'Sí. 1957 utiliza Marteña para identificar su opción Picual.','¿Es más fuerte que Arbequina?'=>'Habitualmente el Picual presenta un perfil más intenso, aunque el resultado exacto depende de cada aceite.','¿Se puede comprar en 5 litros?'=>'Sí. La gama incluye un producto de AOVE de 5 litros con opción Picual o Marteña.')),
'en'=>array('intro'=>array('<strong>Picual extra virgin olive oil</strong> is one of Spain’s most recognisable olive varieties. In the 1957 range it is also presented as <strong>Marteña</strong>, the name used by the producer for this option.','It is well suited to customers who want a more assertive olive-oil profile than Arbequina and need a choice of formats for regular use.'),'sections'=>array('Picual flavour profile'=>array('Picual commonly has a more pronounced character, with green, bitter or peppery notes whose intensity changes with harvest and production.','This makes it useful both raw and in cooking, especially when the olive oil should remain noticeable in the finished dish.'),'Picual or Arbequina'=>array('The choice is not about one being universally better. Arbequina is generally milder, while Picual tends to be more structured and intense.','Keeping both varieties also lets you match the oil to the dish instead of relying on one flavour profile for every use.'),'Available 1957 formats'=>array('Marteña or Picual can be selected across several 1957 products, from large household formats to packs of 500 ml or 1-litre bottles.')),'bullets'=>array('Common uses for Picual EVOO'=>array('Meat and fish.','Roasted vegetables.','Toast with a pronounced olive-oil flavour.','Stews and everyday cooking.','Dressings where the oil should stand out.')),'faq_title'=>'Frequently asked questions','faq'=>array('Are Marteña and Picual the same option here?'=>'Yes. 1957 uses Marteña to identify its Picual variety.','Is it stronger than Arbequina?'=>'Picual generally has a more intense profile, although each oil can vary.','Is a 5-litre format available?'=>'Yes. The 5-litre EVOO product includes a Picual or Marteña option.'))
),
array(
'key'=>'carne-ternera-online','group'=>'carnes','es_slug'=>'carne-ternera-online','en_slug'=>'buy-fresh-beef-online','es_title'=>'Carne de Ternera Online','en_title'=>'Buy Fresh Beef Online','seo_title'=>'Comprar Carne de Ternera Online | Cortes y Packs','es_meta'=>'Compra carne de ternera online: filetes, solomillo, morcillo, osobuco, churrasco, picaña y otros cortes preparados por Tolecarnes.','en_meta'=>'Buy fresh beef online from Tolecarnes. Compare steaks, tenderloin, shin, osso buco, picanha, ribs and other cuts.',
'products'=>array(11087,11077,11064,11073,11090,11105,11092,11163,11134,11154,11103,11123),
'es'=>array('intro'=>array('Comprar <strong>carne de ternera online</strong> tiene sentido cuando puedes elegir el corte con la misma precisión que en una carnicería. En esta selección reunimos distintos cortes de Tolecarnes para plancha, guiso, horno y barbacoa.','No todos los cortes sirven para lo mismo. Por eso esta página está pensada para comparar usos y elegir la pieza en función de la receta, en lugar de tratar toda la carne de ternera como una única categoría.'),'sections'=>array('Cortes para plancha y cocina rápida'=>array('Solomillo, entrecot y determinados filetes están pensados para cocciones rápidas. Aquí importan el grosor, la temperatura de la carne y el punto de cocción más que una cocción prolongada.','Para este tipo de preparaciones conviene seleccionar piezas que puedan cocinarse en pocos minutos sin perder jugosidad.'),'Ternera para guisos y cocciones lentas'=>array('Morcillo, osobuco, ragú y otros cortes ricos en tejido conjuntivo se benefician de tiempos más largos. Con temperatura moderada y suficiente humedad desarrollan una textura distinta a la de los cortes de plancha.','Elegir un corte específico para guisar suele dar mejor resultado que utilizar una pieza tierna pensada para cocción rápida.'),'Cortes para horno y barbacoa'=>array('Picaña, churrasco, tomahawk, roast beef o vacío permiten plantear preparaciones de mayor tamaño, asados y barbacoas. Cada corte necesita un enfoque diferente en grosor, temperatura y reposo.')),'bullets'=>array('Cómo elegir tu carne de ternera'=>array('Plancha: filetes, solomillo y entrecot.','Guiso: morcillo, osobuco y ragú.','Horno: roast beef, redondo y piezas para asar.','Barbacoa: churrasco, picaña, tomahawk y vacío.')),'faq_title'=>'Preguntas frecuentes','faq'=>array('¿Qué corte es mejor para plancha?'=>'Depende del presupuesto y del grosor, pero solomillo, entrecot y filetes son opciones habituales.','¿Qué carne elegir para guisar?'=>'Morcillo, osobuco y ragú son cortes especialmente adecuados para cocciones largas.','¿Quién prepara estos productos?'=>'La selección de carne procede de Tolecarnes, productor visible en cada ficha.')),
'en'=>array('intro'=>array('Buying <strong>fresh beef online</strong> works best when you can choose the cut as precisely as you would at a butcher’s counter. This selection brings together Tolecarnes cuts for pan cooking, stews, roasting and barbecues.','Different cuts suit different cooking methods, so the page is organised around how you plan to use the meat rather than treating all beef as one product.'),'sections'=>array('Cuts for quick pan cooking'=>array('Tenderloin, entrecôte and selected steaks are suited to fast cooking. Thickness, pan temperature and final doneness matter more than long cooking times.','Choose these cuts when you want a tender result from a short cooking process.'),'Beef for stews and slow cooking'=>array('Shin, osso buco, diced beef and similar cuts benefit from longer cooking. Moderate heat and moisture help transform their texture over time.','Choosing a cut designed for stewing usually makes more sense than using a premium quick-cooking steak.'),'Cuts for roasting and barbecue'=>array('Picanha, ribs, tomahawk, roasting joints and flank cuts offer options for larger preparations and outdoor cooking. Each cut requires its own approach to thickness, heat and resting.')),'bullets'=>array('How to choose your beef'=>array('Pan: steaks, tenderloin and entrecôte.','Stews: shin, osso buco and diced beef.','Oven: roasting joints and round cuts.','Barbecue: ribs, picanha, tomahawk and flank.')),'faq_title'=>'Frequently asked questions','faq'=>array('Which cut is best for pan cooking?'=>'Tenderloin, entrecôte and steaks are common choices, depending on budget and thickness.','Which beef is good for stews?'=>'Shin, osso buco and diced beef are particularly suitable for slow cooking.','Who prepares these products?'=>'The meat selection comes from Tolecarnes, shown as the producer on each product page.'))
),
array(
'key'=>'carne-vaca-madurada','group'=>'carnes','es_slug'=>'carne-vaca-madurada','en_slug'=>'dry-aged-mature-beef','es_title'=>'Carne de Vaca Madurada','en_title'=>'Dry-Aged Mature Beef','seo_title'=>'Comprar Carne de Vaca Madurada | Cortes Seleccionados','es_meta'=>'Compra carne de vaca madurada: chuletón, entrecot, solomillo, carne a la piedra y hamburguesas de vaca de Tolecarnes.','en_meta'=>'Buy dry-aged mature beef from Tolecarnes: rib steak, entrecôte, tenderloin, hot-stone strips and mature beef burgers.',
'products'=>array(11082,11107,11099,11125,11166),
'es'=>array('intro'=>array('La <strong>carne de vaca madurada</strong> se busca por un perfil diferente al de una ternera joven: mayor intensidad de sabor y cortes pensados para disfrutar especialmente a la plancha, parrilla o piedra.','En esta selección puedes comparar chuletón, entrecot, solomillo, carne preparada para piedra y hamburguesas de vaca.'),'sections'=>array('Qué aporta la maduración'=>array('La maduración controlada modifica la carne con el paso del tiempo y puede concentrar aromas y favorecer una textura determinada. No todos los cortes se comportan igual, por lo que conviene valorar también grosor, infiltración y preparación.','El término “madurada” no sustituye a la información de cada ficha: el producto concreto sigue siendo lo que debe guiar la elección.'),'Chuletón, entrecot o solomillo'=>array('El chuletón es una pieza de gran formato apropiada para compartir o para una cocción controlada. El entrecot ofrece una ración más manejable y el solomillo destaca por su terneza.','Quien prioriza intensidad puede inclinarse por cortes con mayor grasa e infiltración; quien busca una textura muy tierna puede preferir solomillo.'),'Cómo cocinar carne madurada'=>array('Una superficie bien caliente ayuda a desarrollar el exterior, mientras que controlar el tiempo evita sobrecocinar el interior. En piezas gruesas resulta especialmente importante dejar reposar la carne antes de cortarla.')),'bullets'=>array('Opciones disponibles'=>array('Chuletón de vaca vieja madurado.','Entrecot de vaca.','Solomillo de vaca.','Carne a la piedra de vaca madurada.','Hamburguesas 100% vaca.')),'faq_title'=>'Preguntas frecuentes','faq'=>array('¿Vaca madurada y ternera son lo mismo?'=>'No. Son categorías y edades distintas, con perfiles de sabor y textura diferentes.','¿Qué corte elegir para compartir?'=>'Un chuletón de mayor tamaño suele encajar bien en una comida para compartir.','¿Se puede hacer a la piedra?'=>'Sí. Hay un producto específicamente preparado para cocinar carne de vaca madurada a la piedra.')),
'en'=>array('intro'=>array('<strong>Dry-aged mature beef</strong> is chosen for a different profile from younger beef: stronger flavour and cuts designed particularly for grilling, pan cooking or hot-stone preparation.','This selection includes mature rib steak, entrecôte, tenderloin, hot-stone strips and burgers.'),'sections'=>array('What ageing changes'=>array('Controlled ageing changes the meat over time and can concentrate flavour while influencing texture. Each cut still behaves differently, so thickness, marbling and preparation remain important.','The word “aged” should not replace the information on the individual product page when making a final choice.'),'Rib steak, entrecôte or tenderloin'=>array('A large rib steak works well for sharing or carefully controlled cooking. Entrecôte offers a more manageable portion, while tenderloin is chosen mainly for tenderness.','Customers prioritising intensity may prefer cuts with more fat and marbling; those prioritising tenderness may prefer tenderloin.'),'Cooking mature beef'=>array('A properly heated cooking surface helps develop the exterior, while careful timing prevents overcooking the centre. Thick steaks benefit especially from resting before slicing.')),'bullets'=>array('Available options'=>array('Dry-aged mature beef rib steak.','Mature beef entrecôte.','Mature beef tenderloin.','Dry-aged strips for hot-stone cooking.','100% mature beef burgers.')),'faq_title'=>'Frequently asked questions','faq'=>array('Is mature beef the same as young beef?'=>'No. Age and production category differ, producing different flavour and texture profiles.','Which cut is suitable for sharing?'=>'A large rib steak is often a good option for a shared meal.','Can it be cooked on a hot stone?'=>'Yes. A product is specifically prepared as dry-aged beef strips for hot-stone cooking.'))
),
array(
'key'=>'carne-barbacoa','group'=>'carnes','es_slug'=>'carne-para-barbacoa','en_slug'=>'meat-for-barbecue','es_title'=>'Carne para Barbacoa','en_title'=>'Meat for Barbecue','seo_title'=>'Comprar Carne para Barbacoa | Cortes y Lotes','es_meta'=>'Compra carne para barbacoa: tomahawk, churrasco, picaña, entraña, vacío y lotes preparados por Tolecarnes.','en_meta'=>'Buy meat for barbecue from Tolecarnes: tomahawk, ribs, picanha, skirt steak, flank and barbecue boxes.',
'products'=>array(11139,11134,11145,11120,11092,11075,11163,11123,11156),
'es'=>array('intro'=>array('Una buena <strong>selección de carne para barbacoa</strong> no consiste en comprar muchos cortes iguales, sino en combinar piezas con diferentes grosores, tiempos de cocción y formas de servir.','Aquí reunimos cortes de Tolecarnes que encajan especialmente bien en parrilla: tomahawk, churrasco, picaña, entraña, vacío y lotes ya preparados.'),'sections'=>array('Cortes rápidos y cortes gruesos'=>array('Entraña, churrasco o determinados filetes pueden cocinarse con rapidez a fuego fuerte. Un tomahawk o una pieza de mayor grosor necesita más control para conseguir un exterior marcado sin pasar el centro.','Combinar ambos tipos permite servir carne en distintos momentos y adaptarse a diferentes puntos de cocción.'),'Picaña, vacío y cortes para compartir'=>array('La picaña y el vacío son cortes populares para parrilla porque permiten cocinar piezas de tamaño medio y después cortar en porciones. La dirección del corte final influye mucho en la sensación de ternura.','También pueden combinarse con piezas pequeñas o hamburguesas para ampliar la variedad de la barbacoa.'),'Lotes preparados'=>array('Si no quieres elegir cada corte por separado, el lote barbacoa agrupa varias opciones en una única compra. Para ocasiones concretas también hay packs que combinan tomahawk con otros productos.')),'bullets'=>array('Antes de encender la parrilla'=>array('Agrupa cortes por grosor.','Empieza por las piezas que necesitan más tiempo.','No pinches constantemente la carne.','Deja reposar los cortes gruesos antes de servir.','Corta piezas como picaña o vacío en la dirección adecuada.')),'faq_title'=>'Preguntas frecuentes','faq'=>array('¿Qué carne comprar para una barbacoa variada?'=>'Una combinación de churrasco, entraña o vacío con una pieza gruesa como tomahawk ofrece distintas texturas y tiempos de cocción.','¿Hay lotes ya preparados?'=>'Sí. Tolecarnes dispone de un lote barbacoa y otros packs relacionados.','¿Picaña y vacío sirven para parrilla?'=>'Sí. Son cortes especialmente populares para este tipo de cocción.')),
'en'=>array('intro'=>array('A good <strong>barbecue meat selection</strong> is not about buying many identical steaks. It is about combining cuts with different thicknesses, cooking times and serving styles.','This Tolecarnes selection includes tomahawk, ribs, picanha, skirt steak, flank and ready-made barbecue boxes.'),'sections'=>array('Fast-cooking and thick cuts'=>array('Skirt steak, ribs and thinner cuts can cook quickly over strong heat. A tomahawk or other thick steak needs more control to brown the outside without overcooking the centre.','Combining both types makes it easier to serve meat in stages and offer different levels of doneness.'),'Picanha, flank and sharing cuts'=>array('Picanha and flank cuts work well on a grill because they can be cooked as medium-sized pieces and sliced for serving. Cutting direction matters greatly to perceived tenderness.','They can also be combined with smaller steaks or burgers for a broader barbecue spread.'),'Ready-made boxes'=>array('If you prefer not to select every cut separately, the barbecue box groups several options into one purchase. Other packs combine tomahawk with complementary products.')),'bullets'=>array('Before you light the grill'=>array('Group cuts by thickness.','Start cuts that need the longest cooking first.','Avoid repeatedly piercing the meat.','Rest thick steaks before serving.','Slice picanha and flank correctly across the grain.')),'faq_title'=>'Frequently asked questions','faq'=>array('What should I buy for a varied barbecue?'=>'Combine quick cuts such as ribs or skirt steak with a thicker centrepiece such as tomahawk.','Are ready-made barbecue boxes available?'=>'Yes. Tolecarnes offers a barbecue box and related packs.','Are picanha and flank good for grilling?'=>'Yes. Both are popular barbecue cuts.'))
),
array(
'key'=>'packs-carne','group'=>'carnes','es_slug'=>'packs-lotes-carne','en_slug'=>'beef-boxes-and-meat-packs','es_title'=>'Packs y Lotes de Carne','en_title'=>'Beef Boxes and Meat Packs','seo_title'=>'Packs y Lotes de Carne Online | Barbacoa y Familiar','es_meta'=>'Compra packs y lotes de carne de Tolecarnes: lote familiar, barbacoa, parejas, filetes y magro o tomahawk con vino.','en_meta'=>'Buy Tolecarnes beef boxes and meat packs for families, couples, barbecues and mixed steak selections.',
'products'=>array(11112,11139,11131,11159,11156),
'es'=>array('intro'=>array('Los <strong>packs y lotes de carne</strong> permiten resolver varias comidas con una sola compra y suelen ser más cómodos que seleccionar cada corte individualmente.','Tolecarnes dispone de lotes orientados a familias, parejas, barbacoas y combinaciones de filetes, magro o tomahawk.'),'sections'=>array('Lote familiar o lote para parejas'=>array('La diferencia principal está en la cantidad y en cómo se reparte entre distintos cortes. Un lote familiar prioriza volumen y variedad para varias comidas; uno pensado para parejas busca cantidades más contenidas.','Antes de elegir conviene revisar qué piezas incluye cada pack y pensar si se van a consumir inmediatamente o se van a repartir y congelar.'),'Packs para barbacoa'=>array('Los packs de barbacoa concentran cortes adecuados para parrilla y evitan tener que calcular cada pieza por separado. Son especialmente útiles cuando el número de comensales y el tipo de comida están claros.','Si se busca una pieza protagonista, existen también lotes centrados en tomahawk y acompañamientos.'),'Cómo organizar un lote al recibirlo'=>array('Separar la carne por comidas y fechas de consumo facilita aprovechar el pack. Lo que no vaya a utilizarse dentro de su vida útil puede porcionarse y congelarse siguiendo las indicaciones de conservación del producto.')),'bullets'=>array('Qué comparar entre lotes'=>array('Número de personas previsto.','Tipos de corte incluidos.','Cantidad total.','Uso: diario, barbacoa o comida especial.','Posibilidad de dividir y congelar por raciones.')),'faq_title'=>'Preguntas frecuentes','faq'=>array('¿Un lote sale siempre más barato?'=>'Depende de la composición y de las promociones vigentes; conviene comparar el contenido y el precio total.','¿Hay packs para barbacoa?'=>'Sí. Existe un lote específicamente planteado para barbacoa.','¿Puedo congelar parte del lote?'=>'En general sí, siempre que se haga respetando la conservación y el estado del producto recibido.')),
'en'=>array('intro'=>array('<strong>Beef boxes and meat packs</strong> make it possible to cover several meals with one purchase and can be more convenient than selecting every cut separately.','Tolecarnes offers boxes designed for families, couples, barbecues and mixed combinations of steaks, diced beef or tomahawk.'),'sections'=>array('Family or couples box'=>array('The main difference is quantity and how it is distributed among cuts. A family box prioritises volume and variety across several meals, while a couples box keeps portions more compact.','Check the exact contents and decide which items will be eaten soon and which may need to be frozen.'),'Barbecue packs'=>array('Barbecue packs group grill-friendly cuts and reduce the need to calculate each item separately. They work particularly well when the number of guests and the type of meal are already known.','Other packs focus on a centrepiece such as tomahawk together with complementary items.'),'Organising a meat box on arrival'=>array('Separating the meat by meal and intended date makes the box easier to use. Portions not required within their refrigerated shelf life can be frozen when appropriate, following the product storage guidance.')),'bullets'=>array('What to compare between boxes'=>array('Expected number of people.','Cuts included.','Total quantity.','Purpose: everyday meals, barbecue or special occasion.','Ease of dividing into portions.')),'faq_title'=>'Frequently asked questions','faq'=>array('Is a meat box always cheaper?'=>'Not necessarily. Compare the exact contents and current total price.','Are barbecue boxes available?'=>'Yes. A dedicated barbecue box is available.','Can part of a box be frozen?'=>'Generally yes when the product condition and storage instructions allow it.'))
),
array(
'key'=>'carne-guisar','group'=>'carnes','es_slug'=>'carne-para-guisar','en_slug'=>'beef-for-stews','es_title'=>'Carne para Guisar','en_title'=>'Beef for Stews','seo_title'=>'Comprar Carne para Guisar | Morcillo, Osobuco y Ragú','es_meta'=>'Compra carne para guisar: morcillo, osobuco, ragú, rabo y otros cortes de ternera preparados para cocciones lentas.','en_meta'=>'Buy beef for stews: shin, osso buco, diced beef, oxtail and other slow-cooking cuts from Tolecarnes.',
'products'=>array(11073,11090,11105,11110,11129,11103),
'es'=>array('intro'=>array('La <strong>carne para guisar</strong> necesita características distintas a las de un filete para plancha. Los mejores resultados suelen venir de cortes que ganan ternura con una cocción lenta y húmeda.','En esta selección encontrarás morcillo, osobuco, ragú, rabo y otras piezas de Tolecarnes adecuadas para guisos, estofados y platos de cuchara.'),'sections'=>array('Por qué algunos cortes mejoran con tiempo'=>array('Los cortes destinados a guiso suelen contener tejido conjuntivo que necesita tiempo para transformarse. Una cocción demasiado breve puede dejarlos firmes; una cocción lenta permite obtener una textura más melosa.','El objetivo no es cocinar a máxima temperatura, sino mantener un hervor controlado y dar tiempo a que el corte evolucione.'),'Morcillo, osobuco y ragú'=>array('El morcillo funciona bien en guisos largos y caldos. El osobuco incorpora hueso y médula, que aportan características propias al plato. El ragú ya viene troceado y resulta práctico cuando se quiere reducir preparación.','Rabo y otros cortes requieren también paciencia, pero permiten preparar recetas con salsas concentradas y texturas muy diferentes a las de la plancha.'),'Cómo calcular la compra'=>array('Al cocinar un guiso hay que considerar que el plato suele incluir salsa, verduras y otros ingredientes. La cantidad de carne por persona puede ser menor que en una comida basada exclusivamente en un filete o chuletón.')),'bullets'=>array('Cortes que encontrarás aquí'=>array('Morcillo de ternera.','Osobuco de ternera.','Magro o ragú de ternera.','Rabo de ternera.','Ragú de vacuno.','Redondo para determinadas elaboraciones.')),'faq_title'=>'Preguntas frecuentes','faq'=>array('¿Cuál es la mejor carne para un estofado largo?'=>'Morcillo, osobuco y rabo son opciones clásicas para cocciones prolongadas.','¿El ragú viene troceado?'=>'Sí. Es una opción práctica para empezar el guiso con menos preparación.','¿Se puede usar solomillo para guisar?'=>'Se puede, pero normalmente no es la elección más lógica por precio y por las características del corte.')),
'en'=>array('intro'=>array('<strong>Beef for stews</strong> needs different qualities from a quick-cooking steak. Cuts that become tender through slow, moist cooking are usually the most suitable.','This selection includes shin, osso buco, diced beef, oxtail and other Tolecarnes cuts for stews and braises.'),'sections'=>array('Why some cuts improve with time'=>array('Stewing cuts often contain connective tissue that needs time to transform. Cooking them too briefly can leave them firm, while slow cooking develops a softer texture.','The goal is controlled heat and enough time rather than the highest possible temperature.'),'Shin, osso buco and diced beef'=>array('Shin works well in long stews and broths. Osso buco includes bone and marrow, which contribute their own character. Diced beef reduces preparation time because the meat is already portioned.','Oxtail and similar cuts also reward patience and work well with concentrated sauces.'),'Planning quantities'=>array('A stew normally includes sauce, vegetables and other ingredients, so the amount of meat per person may be lower than for a meal centred on an individual steak.')),'bullets'=>array('Cuts in this selection'=>array('Beef shin.','Osso buco.','Lean diced beef or ragout.','Oxtail.','Beef flank ragout.','Round for selected slow-cooked recipes.')),'faq_title'=>'Frequently asked questions','faq'=>array('Which beef is best for a long stew?'=>'Shin, osso buco and oxtail are classic slow-cooking choices.','Is diced beef already cut?'=>'Yes. It reduces preparation before cooking.','Can tenderloin be used for stew?'=>'It can, but it is normally an inefficient choice for this cooking method.'))
),
array(
'key'=>'carne-asar','group'=>'carnes','es_slug'=>'carne-para-asar','en_slug'=>'beef-for-roasting','es_title'=>'Carne para Asar','en_title'=>'Beef for Roasting','seo_title'=>'Comprar Carne para Asar | Horno y Roast Beef','es_meta'=>'Compra carne para asar al horno: roast beef, redondo, aleta y cortes de ternera o vaca para piezas enteras y comidas especiales.','en_meta'=>'Buy beef for roasting: roasting joints, eye of round, flank for stuffing and tender cuts for oven cooking.',
'products'=>array(11154,11103,11136,11087,11125),
'es'=>array('intro'=>array('Elegir <strong>carne para asar</strong> consiste en buscar una pieza que pueda cocinarse entera o en porciones grandes y que permita controlar bien el punto interior.','Tolecarnes dispone de roast beef, redondo, aleta para rellenar y cortes tiernos como solomillo que pueden utilizarse en preparaciones de horno y comidas especiales.'),'sections'=>array('Roast beef y piezas enteras'=>array('Una pieza preparada para roast beef facilita una cocción uniforme y un corte posterior en lonchas. El redondo es otra opción clásica para asados, especialmente cuando se acompaña de salsa o se cocina con control de temperatura.','En piezas enteras conviene pensar en el punto final antes de introducirlas en el horno y tener en cuenta que la temperatura puede seguir subiendo durante el reposo.'),'Aleta para rellenar'=>array('La aleta permite preparar un asado relleno y enrollado. Es un formato diferente a una pieza de roast beef porque el relleno, el grosor final y el atado influyen directamente en el tiempo de cocción.','Resulta útil para comidas en las que se quiere servir una pieza preparada en lonchas.'),'Solomillo al horno'=>array('El solomillo puede cocinarse entero y después porcionarse. Al ser un corte tierno, necesita especial atención para no prolongar la cocción más de lo necesario.')),'bullets'=>array('Claves para un asado más controlado'=>array('Elige el corte según el número de personas.','Presta atención al grosor de la pieza.','Controla la temperatura interior.','Deja reposar antes de cortar.','Corta en lonchas solo cuando vaya a servirse.')),'faq_title'=>'Preguntas frecuentes','faq'=>array('¿Qué pieza es buena para roast beef?'=>'Existe un producto preparado específicamente como roast beef de ternera.','¿El redondo sirve para horno?'=>'Sí. Es una pieza clásica para asados y preparaciones con salsa.','¿Puedo asar un solomillo entero?'=>'Sí, controlando especialmente el tiempo y la temperatura para mantener la terneza.')),
'en'=>array('intro'=>array('Choosing <strong>beef for roasting</strong> means selecting a cut that can cook as a whole joint or large portion while allowing good control of the internal doneness.','Tolecarnes offers a dedicated roasting joint, eye of round, flank for stuffing and tender cuts such as beef tenderloin for oven cooking and special meals.'),'sections'=>array('Roasting joints and whole cuts'=>array('A dedicated roasting joint is designed for even cooking and later slicing. Eye of round is another classic option, particularly when served with sauce or cooked with careful temperature control.','For whole joints, decide the target doneness in advance and remember that internal temperature can continue rising during resting.'),'Flank for stuffing'=>array('A flank piece can be filled, rolled and tied before roasting. The filling and final thickness change the cooking time compared with a simple roasting joint.','It works particularly well when the finished meat will be served in slices.'),'Whole roasted tenderloin'=>array('Tenderloin can be cooked whole and portioned afterwards. Because it is naturally tender, careful timing is important to avoid overcooking.')),'bullets'=>array('Keys to controlled roasting'=>array('Choose the cut for the number of guests.','Consider the thickness of the joint.','Monitor internal temperature.','Rest before carving.','Slice shortly before serving.')),'faq_title'=>'Frequently asked questions','faq'=>array('Which cut is suitable for roast beef?'=>'A product is specifically prepared as a beef roasting joint.','Can eye of round be roasted?'=>'Yes. It is a classic roasting cut, especially with sauces.','Can tenderloin be roasted whole?'=>'Yes, with careful control of time and temperature.'))
),
array(
'key'=>'filetes-ternera','group'=>'carnes','es_slug'=>'filetes-ternera-online','en_slug'=>'beef-steaks-online','es_title'=>'Filetes de Ternera Online','en_title'=>'Beef Steaks Online','seo_title'=>'Comprar Filetes de Ternera Online | Cortes para Plancha','es_meta'=>'Compra filetes de ternera online: primera, segunda, aguja, cachopo y otros cortes preparados por Tolecarnes para plancha y recetas.','en_meta'=>'Buy beef steaks online from Tolecarnes: prime steaks, second cuts, chuck steaks and steaks prepared for cachopo.',
'products'=>array(11064,11117,11079,11114,11141,11075),
'es'=>array('intro'=>array('No todos los <strong>filetes de ternera</strong> son iguales. El corte determina terneza, grosor, sabor, precio y el tipo de receta para el que resulta más práctico.','Esta selección permite comparar filetes de primera y segunda, aguja, piezas para cachopo y otros cortes preparados por Tolecarnes.'),'sections'=>array('Filetes de primera y segunda'=>array('La clasificación comercial orienta sobre el tipo de pieza y su uso, pero no significa que un corte de segunda sea peor para cualquier receta. Algunos cortes ofrecen más sabor o funcionan mejor en preparaciones concretas.','Para una plancha rápida suele interesar un filete de grosor uniforme; para recetas con relleno o empanado puede ser más importante el tamaño y la forma.'),'Aguja y otros cortes con más carácter'=>array('La aguja presenta una estructura distinta a cortes más magros y puede ofrecer un sabor muy interesante. Controlar el punto de cocción ayuda a evitar que pierda jugosidad.','Otros filetes pueden elegirse por precio o por el tipo de plato, especialmente cuando van acompañados de salsa o se cocinan como parte de una receta.'),'Filetes para cachopo'=>array('Los filetes destinados a cachopo buscan una forma y tamaño apropiados para rellenar, cerrar y empanar. Comprar el corte ya preparado reduce trabajo y facilita conseguir piezas más regulares.')),'bullets'=>array('Cómo elegir filetes'=>array('Para plancha diaria: filetes uniformes y manejables.','Para cachopo: piezas amplias preparadas para rellenar.','Para sabor más intenso: cortes como aguja.','Para ajustar presupuesto: compara primera y segunda según el uso.')),'faq_title'=>'Preguntas frecuentes','faq'=>array('¿Qué diferencia hay entre primera y segunda?'=>'Son clasificaciones de los cortes y de sus características; la mejor elección depende de la receta.','¿Hay filetes preparados para cachopo?'=>'Sí. Tolecarnes ofrece filetes específicos para esta preparación.','¿La aguja sirve para plancha?'=>'Sí, controlando el tiempo y evitando una cocción excesiva.')),
'en'=>array('intro'=>array('Not all <strong>beef steaks</strong> are the same. The cut influences tenderness, thickness, flavour, price and the recipes it suits best.','This selection compares prime steaks, second cuts, chuck steaks, large steaks for cachopo and other Tolecarnes options.'),'sections'=>array('Prime and second-cut steaks'=>array('Commercial cut categories indicate different characteristics and uses, but a second cut is not automatically worse for every recipe. Some cuts offer stronger flavour or suit particular preparations better.','For quick pan cooking, even thickness is useful; for filled or breaded dishes, shape and size may matter more.'),'Chuck and more characterful cuts'=>array('Chuck steaks have a different structure from leaner cuts and can provide excellent flavour. Careful cooking helps preserve juiciness.','Other steaks can be selected according to budget and recipe, particularly when served with sauce or as part of a composed dish.'),'Steaks for cachopo'=>array('Steaks prepared for cachopo are selected for a shape and size suitable for filling, closing and breading. Buying them ready for this use reduces preparation work.')),'bullets'=>array('How to choose steaks'=>array('Everyday pan cooking: even, manageable steaks.','Cachopo: large steaks prepared for filling.','More pronounced flavour: cuts such as chuck.','Budget control: compare cuts according to intended use.')),'faq_title'=>'Frequently asked questions','faq'=>array('What is the difference between prime and second cuts?'=>'They are commercial cut classifications with different characteristics; the best option depends on the dish.','Are steaks prepared for cachopo available?'=>'Yes. Tolecarnes sells steaks specifically prepared for this dish.','Can chuck steak be pan cooked?'=>'Yes, with careful timing to avoid overcooking.'))
),
array(
'key'=>'hamburguesas-carne','group'=>'carnes','es_slug'=>'hamburguesas-ternera-vaca','en_slug'=>'beef-burgers-online','es_title'=>'Hamburguesas de Ternera y Vaca','en_title'=>'Beef Burgers Online','seo_title'=>'Comprar Hamburguesas de Ternera y Vaca | Tolecarnes','es_meta'=>'Compra hamburguesas de ternera, vaca y mixtas sin gluten preparadas por Tolecarnes. Compara las opciones disponibles para plancha o barbacoa.','en_meta'=>'Buy Tolecarnes beef burgers online, including young beef, mature beef and mixed beef-pork gluten-free options.',
'products'=>array(11148,11166,11061),
'es'=>array('intro'=>array('Las <strong>hamburguesas de ternera y vaca</strong> permiten elegir entre perfiles distintos sin tener que preparar la carne picada y formar cada unidad en casa.','Tolecarnes ofrece opciones 100% ternera, 100% vaca y hamburguesas mixtas de vacuno y cerdo, todas pensadas para una preparación rápida a la plancha o barbacoa.'),'sections'=>array('Ternera o vaca'=>array('La ternera suele ofrecer un perfil más suave, mientras que la vaca madura puede aportar un sabor más intenso. La elección depende de la preferencia personal y de los ingredientes con los que se vaya a acompañar.','No hace falta cargar una hamburguesa de toppings para disfrutarla: cuando se quiere apreciar la carne, una preparación sencilla permite comparar mejor las diferencias.'),'Hamburguesas mixtas'=>array('La mezcla de vacuno y cerdo produce una composición diferente a una hamburguesa 100% vacuno. Puede ser una alternativa para quien busca otro equilibrio de sabor y jugosidad.','Las opciones disponibles se presentan como sin gluten; conviene revisar siempre la ficha y el etiquetado si existe una necesidad alimentaria específica.'),'Plancha o barbacoa'=>array('Ambos métodos funcionan bien. En barbacoa hay que controlar especialmente las llamas provocadas por la grasa; en plancha conviene utilizar una superficie suficientemente caliente para marcar el exterior.')),'bullets'=>array('Opciones disponibles'=>array('Hamburguesa 100% ternera.','Hamburguesa 100% vaca madura.','Hamburguesa mixta de vacuno y cerdo.')),'faq_title'=>'Preguntas frecuentes','faq'=>array('¿Qué diferencia hay entre la de ternera y la de vaca?'=>'Principalmente el tipo y edad del vacuno, lo que puede influir en intensidad de sabor y textura.','¿Hay hamburguesas mixtas?'=>'Sí. Existe una opción combinando carne de vacuno y cerdo.','¿Son aptas para barbacoa?'=>'Sí. Pueden cocinarse tanto a la plancha como en parrilla.')),
'en'=>array('intro'=>array('<strong>Beef burgers</strong> make it easy to choose between different meat profiles without mincing and shaping portions at home.','Tolecarnes offers 100% young beef, 100% mature beef and mixed beef-and-pork burgers for quick pan or barbecue cooking.'),'sections'=>array('Young beef or mature beef'=>array('Younger beef generally has a milder profile, while mature beef can provide a stronger flavour. The best choice depends on personal preference and the ingredients served with the burger.','A simple preparation can make it easier to taste the differences between the meat options.'),'Mixed burgers'=>array('Combining beef and pork creates a different balance from a 100% beef burger and can offer another flavour and juiciness profile.','The available options are presented as gluten-free; customers with specific dietary requirements should still review the individual product information.'),'Pan or barbecue'=>array('Both methods work well. On a barbecue, control flare-ups caused by fat; on a pan or griddle, use a sufficiently hot surface to brown the exterior.')),'bullets'=>array('Available options'=>array('100% young beef burger.','100% mature beef burger.','Mixed beef and pork burger.')),'faq_title'=>'Frequently asked questions','faq'=>array('What is the difference between young and mature beef burgers?'=>'The age and type of beef can affect flavour intensity and texture.','Are mixed burgers available?'=>'Yes. One option combines beef and pork.','Can they be barbecued?'=>'Yes. They can be cooked on a grill or a hot pan.'))
)
);

try {
    $out=array(); $by_group=array('aceites'=>array(),'carnes'=>array());
    foreach($pages as $cfg){
        $row=emdo_ac_upsert($cfg);
        $row['es_title']=$cfg['es_title']; $row['en_title']=$cfg['en_title'];
        $out[]=$row; $by_group[$cfg['group']][]=$row;
    }
    emdo_ac_link_category('aceites',$by_group['aceites']);
    emdo_ac_link_category('carnes',$by_group['carnes']);
    flush_rewrite_rules(false);
    echo wp_json_encode(array('verified'=>true,'count'=>count($out),'aceites'=>count($by_group['aceites']),'carnes'=>count($by_group['carnes']),'pages'=>$out),JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES).PHP_EOL;
} catch(Throwable $e){
    fwrite(STDERR,$e->getMessage().PHP_EOL); exit(1);
}
