<?php
/** La Huerta de Ana Mary product copy batch 09 (ES + EN). */
if (!defined('ABSPATH')) { exit("Run inside WordPress\n"); }
global $wpdb;
function mo_ha9_fail($m){ if(defined('WP_CLI')&&WP_CLI){WP_CLI::error($m);} throw new Exception($m); }
function mo_ha9_vendor($p){$u=get_userdata((int)$p->post_author);return $u?(string)$u->display_name:'';}
function mo_ha9_segments($h){$o=[];if(preg_match_all('~<(h2|h3|p)\b[^>]*>(.*?)</\1>~isu',$h,$m,PREG_SET_ORDER)){foreach($m as $r){$t=trim(html_entity_decode(wp_strip_all_tags($r[2]),ENT_QUOTES|ENT_HTML5,'UTF-8'));if($t!=='')$o[]=['tag'=>strtolower($r[1]),'text'=>$t];}}return $o;}
function mo_ha9_pair($es,$en,$label){$a=mo_ha9_segments($es);$b=mo_ha9_segments($en);if(count($a)!==count($b))mo_ha9_fail("Segment mismatch {$label}");$o=[];foreach($a as $i=>$r){if($r['tag']!==$b[$i]['tag'])mo_ha9_fail("Tag mismatch {$label}");$o[$r['text']]=$b[$i]['text'];}return $o;}
function mo_ha9_trp($table,$o,$t){global $wpdb;$id=$wpdb->get_var($wpdb->prepare("SELECT id FROM `{$table}` WHERE original=%s ORDER BY id DESC LIMIT 1",$o));if($id){if($wpdb->update($table,['translated'=>$t,'status'=>2,'block_type'=>0],['id'=>(int)$id],['%s','%d','%d'],['%d'])===false)mo_ha9_fail("TRP update failed");}else{if($wpdb->insert($table,['original'=>$o,'translated'=>$t,'status'=>2,'block_type'=>0],['%s','%s','%d','%d'])===false)mo_ha9_fail("TRP insert failed");}}
$producer_es=<<<'HTML'
<h2>Sobre La Huerta de Ana Mary</h2>
<p>En Fresno de la Vega, en la provincia de León, la agricultura y el cultivo de hortalizas forman parte de una tradición ligada a la Vega del Esla desde hace generaciones. La Huerta de Ana Mary continúa esa actividad familiar, con más de tres generaciones vinculadas al trabajo en el campo.</p>
<p>Las verduras y hortalizas se cultivan en parcelas de Fresno de la Vega, aprovechando la experiencia agrícola de la zona y adaptando el trabajo a los ciclos y temporadas de cada cultivo.</p>
<p>La recolección se organiza en función de los pedidos para reducir el tiempo de almacenamiento y acortar al máximo el recorrido entre la huerta y el consumidor, favoreciendo que el producto llegue fresco y en buenas condiciones.</p>
HTML;
$producer_en=<<<'HTML'
<h2>About La Huerta de Ana Mary</h2>
<p>In Fresno de la Vega, in the province of León, farming and vegetable growing are part of a tradition connected to the Vega del Esla that goes back generations. La Huerta de Ana Mary continues this family activity, with more than three generations linked to working the land.</p>
<p>The vegetables are grown on plots in Fresno de la Vega, drawing on the farming experience of the area and adapting the work to the cycles and seasons of each crop.</p>
<p>Harvesting is organised around orders to reduce storage time and keep the journey from the fields to the customer as short as possible, helping the produce arrive fresh and in good condition.</p>
HTML;
$products=[
['id'=>12829,'title'=>'4 Cajas de hortalizas 7 kg, recíbelas cada semana','title_en'=>'4 Boxes of Seasonal Vegetables, 7 kg Each','slug'=>'4-cajas-de-hortalizas-7-kg-recibelas-cada-semana','es_excerpt'=>'<p>Pack de 4 cajas de hortalizas frescas y de temporada de 7 kg cada una. Se pueden recibir semanalmente durante un mes o cada 15 días durante dos meses. Gastos de envío incluidos a destinos de la Península.</p>','en_excerpt'=>'<p>Pack of 4 boxes of fresh seasonal vegetables, 7 kg each. They can be delivered weekly over one month or every 15 days over two months. Shipping is included to mainland Spain.</p>','es_content'=><<<'HTML'
<h2>Cuatro cajas de hortalizas frescas y de temporada</h2>
<p>Este formato incluye cuatro cajas de 7 kg con una selección de hortalizas de temporada. La composición cambia según la disponibilidad de la huerta, de modo que las cajas se adaptan a los productos disponibles en cada momento.</p>
<p>Las cuatro entregas pueden organizarse semanalmente durante un mes o cada 15 días durante dos meses. La ficha actual indica que los gastos de envío están incluidos a destinos de la Península.</p>
<h2>Cómo aprovechar las cajas</h2>
<p>La selección permite disponer de distintas hortalizas para ensaladas, guisos, cremas, salteados, asados y otras preparaciones cotidianas. Al ser un surtido de temporada, el contenido concreto puede variar entre entregas.</p>
<p>Al recibir cada caja, conviene conservar cada producto según sus necesidades, ya que algunas hortalizas se mantienen mejor refrigeradas y otras en un lugar fresco, seco y ventilado.</p>
HTML,'en_content'=><<<'HTML'
<h2>Four boxes of fresh seasonal vegetables</h2>
<p>This format includes four 7 kg boxes with a selection of seasonal vegetables. The contents vary according to what is available from the fields at each point in the season.</p>
<p>The four deliveries can be arranged weekly over one month or every 15 days over two months. The current product information states that shipping is included to mainland Spain.</p>
<h2>How to use the boxes</h2>
<p>The selection provides different vegetables for salads, stews, soups, sautés, roasting and other everyday dishes. Because it is a seasonal assortment, the exact contents may change from one delivery to another.</p>
<p>When each box arrives, store every item according to its needs, as some vegetables keep best refrigerated while others prefer a cool, dry and well-ventilated place.</p>
HTML,'es_faq'=><<<'HTML'
<h2>Preguntas frecuentes</h2><h3>¿Cuántas cajas incluye?</h3><p>Incluye cuatro cajas de 7 kg cada una.</p><h3>¿Cada cuánto se reciben?</h3><p>Pueden recibirse una vez por semana durante un mes o cada 15 días durante dos meses.</p><h3>¿La composición es siempre la misma?</h3><p>No. La selección varía según las hortalizas de temporada disponibles en cada momento.</p>
HTML,'en_faq'=><<<'HTML'
<h2>Frequently asked questions</h2><h3>How many boxes are included?</h3><p>The pack includes four boxes of 7 kg each.</p><h3>How often are they delivered?</h3><p>They can be delivered once a week for one month or every 15 days for two months.</p><h3>Are the contents always the same?</h3><p>No. The selection varies according to the seasonal vegetables available at the time.</p>
HTML],
['id'=>12832,'title'=>'Alubia canela','title_en'=>'Cinnamon Beans','slug'=>'alubia-canela','es_excerpt'=>'<p>Alubia canela de tamaño mediano, forma alargada y redondeada y característico color canela. Al cocerse mantiene bien la forma y produce un caldo cremoso. Se cultiva en el Páramo Leonés y en Zamora.</p>','en_excerpt'=>'<p>Medium-sized cinnamon beans with an elongated, rounded shape and characteristic cinnamon colour. They hold their shape well when cooked and produce a creamy broth. Grown in the Páramo Leonés area and Zamora.</p>','es_content'=><<<'HTML'
<h2>Alubia canela para guisos y platos de cuchara</h2><p>La alubia canela se reconoce por su color, su tamaño mediano y su forma alargada y redondeada. Durante la cocción adquiere un tono más anaranjado y mantiene bien la forma sin deshacerse con facilidad.</p><p>Es una alubia adecuada para preparaciones en las que se busca un caldo cremoso. La ficha actual sitúa su cultivo en el Páramo Leonés y en Zamora.</p><h2>Cómo prepararla</h2><p>Puede utilizarse en potajes, guisos de legumbres y platos de cuchara. Como con otras alubias secas, conviene adaptar el remojo y el tiempo de cocción al método utilizado y a la textura deseada.</p>
HTML,'en_content'=><<<'HTML'
<h2>Cinnamon beans for stews and slow-cooked dishes</h2><p>Cinnamon beans are recognised by their colour, medium size and elongated, rounded shape. During cooking they take on a more orange-brown tone and hold their shape well.</p><p>They work especially well in dishes where a creamy broth is desired. The current product information places their cultivation in the Páramo Leonés area and Zamora.</p><h2>How to cook them</h2><p>Use them in bean stews and other slow-cooked dishes. As with other dried beans, soaking and cooking times should be adjusted to the cooking method and the texture you want.</p>
HTML,'es_faq'=><<<'HTML'
<h2>Preguntas frecuentes</h2><h3>¿Dónde se cultiva?</h3><p>La ficha actual indica cultivo en el Páramo Leonés y en Zamora.</p><h3>¿Se deshace al cocer?</h3><p>Es una variedad que mantiene bien la forma durante la cocción.</p><h3>¿Para qué platos es adecuada?</h3><p>Para potajes, guisos y otros platos de cuchara.</p>
HTML,'en_faq'=><<<'HTML'
<h2>Frequently asked questions</h2><h3>Where is it grown?</h3><p>The current product information states that it is grown in the Páramo Leonés area and Zamora.</p><h3>Does it fall apart when cooked?</h3><p>It is a variety that holds its shape well during cooking.</p><h3>What dishes is it suitable for?</h3><p>Bean stews and other slow-cooked dishes.</p>
HTML],
['id'=>12837,'title'=>'Alubia blanca de riñón','title_en'=>'White Kidney Beans','slug'=>'alubia-blanca-de-rinon','es_excerpt'=>'<p>Alubia blanca de riñón de tamaño mediano, color blanquecino y forma arriñonada. Destaca por su textura suave, piel fina y carácter mantecoso una vez cocinada.</p>','en_excerpt'=>'<p>Medium-sized white kidney beans with an off-white colour and kidney shape. They are known for their smooth texture, thin skin and buttery character once cooked.</p>','es_content'=><<<'HTML'
<h2>Alubia blanca de riñón de textura suave</h2><p>Esta variedad se caracteriza por su color blanquecino, tamaño mediano y forma arriñonada. Una vez cocida ofrece una textura suave y mantecosidad, con una piel fina.</p><h2>Cómo prepararla</h2><p>Es una alubia versátil para potajes, guisos, platos de cuchara y otras recetas con legumbres. El remojo y el tiempo de cocción pueden ajustarse al método utilizado y al punto de textura que se busque.</p>
HTML,'en_content'=><<<'HTML'
<h2>White kidney beans with a smooth texture</h2><p>This variety is characterised by its off-white colour, medium size and kidney shape. Once cooked it develops a smooth, buttery texture with a thin skin.</p><h2>How to cook them</h2><p>They are versatile beans for stews, slow-cooked dishes and other pulse-based recipes. Soaking and cooking times can be adjusted to the method used and the texture you prefer.</p>
HTML,'es_faq'=><<<'HTML'
<h2>Preguntas frecuentes</h2><h3>¿Cómo es esta alubia?</h3><p>Es de tamaño mediano, color blanquecino y forma arriñonada.</p><h3>¿Qué textura tiene una vez cocida?</h3><p>Ofrece una textura suave y mantecosidad, con una piel fina.</p><h3>¿Para qué recetas puede utilizarse?</h3><p>Para potajes, guisos y otros platos de legumbres.</p>
HTML,'en_faq'=><<<'HTML'
<h2>Frequently asked questions</h2><h3>What is this bean like?</h3><p>It is medium-sized, off-white and kidney-shaped.</p><h3>What is its cooked texture?</h3><p>It has a smooth, buttery texture with a thin skin.</p><h3>What recipes can it be used for?</h3><p>Stews and other bean-based dishes.</p>
HTML],
['id'=>12841,'title'=>'Alubias pintas','title_en'=>'Pinto Beans','slug'=>'alubias-pintas','es_excerpt'=>'<p>Alubias pintas de tamaño grande, forma redondeada y color rosáceo con pintas granates. Mantienen bien la forma al cocinarse y producen un caldo oscuro y cremoso. Cultivadas en tierras de La Bañeza, León.</p>','en_excerpt'=>'<p>Large pinto beans with a rounded shape and pinkish colour marked with burgundy speckles. They hold their shape well when cooked and produce a dark, creamy broth. Grown around La Bañeza, León.</p>','es_content'=><<<'HTML'
<h2>Alubias pintas para guisos con caldo cremoso</h2><p>La alubia pinta tiene un tamaño grande, forma redondeada y un característico color rosáceo con pintas granates. Durante la cocción mantiene bien la forma y aporta al caldo un tono oscuro y una textura cremosa.</p><p>Es habitual en guisos del norte de España. La ficha actual indica que se cultiva en tierras de La Bañeza, en León.</p><h2>Cómo prepararlas</h2><p>Funcionan bien en potajes, guisos tradicionales y otros platos de cuchara. El remojo y el tiempo de cocción pueden adaptarse al método utilizado y al punto deseado.</p>
HTML,'en_content'=><<<'HTML'
<h2>Pinto beans for rich, creamy stews</h2><p>Pinto beans are large and rounded, with a characteristic pinkish colour and burgundy speckles. They hold their shape well while cooking and give the broth a darker colour and creamy texture.</p><p>They are commonly used in northern Spanish stews. The current product information states that they are grown around La Bañeza, in León.</p><h2>How to cook them</h2><p>They work well in traditional bean stews and other slow-cooked dishes. Soaking and cooking times can be adjusted to the method used and the texture you want.</p>
HTML,'es_faq'=><<<'HTML'
<h2>Preguntas frecuentes</h2><h3>¿Dónde se cultivan?</h3><p>La ficha actual indica cultivo en tierras de La Bañeza, León.</p><h3>¿Se deshacen al cocinarlas?</h3><p>Mantienen bien la forma durante la cocción.</p><h3>¿Para qué platos son adecuadas?</h3><p>Para potajes, guisos tradicionales y otros platos de cuchara.</p>
HTML,'en_faq'=><<<'HTML'
<h2>Frequently asked questions</h2><h3>Where are they grown?</h3><p>The current product information states that they are grown around La Bañeza, León.</p><h3>Do they fall apart when cooked?</h3><p>They hold their shape well during cooking.</p><h3>What dishes are they suitable for?</h3><p>Traditional bean stews and other slow-cooked dishes.</p>
HTML],
['id'=>12845,'title'=>'Garbanzo pedrosillano','title_en'=>'Pedrosillano Chickpeas','slug'=>'garbanzo-pedrosillano','es_excerpt'=>'<p>Garbanzo pedrosillano, también conocido como pico de pardal, de tamaño pequeño, forma casi esférica y color amarillo anaranjado. Se vende por kilo y es una variedad muy utilizada en cocidos, potajes y ensaladas.</p>','en_excerpt'=>'<p>Pedrosillano chickpeas, also known as pico de pardal, small and almost spherical with a yellow-orange colour. Sold by the kilogram and widely used in stews, cocidos and salads.</p>','es_content'=><<<'HTML'
<h2>Garbanzo pedrosillano de pequeño tamaño</h2><p>El garbanzo pedrosillano, también conocido como pico de pardal, se distingue por su tamaño pequeño, forma casi esférica, color amarillo anaranjado y un pico corto y marcado.</p><p>Esta referencia se vende por kilo.</p><h2>Cómo prepararlo</h2><p>Puede utilizarse en cocidos, potajes, guisos, ensaladas y otras recetas con legumbres. Al tratarse de garbanzo seco, conviene adaptar el remojo y el tiempo de cocción al método empleado y a la textura deseada.</p>
HTML,'en_content'=><<<'HTML'
<h2>Small Pedrosillano chickpeas</h2><p>Pedrosillano chickpeas, also known as pico de pardal, are distinguished by their small size, almost spherical shape, yellow-orange colour and short pointed tip.</p><p>This product is sold by the kilogram.</p><h2>How to cook them</h2><p>Use them in cocidos, stews, salads and other pulse-based recipes. As dried chickpeas, soaking and cooking times should be adjusted to the method used and the texture you want.</p>
HTML,'es_faq'=><<<'HTML'
<h2>Preguntas frecuentes</h2><h3>¿Qué tamaño tiene?</h3><p>Es un garbanzo de tamaño pequeño y forma casi esférica.</p><h3>¿Cómo se vende?</h3><p>Esta referencia se vende por kilo.</p><h3>¿Para qué recetas puede utilizarse?</h3><p>Para cocidos, potajes, guisos, ensaladas y otras recetas con legumbres.</p>
HTML,'en_faq'=><<<'HTML'
<h2>Frequently asked questions</h2><h3>What size is it?</h3><p>It is a small, almost spherical chickpea.</p><h3>How is it sold?</h3><p>This product is sold by the kilogram.</p><h3>What recipes can it be used for?</h3><p>Cocidos, stews, salads and other pulse-based dishes.</p>
HTML]
];
$table=$wpdb->prefix.'trp_dictionary_es_es_en_us';if($wpdb->get_var($wpdb->prepare('SHOW TABLES LIKE %s',$table))!==$table)mo_ha9_fail('TranslatePress table missing');$backup=[];$pairs=[];
foreach($products as $i=>$p){$post=get_post($p['id']);if(!$post||$post->post_type!=='product'||$post->post_status!=='publish')mo_ha9_fail("Missing/unpublished {$p['id']}");if($post->post_title!==$p['title'])mo_ha9_fail("Title mismatch {$p['id']}: {$post->post_title}");if($post->post_name!==$p['slug'])mo_ha9_fail("Slug mismatch {$p['id']}");if(stripos(mo_ha9_vendor($post),'Huerta de Ana Mary')===false)mo_ha9_fail("Vendor mismatch {$p['id']}");if(get_post_meta($p['id'],'_stock_status',true)!=='instock')mo_ha9_fail("Not instock {$p['id']}");$backup[$p['id']]=['post_excerpt'=>$post->post_excerpt,'post_content'=>$post->post_content,'_en_US_post_excerpt'=>get_post_meta($p['id'],'_en_US_post_excerpt',true),'_en_US_post_content'=>get_post_meta($p['id'],'_en_US_post_content',true)];$products[$i]['full_es']=$p['es_content']."\n".$producer_es."\n".$p['es_faq'];$products[$i]['full_en']=$p['en_content']."\n".$producer_en."\n".$p['en_faq'];$pairs[$p['title']]=$p['title_en'];$pairs=array_merge($pairs,mo_ha9_pair($p['es_excerpt'],$p['en_excerpt'],"excerpt {$p['id']}"));$pairs=array_merge($pairs,mo_ha9_pair($products[$i]['full_es'],$products[$i]['full_en'],"content {$p['id']}"));}
$key='mo_huerta_anamary_batch09_backup_20260831';if(get_option($key,false)===false){add_option($key,$backup,'','no');echo "BACKUP created {$key}\n";}else echo "BACKUP exists {$key}\n";
foreach($products as $p){$r=wp_update_post(['ID'=>$p['id'],'post_excerpt'=>$p['es_excerpt'],'post_content'=>$p['full_es']],true);if(is_wp_error($r))mo_ha9_fail("Update failed {$p['id']}");update_post_meta($p['id'],'_en_US_post_excerpt',$p['en_excerpt']);update_post_meta($p['id'],'_en_US_post_content',$p['full_en']);}
foreach($pairs as $o=>$t)mo_ha9_trp($table,$o,$t);
foreach($products as $p){$post=get_post($p['id']);$en=(string)get_post_meta($p['id'],'_en_US_post_content',true);$ens=(string)get_post_meta($p['id'],'_en_US_post_excerpt',true);if(strpos($post->post_content,'Sobre La Huerta de Ana Mary')===false||strpos($post->post_content,'Preguntas frecuentes')===false)mo_ha9_fail("ES verify {$p['id']}");if(strpos($en,'About La Huerta de Ana Mary')===false||strpos($en,'Frequently asked questions')===false||trim(wp_strip_all_tags($ens))==='')mo_ha9_fail("EN verify {$p['id']}");echo "UPDATED_AND_VERIFIED ID={$p['id']} {$p['title']}\n";}
echo 'DONE huerta_batch09_products='.count($products).' translations='.count($pairs)."\n";
