<?php
if (!defined('ABSPATH')) exit;
global $wpdb;

function emdo_r_norm($url){$u=wp_parse_url(html_entity_decode((string)$url,ENT_QUOTES|ENT_HTML5,'UTF-8'));if(!$u||empty($u['path']))return null;$p='/'.trim($u['path'],'/').'/';return preg_replace('#/+#','/',$p);}
function emdo_r_links($html){preg_match_all('/<a\b[^>]*\bhref\s*=\s*(["\'])(.*?)\1[^>]*>(.*?)<\/a>/isu',(string)$html,$m,PREG_SET_ORDER);$o=[];foreach($m as $x){$h=trim(html_entity_decode($x[2],ENT_QUOTES|ENT_HTML5,'UTF-8'));if($h===''||str_starts_with($h,'#')||preg_match('#^(?:mailto|tel|javascript):#i',$h))continue;$o[]=['href'=>$h,'anchor'=>trim(preg_replace('/\s+/u',' ',wp_strip_all_tags($x[3])))];}return $o;}
function emdo_r_tokens($s){$s=remove_accents(mb_strtolower(wp_strip_all_tags((string)$s),'UTF-8'));preg_match_all('/[a-z0-9]+/u',$s,$m);$stop=array_fill_keys(['que','como','para','por','con','del','las','los','una','uno','unos','unas','sus','sin','mas','muy','hay','cada','entre','sobre','esta','este','estos','estas','guia','complete','guide','what','how','why','the','and','with','from','into','when','which','does','really','more','your'],true);$o=[];foreach($m[0] as $t)if(strlen($t)>=3&&empty($stop[$t]))$o[$t]=1;return array_keys($o);}
function emdo_r_j($a,$b){$a=array_fill_keys($a,1);$b=array_fill_keys($b,1);if(!$a||!$b)return 0;$i=0;foreach($a as $k=>$_)if(isset($b[$k]))$i++;return $i/count($a+$b);}
function emdo_r_slug_from_path($path,$lang){$p=trim($path,'/');if($lang==='en'&&str_starts_with($p,'en/'))$p=substr($p,3);return trim($p,'/');}

$posts=get_posts(['post_type'=>'post','post_status'=>'publish','numberposts'=>-1]);$ids=array_fill_keys(array_map(fn($p)=>$p->ID,$posts),1);$cur=['es'=>[],'en'=>[]];$data=[];
foreach($posts as $p){$es=emdo_r_norm(get_permalink($p->ID));$ens=(string)get_post_meta($p->ID,'_en_US_post_name',true);$en=$ens?'/en/'.trim($ens,'/').'/':null;$data[$p->ID]=['es_title'=>$p->post_title,'en_title'=>(string)get_post_meta($p->ID,'_en_US_post_title',true),'es_slug'=>$p->post_name,'en_slug'=>$ens,'es_html'=>$p->post_content,'en_html'=>(string)get_post_meta($p->ID,'_en_US_post_content',true)];if($es)$cur['es'][$es]=$p->ID;if($en)$cur['en'][$en]=$p->ID;}
$old_es=[];$rows=$wpdb->get_results("SELECT post_id,meta_value FROM {$wpdb->postmeta} WHERE meta_key='_wp_old_slug'");foreach($rows as $r){$id=(int)$r->post_id;if(isset($ids[$id])&&$r->meta_value!=='')$old_es['/'.trim($r->meta_value,'/').'/']=$id;}
$redirects=[];$raw=get_option('emdo_authority_redirects_20260902',[]);if(is_array($raw)){foreach($raw as $k=>$v){if(is_string($k)&&is_string($v)){$redirects[emdo_r_norm($k)??$k]=emdo_r_norm($v)??$v;}elseif(is_array($v)){foreach(['from','source','old'] as $fk)foreach(['to','target','new'] as $tk)if(!empty($v[$fk])&&!empty($v[$tk])){$redirects[emdo_r_norm($v[$fk])??$v[$fk]]=emdo_r_norm($v[$tk])??$v[$tk];break 2;}}}}
function emdo_r_direct($lang,$path,$cur,$old_es,$redirects){if(isset($cur[$lang][$path]))return ['kind'=>'current','id'=>$cur[$lang][$path]];if($lang==='es'&&isset($old_es[$path]))return ['kind'=>'old_slug','id'=>$old_es[$path]];if(isset($redirects[$path])){$to=$redirects[$path];if(isset($cur[$lang][$to]))return ['kind'=>'redirect_map','id'=>$cur[$lang][$to]];}return null;}

$un=[];
foreach($posts as $p){foreach(['es','en'] as $lang){$html=$lang==='es'?$p->post_content:(string)get_post_meta($p->ID,'_en_US_post_content',true);foreach(emdo_r_links($html) as $ln){$parts=wp_parse_url($ln['href']);$host=strtolower($parts['host']??'');if($host&&!in_array($host,['www.elmercadodeorigen.com','elmercadodeorigen.com'],true))continue;$path=emdo_r_norm($ln['href']);if(!$path||!preg_match('#^/(?:en/)?[^/]+/$#',$path)||isset($cur[$lang][$path]))continue;$un[$lang.'|'.$path]=['lang'=>$lang,'path'=>$path,'from'=>$p->ID,'anchor'=>$ln['anchor']];}}}

$out=[];$counts=['total'=>count($un),'old_slug'=>0,'redirect_map'=>0,'valid_nonpost'=>0,'crosslang'=>0,'fuzzy'=>0,'ambiguous'=>0];
foreach($un as $u){$lang=$u['lang'];$path=$u['path'];$sid=$u['from'];$direct=emdo_r_direct($lang,$path,$cur,$old_es,$redirects);if($direct&&$direct['kind']!=='current'){$u['resolution']=$direct;$u['target_title']=$lang==='es'?$data[$direct['id']]['es_title']:$data[$direct['id']]['en_title'];$counts[$direct['kind']]++;$out[]=$u;continue;}
 $url=home_url($path);$obj=url_to_postid($url);if($obj&&(!isset($ids[$obj])||get_post_type($obj)!=='post')){$u['resolution']=['kind'=>'valid_nonpost','id'=>$obj,'type'=>get_post_type($obj)];$counts['valid_nonpost']++;$out[]=$u;continue;}
 $other=$lang==='es'?'en':'es';$other_html=$data[$sid][$other.'_html']??'';$cand=[];foreach(emdo_r_links($other_html) as $ol){$oparts=wp_parse_url($ol['href']);$oh=strtolower($oparts['host']??'');if($oh&&!in_array($oh,['www.elmercadodeorigen.com','elmercadodeorigen.com'],true))continue;$op=emdo_r_norm($ol['href']);if(!$op)continue;$r=emdo_r_direct($other,$op,$cur,$old_es,$redirects);if($r&&isset($data[$r['id']]))$cand[$r['id']]=1;}
 $srcTok=emdo_r_tokens($u['anchor'].' '.str_replace('-',' ',emdo_r_slug_from_path($path,$lang)));$scores=[];foreach(array_keys($cand) as $tid){$tt=($lang==='es'?$data[$tid]['es_title'].' '.$data[$tid]['es_slug']:$data[$tid]['en_title'].' '.$data[$tid]['en_slug']);$scores[$tid]=emdo_r_j($srcTok,emdo_r_tokens($tt));}arsort($scores);$bestId=$scores?array_key_first($scores):null;$best=$bestId!==null?$scores[$bestId]:0;$second=count($scores)>1?array_values($scores)[1]:0;
 if($bestId!==null&&$best>=0.28&&($best-$second)>=0.08){$u['resolution']=['kind'=>'crosslang','id'=>$bestId,'score'=>round($best,3),'margin'=>round($best-$second,3)];$u['target_title']=$lang==='es'?$data[$bestId]['es_title']:$data[$bestId]['en_title'];$counts['crosslang']++;$out[]=$u;continue;}
 $scores=[];foreach($data as $tid=>$d){$tt=$lang==='es'?$d['es_title'].' '.$d['es_slug']:$d['en_title'].' '.$d['en_slug'];$scores[$tid]=emdo_r_j($srcTok,emdo_r_tokens($tt));}arsort($scores);$bestId=array_key_first($scores);$best=$scores[$bestId]??0;$second=count($scores)>1?array_values($scores)[1]:0;if($best>=0.58&&($best-$second)>=0.14){$u['resolution']=['kind'=>'fuzzy','id'=>$bestId,'score'=>round($best,3),'margin'=>round($best-$second,3)];$u['target_title']=$lang==='es'?$data[$bestId]['es_title']:$data[$bestId]['en_title'];$counts['fuzzy']++;}else{$u['resolution']=['kind'=>'ambiguous','best_id'=>$bestId,'best_score'=>round($best,3),'second_score'=>round($second,3)];$u['best_title']=$lang==='es'?$data[$bestId]['es_title']:$data[$bestId]['en_title'];$counts['ambiguous']++;}$out[]=$u;
}
echo "EMDO_UNRESOLVED_RESOLVER_BEGIN\n";echo wp_json_encode(['counts'=>$counts,'items'=>$out],JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES)."\n";echo "EMDO_UNRESOLVED_RESOLVER_END\n";
