<?php
if (!defined('ABSPATH')) { exit; }
function emdop3_words($html){$text=trim(preg_replace('/\s+/u',' ',wp_strip_all_tags(strip_shortcodes($html))));if($text==='')return 0;preg_match_all('/[\p{L}\p{M}]+(?:[’\x{27}’-][\p{L}\p{M}]+)*/u',$text,$m);return count($m[0]);}
function emdop3_cat($name,$slug,$en_name,$en_slug,$fallback_name=''){$term=get_term_by('slug',$slug,'category');if(!$term&&$fallback_name!=='')$term=get_term_by('name',$fallback_name,'category');if(!$term)$term=get_term_by('name',$name,'category');if(!$term){$made=wp_insert_term($name,'category',array('slug'=>$slug));if(is_wp_error($made))throw new Exception($made->get_error_message());$term=get_term((int)$made['term_id'],'category');}update_term_meta($term->term_id,'_en_US_name',$en_name);update_term_meta($term->term_id,'_en_US_slug',$en_slug);update_term_meta($term->term_id,'_en_US_published','1');return (int)$term->term_id;}
function emdop3_existing($key,$slug){$ids=get_posts(array('post_type'=>'post','post_status'=>'any','posts_per_page'=>1,'fields'=>'ids','meta_key'=>'_emdo_authority_key','meta_value'=>$key));if($ids)return (int)$ids[0];$p=get_page_by_path($slug,OBJECT,'post');return $p?(int)$p->ID:0;}
$dir=(string)getenv('EMDO_PRIORITY_BATCH03_DIR');if(!$dir||!is_dir($dir))throw new Exception('Priority batch 03 data directory missing');$files=glob(trailingslashit($dir).'*.php');sort($files,SORT_NATURAL);if(count($files)!==5)throw new Exception('Expected five article files');
$guide=emdop3_cat('Guías y consejos','guias-y-consejos','Guides and advice','guides-and-advice');
$cats=array(
'meat'=>emdop3_cat('Carnes','carnes','Meat','meat'),
'oil'=>emdop3_cat('Aceites','aceites','Olive oil','olive-oil'),
'cured'=>emdop3_cat('Embutidos y curados','embutidos-y-curados','Cured meats','cured-meats','Embutidos y curados'));
$product_slugs=array('meat'=>'carnes','oil'=>'aceites','cured'=>'embutidos-curados');
$default=(int)get_option('emdo_default_blog_featured_attachment_id',0);if($default<=0||get_post_type($default)!=='attachment')throw new Exception('Central provisional image missing');$default_hash=(string)get_option('emdo_default_blog_featured_hash','');$admins=get_users(array('role'=>'administrator','number'=>1,'fields'=>'ID'));$author=$admins?(int)$admins[0]:1;$rows=array();
foreach($files as $file){
$a=require $file;
foreach(array('key','priority','slug','en_slug','topic','title','en_title','excerpt','en_excerpt','content','en_content','min_es','min_en') as $f){if(!isset($a[$f])||$a[$f]==='')throw new Exception(basename($file).' missing '.$f);}
if(!isset($cats[$a['topic']]))throw new Exception('Unexpected topic '.$a['topic']);if((int)$a['priority']<11||(int)$a['priority']>15)throw new Exception('Unexpected priority '.(int)$a['priority']);
$product=$product_slugs[$a['topic']];$content=str_replace('__PRODUCT_CAT__',$product,$a['content']);$en=str_replace('__PRODUCT_CAT__',$product,$a['en_content']);
if($a['key']==='priority-12-vacuum-meat-purple'){
$content=str_replace('<h2>Una regla práctica para recordar</h2>','<h2>¿Por qué el interior puede conservar un color diferente?</h2><p>Al cortar una pieza también es posible observar que la superficie y el interior no tienen exactamente el mismo tono. Es normal: <strong>el oxígeno no penetra de forma uniforme ni instantánea en todo el músculo</strong>. La parte exterior reacciona primero con el aire, mientras que las zonas internas permanecen durante más tiempo en un entorno con menos oxígeno. Por eso una carne recién cortada puede mostrar un centro más púrpura y un exterior más rojo sin que exista ninguna anomalía.</p><p>Si dejamos la nueva superficie unos minutos expuesta al aire, su color también puede evolucionar. Esta diferencia entre exterior e interior es otra razón para no utilizar una fotografía instantánea del color como prueba única de frescura o deterioro.</p><h2>Una regla práctica para recordar</h2>',$content);
$en=str_replace('<h2>The rule worth remembering</h2>','<h2>Why can the inside remain a different colour?</h2><p>After cutting a piece of beef, the outside and the newly exposed centre may not have the same shade. That is normal because <strong>oxygen does not penetrate the whole muscle evenly or instantly</strong>. The outer surface reacts with air first, while the centre remains in a lower-oxygen environment for longer. A freshly cut steak can therefore show a more purple centre and a redder exterior without anything being wrong.</p><p>If the new cut surface is exposed to air for a few minutes, that colour can also evolve. This outside-versus-inside difference is another reason not to use one snapshot of colour as the sole test of freshness or spoilage.</p><h2>The rule worth remembering</h2>',$en);
}
$wes=emdop3_words($content);$wen=emdop3_words($en);if($wes<(int)$a['min_es']||$wen<(int)$a['min_en'])throw new Exception($a['key'].' too short ES='.$wes.'/'.(int)$a['min_es'].' EN='.$wen.'/'.(int)$a['min_en']);$existing=emdop3_existing($a['key'],$a['slug']);$new=$existing<=0;$post=array('post_type'=>'post','post_status'=>'publish','post_author'=>$author,'post_title'=>wp_strip_all_tags($a['title']),'post_name'=>sanitize_title($a['slug']),'post_excerpt'=>wp_strip_all_tags($a['excerpt']),'post_content'=>$content);if($existing)$post['ID']=$existing;$res=$existing?wp_update_post($post,true):wp_insert_post($post,true);if(is_wp_error($res))throw new Exception($a['key'].': '.$res->get_error_message());$id=(int)$res;wp_set_post_categories($id,array($guide,$cats[$a['topic']]),false);update_post_meta($id,'_emdo_authority_key',$a['key']);update_post_meta($id,'_emdo_priority_plan','38');update_post_meta($id,'_emdo_priority_order',(string)$a['priority']);update_post_meta($id,'_emdo_priority_batch','3');update_post_meta($id,'_en_US_post_title',wp_strip_all_tags($a['en_title']));update_post_meta($id,'_en_US_post_name',sanitize_title($a['en_slug']));update_post_meta($id,'_en_US_post_excerpt',wp_strip_all_tags($a['en_excerpt']));update_post_meta($id,'_en_US_post_content',$en);update_post_meta($id,'_en_US_ready','1');update_post_meta($id,'_en_US_published','1');update_post_meta($id,'_emdo_editorial_updated',gmdate('c'));$current=(int)get_post_thumbnail_id($id);$marked=(string)get_post_meta($id,'_emdo_uses_default_featured',true)==='1';if($new||$marked||$current<=0){update_post_meta($id,'_thumbnail_id',$default);update_post_meta($id,'_emdo_uses_default_featured','1');update_post_meta($id,'_emdo_editorial_image_approved_id',$default);delete_post_meta($id,'_emdo_editorial_image_approved_pexels_id');update_post_meta($id,'_emdo_editorial_cover_asset_id','emdo-blog-default-featured');update_post_meta($id,'_emdo_editorial_cover_brand_safe','1');update_post_meta($id,'_emdo_default_featured_hash',$default_hash);update_post_meta($id,'_emdo_default_featured_updated_at',gmdate('c'));}clean_post_cache($id);$rows[]=array('key'=>$a['key'],'priority'=>(int)$a['priority'],'id'=>$id,'status'=>get_post_status($id),'slug'=>get_post_field('post_name',$id),'en_slug'=>sanitize_title($a['en_slug']),'thumbnail_id'=>(int)get_post_thumbnail_id($id),'provisional'=>(string)get_post_meta($id,'_emdo_uses_default_featured',true),'words_es'=>$wes,'words_en'=>$wen,'min_es'=>(int)$a['min_es'],'min_en'=>(int)$a['min_en'],'topic'=>$a['topic'],'product_category'=>$product,'has_products_es'=>strpos($content,'[products')!==false,'has_products_en'=>strpos($en,'[products')!==false);
}
if(count($rows)!==5)throw new Exception('Publish count mismatch');usort($rows,function($a,$b){return $a['priority']<=>$b['priority'];});echo wp_json_encode(array('batch'=>'priority-03','default'=>$default,'posts'=>$rows),JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES|JSON_PRETTY_PRINT).PHP_EOL;
