<?php
/**
 * Publish the first cheese authority batch directly in production.
 * Ten Spanish posts + Falang en_US translations, category Quesos/Cheese.
 * Idempotent by slug and batch marker.
 */

if ( ! defined( 'ABSPATH' ) ) { exit; }

const EMDO_CHEESE_BATCH01_MARKER = '2026-09-01.cheese-01.v1';

$articles = array(
array(
'pos'=>1,
'title'=>'Queso Manchego DOP: qué es, cómo se elabora y cómo reconocer el auténtico',
'slug'=>'queso-manchego-dop-que-es-como-se-elabora-reconocer-autentico',
'en_title'=>'Manchego PDO cheese: what it is, how it is made and how to identify the real thing',
'en_slug'=>'manchego-pdo-cheese-what-it-is-how-made-how-identify-authentic',
'excerpt'=>'Guía completa del Queso Manchego DOP: leche, zona, maduración, elaboración, etiquetado y claves para distinguir un Manchego certificado de un queso similar.',
'en_excerpt'=>'Complete guide to Manchego PDO cheese: milk, area, ageing, production, labelling and how to distinguish certified Manchego from similar cheeses.',
'lead_es'=>'El nombre Manchego no describe simplemente un queso de oveja hecho en Castilla-La Mancha. La Denominación de Origen Protegida Queso Manchego define una materia prima concreta, una zona geográfica, unas condiciones de elaboración y maduración y un sistema de identificación que permite comprobar si una pieza está realmente amparada.',
'lead_en'=>'The name Manchego does not simply describe any sheep’s-milk cheese made in Castilla-La Mancha. The Manchego Protected Designation of Origin defines a specific raw material, geographical area, production and ageing rules, plus an identification system that lets buyers verify whether a cheese is genuinely certified.',
'facts_es'=>array(array('Leche','Exclusivamente leche de oveja de raza manchega.'),array('Tipo','Queso de pasta prensada.'),array('Maduración','Mínimo 30 días en piezas de hasta 1,5 kg y 60 días en formatos mayores; máximo 2 años según el pliego vigente.'),array('Clave de compra','Buscar la identificación oficial de la DOP, no solo la palabra “manchego”.')),
'facts_en'=>array(array('Milk','Exclusively milk from Manchega sheep.'),array('Style','Pressed-curd cheese.'),array('Ageing','At least 30 days for cheeses up to 1.5 kg and 60 days for larger formats; up to 2 years under the current specification.'),array('Buying key','Look for official PDO identification, not merely the word “Manchego”.')),
'sections_es'=>array(
array('Qué convierte a un queso en Queso Manchego DOP','La base está en el origen y en la trazabilidad. La leche debe proceder de ovejas de raza manchega y el queso debe elaborarse dentro de la zona delimitada por la denominación. El pliego vigente también fija parámetros de composición, formato, maduración y características del producto terminado. Por eso un buen queso de oveja de otra raza o de otra zona puede ser excelente, pero no es Queso Manchego DOP.\n\nEsta distinción es importante en internet, donde a veces “manchego” se utiliza de forma genérica para describir quesos de estilo parecido. Para una compra informada conviene separar el estilo sensorial de la certificación geográfica.'),
array('Cómo se elabora y qué cambia durante la maduración','El proceso parte de la coagulación de la leche, el corte de la cuajada, el moldeado y el prensado. Después llegan el salado y la maduración. Durante esta etapa se pierde humedad, la pasta se vuelve más firme y se desarrollan aromas y sabores más complejos. El tiempo no actúa solo: temperatura, humedad, composición de la leche, tamaño de la pieza y manejo de la quesería influyen en la evolución.\n\nEl pliego actual establece mínimos distintos según el peso y una maduración máxima de dos años. Esto ayuda a entender por qué “más curado” no significa automáticamente “mejor”: significa un perfil distinto, normalmente más concentrado y persistente.'),
array('Leche cruda o pasteurizada: ambas pueden existir dentro de la DOP','La DOP no debe confundirse con una única técnica de tratamiento de la leche. Puede encontrarse Queso Manchego elaborado con leche pasteurizada y también versiones artesanas elaboradas con leche cruda cuando cumplen las condiciones aplicables. La diferencia afecta al proceso y puede influir en la expresión aromática, pero no convierte por sí sola una pieza en superior.\n\nAl comparar dos Manchegos es más útil leer el conjunto: productor, leche, maduración, formato, conservación e identificación de la DOP. La etiqueta aporta más información que una sola palabra de marketing.'),
array('Cómo reconocer un Manchego auténtico','La forma más segura es comprobar los elementos oficiales de identificación de la denominación y la información obligatoria del envase. El Consejo Regulador utiliza sistemas de control que permiten individualizar el producto amparado. No basta con que una etiqueta muestre paisajes manchegos, ovejas o términos como “tradicional”.\n\nEn compra online, busca fotografías legibles de la etiqueta y una ficha que diga expresamente DOP Queso Manchego. Si la descripción solo habla de “queso manchego” sin mostrar certificación, conviene verificarlo antes de asumir que está protegido.'),
array('Qué perfil esperar y cómo elegir maduración','Un Manchego joven suele conservar una sensación más láctica y una textura más flexible. A medida que avanza la maduración, el queso tiende a ganar firmeza, intensidad, persistencia y notas más evolucionadas. No todas las piezas evolucionan exactamente igual, por lo que el productor y el afinado siguen teniendo un peso decisivo.\n\nPara aperitivos suaves o público amplio suele funcionar una maduración intermedia. Para una tabla con vinos estructurados, frutos secos o consumo en pequeñas porciones puede encajar mejor un curado o una pieza de maduración larga. Elegir bien depende del uso, no de perseguir la cifra de meses más alta.')
),
'sections_en'=>array(
array('What makes a cheese genuine Manchego PDO','The foundation is origin and traceability. Milk must come from Manchega sheep and the cheese must be made within the area defined by the designation. The current specification also sets composition, format, ageing and finished-product requirements. A very good sheep’s-milk cheese from another breed or region may be excellent, but it is not Manchego PDO.\n\nThis distinction matters online, where “Manchego” is sometimes used loosely for cheeses with a similar style. A careful buyer should separate sensory resemblance from geographical certification.'),
array('How Manchego is made and what ageing changes','Production includes coagulation, cutting the curd, moulding and pressing, followed by salting and maturation. During ageing the cheese loses moisture, its paste becomes firmer and flavour compounds become more concentrated and complex. Time is not the only factor: temperature, humidity, milk composition, cheese size and dairy management all shape the result.\n\nThe current PDO specification sets different minimum ageing periods according to weight and a maximum of two years. This is why “older” should not automatically be read as “better”; it means a different, usually more concentrated style.'),
array('Raw or pasteurised milk: both can exist within the PDO','Manchego PDO should not be confused with one single milk-treatment method. Certified cheese can be made from pasteurised milk and artisan versions may be made from raw milk when the applicable requirements are met. Milk treatment affects the production process and can influence aroma, but it does not by itself create a quality ranking.\n\nWhen comparing two Manchegos, read the complete picture: producer, milk, age, format, storage and PDO identification.'),
array('How to identify authentic Manchego','The safest approach is to check the designation’s official identification elements and the mandatory label information. The regulatory system provides controls that allow certified cheeses to be individually identified. Pictures of windmills, sheep or words such as “traditional” are not substitutes for certification.\n\nWhen buying online, look for clear label photographs and explicit wording such as Manchego PDO. If a product page uses the name without showing certification, verify before assuming that it is protected.'),
array('What flavour profile to expect and how to choose an age','Younger Manchego tends to retain a more lactic character and a more flexible texture. With longer ageing, the cheese generally becomes firmer, more intense and more persistent, with more developed savoury and nutty notes. Producer and maturation conditions still create meaningful differences between cheeses of similar age.\n\nFor an easy aperitif, a medium-aged cheese is often versatile. For a structured cheese board or pairing with fuller wines, a longer-aged Manchego may be more suitable. The best age is the one that fits the occasion.')
),
'practical_es'=>'Si quieres confirmar una pieza, empieza por la DOP y la etiqueta; después compara leche, maduración, productor, peso y formato. Esa secuencia evita pagar un sobreprecio solo por una apariencia o por el uso informal de la palabra Manchego.',
'practical_en'=>'To assess a cheese, start with PDO identification and the label, then compare milk, ageing, producer, weight and format. That sequence avoids paying a premium merely for appearance or loose use of the Manchego name.',
'sources'=>array('https://www.quesomanchego.es/wp-content/uploads/2025/03/Pliego-de-condiciones-25.pdf','https://www.mapa.gob.es/es/alimentacion/temas/calidad-diferenciada/dop-igp/detalle/queso_lacteo/dop_queso_manchego','https://www.quesomanchego.es/queso-manchego/')
),
array(
'pos'=>2,
'title'=>'Tipos de queso: guía completa según leche, maduración, pasta, corteza y elaboración',
'slug'=>'tipos-de-queso-guia-leche-maduracion-pasta-corteza-elaboracion',
'en_title'=>'Types of cheese: complete guide by milk, ageing, texture, rind and production method',
'en_slug'=>'types-of-cheese-guide-milk-ageing-texture-rind-production',
'excerpt'=>'Una guía para entender los principales tipos de queso y aprender a clasificarlos por leche, maduración, humedad, pasta, corteza y método de elaboración.',
'en_excerpt'=>'A guide to the main types of cheese and how to classify them by milk, ageing, moisture, paste, rind and production method.',
'lead_es'=>'Hablar de “tipos de queso” parece sencillo hasta que se intenta ordenar todo el universo quesero con una sola clasificación. Un queso puede ser de oveja, curado, de pasta prensada, de leche cruda y corteza natural al mismo tiempo. Por eso la forma más útil de entender los quesos es combinar varios ejes en lugar de buscar una lista cerrada.',
'lead_en'=>'Talking about “types of cheese” sounds simple until you try to organise the entire cheese world with a single classification. One cheese can simultaneously be sheep’s-milk, aged, pressed, raw-milk and naturally rinded. The most useful way to understand cheese is therefore to combine several classification axes rather than rely on one fixed list.',
'facts_es'=>array(array('Por leche','Vaca, oveja, cabra, búfala o mezclas.'),array('Por maduración','Fresco, tierno, semicurado, curado, viejo o añejo, entre otras categorías.'),array('Por pasta','Blanda, semidura, dura, prensada, azul, hilada, etc.'),array('Idea clave','Un mismo queso pertenece a varias categorías a la vez.')),
'facts_en'=>array(array('By milk','Cow, sheep, goat, buffalo or blends.'),array('By ageing','Fresh, young, semi-aged, aged and long-aged styles.'),array('By body','Soft, semi-hard, hard, pressed, blue, stretched-curd and more.'),array('Key idea','The same cheese belongs to several categories at once.')),
'sections_es'=>array(
array('Clasificar por el tipo de leche','La especie animal modifica la composición de la leche y condiciona textura, rendimiento y perfil aromático, aunque nunca determina por sí sola el sabor final. Los quesos de vaca abarcan desde estilos muy suaves hasta quesos intensos de larga maduración. Los de oveja suelen ofrecer una pasta rica y concentrada; los de cabra pueden mostrar perfiles muy diversos, desde frescos delicados hasta curados marcados.\n\nTambién existen quesos de mezcla. En ellos, la proporción de cada leche y el método de elaboración importan tanto como la lista de especies. Por eso “de tres leches” no es una categoría de calidad, sino una descripción de la materia prima.'),
array('Clasificar por maduración','La maduración transforma físicamente el queso. Al perder agua y avanzar la proteólisis y la lipólisis, cambian firmeza, elasticidad, aroma y persistencia. La normativa española utiliza denominaciones como tierno, semicurado, curado, viejo y añejo con tiempos mínimos que dependen también del peso de la pieza.\n\nEstas palabras ayudan, pero no hacen equivalentes todos los quesos con la misma edad. Un curado pequeño puede evolucionar más rápido que una rueda grande y dos tecnologías distintas pueden producir texturas muy diferentes en el mismo intervalo.'),
array('Clasificar por humedad y textura de la pasta','Los quesos frescos y blandos conservan más humedad y suelen ser más delicados. Los semiduros y duros presentan una estructura más firme y, a menudo, una vida útil mayor. La técnica de prensado, el tamaño del grano de cuajada y el desuerado influyen enormemente en esa estructura.\n\nDentro de esta clasificación aparecen familias muy reconocibles: pasta prensada, pasta blanda, quesos azules, pasta hilada o quesos lavados. No es una jerarquía: cada tecnología busca un comportamiento y un perfil sensorial diferentes.'),
array('La corteza también cuenta','La corteza puede ser natural, enmohecida, lavada, tratada o protegida con materiales autorizados según el tipo de queso. Cumple funciones tecnológicas y también influye en la maduración. En algunos estilos forma parte de la experiencia de consumo; en otros se retira.\n\nLa pregunta “¿se come la corteza?” no tiene una respuesta universal. Hay que distinguir entre cortezas desarrolladas como parte del queso y recubrimientos no destinados al consumo. La etiqueta y la información del productor son la referencia práctica.'),
array('Cómo usar esta clasificación para comprar mejor','En lugar de buscar “el mejor queso”, define primero el uso. Para fundir interesan propiedades distintas que para una tabla. Para una ensalada puede ser útil un fresco o un queso quebradizo; para rallar, uno duro y concentrado; para una tabla, combinar humedad, intensidad y leche crea más contraste que elegir diez quesos parecidos.\n\nLeer un queso por leche + maduración + pasta + corteza + productor proporciona mucha más información que fijarse solo en una palabra como “artesano”, “curado” o “premium”.')
),
'sections_en'=>array(
array('Classifying cheese by milk','Animal species influences milk composition and therefore texture, yield and aromatic potential, but it never determines flavour on its own. Cow’s-milk cheeses range from extremely mild fresh styles to powerful long-aged wheels. Sheep’s milk often produces a rich, concentrated body, while goat’s milk can range from delicate fresh cheese to assertive aged styles.\n\nMixed-milk cheeses form another broad group. The proportion of each milk and the cheesemaking method matter as much as the list of species, so “three-milk cheese” describes raw material rather than a quality level.'),
array('Classifying cheese by ageing','Ageing physically and chemically transforms cheese. As moisture decreases and proteins and fats break down, firmness, elasticity, aroma and persistence evolve. Spanish rules use optional terms equivalent to young, semi-aged, aged, old and extra-aged, with minimum periods that can also depend on cheese weight.\n\nAge labels are useful but do not make all cheeses of the same age equivalent. Size, moisture and technology can make two cheeses mature at very different rates.'),
array('Classifying by moisture and body','Fresh and soft cheeses retain more moisture and are generally more perishable. Semi-hard and hard cheeses have a firmer structure and often keep longer. Pressing, curd size and whey drainage all strongly influence that final body.\n\nThis axis includes familiar families such as pressed cheeses, bloomy soft cheeses, blue cheeses and stretched-curd cheeses. None is inherently better; each technology is designed to create a different texture and flavour profile.'),
array('Rind as part of the classification','A rind may be natural, mould-ripened, washed, treated or protected according to the cheese style. It has technological functions and can shape maturation. In some cheeses the rind is part of the intended eating experience; in others it is removed.\n\nThere is no universal answer to whether a rind should be eaten. Distinguish between edible rinds developed as part of the cheese and coatings that are not intended for consumption, and follow producer information.'),
array('Using classification to buy better cheese','Instead of searching for “the best cheese”, begin with the use. Melting requires different properties from a cheese board. A salad may benefit from a fresh or crumbly cheese, while grating works better with a firm, concentrated style. On a board, contrast in milk, moisture and intensity creates more interest than ten near-identical cheeses.\n\nReading cheese through milk + age + body + rind + producer gives far more useful information than focusing on one marketing word such as “artisan” or “premium”.')
),
'practical_es'=>'Cuando compares quesos online, intenta describir cada opción con cinco datos: leche, tratamiento de la leche, maduración, textura de la pasta y tipo de corteza. Con esa ficha mental es mucho más fácil anticipar el uso y el perfil que con el precio por kilo aislado.',
'practical_en'=>'When comparing cheese online, describe each option with five data points: milk, milk treatment, ageing, paste texture and rind type. That mental profile predicts use and style far better than price per kilo alone.',
'sources'=>array('https://www.boe.es/eli/es/rd/2006/09/29/1113','https://www.mapa.gob.es/es/alimentacion/temas/calidad-diferenciada/dop-igp')
),
array(
'pos'=>3,
'title'=>'Queso tierno, semicurado, curado, viejo y añejo: diferencias y cómo elegir',
'slug'=>'queso-tierno-semicurado-curado-viejo-anejo-diferencias',
'en_title'=>'Young, semi-aged, aged and long-aged cheese: differences and how to choose',
'en_slug'=>'young-semi-aged-aged-long-aged-cheese-differences-how-choose',
'excerpt'=>'Qué significan tierno, semicurado, curado, viejo y añejo en España, tiempos mínimos, cambios de textura y sabor y cómo elegir según el uso.',
'en_excerpt'=>'What young, semi-aged, aged and long-aged cheese terms mean in Spain, minimum ageing times, texture and flavour changes, and how to choose.',
'lead_es'=>'Tierno, semicurado, curado, viejo y añejo no son simplemente adjetivos comerciales. En España forman parte de una clasificación legal facultativa ligada a tiempos mínimos de maduración. Sin embargo, conocer los días no basta para predecir exactamente cómo sabrá un queso: peso, humedad, leche y tecnología modifican la velocidad y el resultado de la maduración.',
'lead_en'=>'Terms such as young, semi-aged, aged and extra-aged are not merely marketing adjectives in Spain. They correspond to optional legal ageing categories with minimum maturation periods. Yet the number of days alone cannot predict flavour: cheese weight, moisture, milk and technology all affect how quickly and in what way a cheese matures.',
'facts_es'=>array(array('Tierno','Mínimo 7 días.'),array('Semicurado','35 días si pesa más de 1,5 kg; 20 días si pesa 1,5 kg o menos.'),array('Curado','105 días en piezas mayores de 1,5 kg; 45 días en las pequeñas.'),array('Viejo / Añejo','Viejo: 180/100 días según peso. Añejo: mínimo 270 días.')),
'facts_en'=>array(array('Young','At least 7 days under the Spanish optional classification.'),array('Semi-aged','35 days above 1.5 kg; 20 days at 1.5 kg or below.'),array('Aged','105 days above 1.5 kg; 45 days for smaller cheeses.'),array('Old / extra-aged','Old: 180/100 days depending on weight. Extra-aged: at least 270 days.')),
'sections_es'=>array(
array('Qué dice realmente la normativa','El Real Decreto 1113/2006 diferencia queso fresco, queso blanco pasteurizado y queso madurado. Dentro de los madurados permite utilizar los calificativos tierno, semicurado, curado, viejo y añejo cuando se alcanzan determinados mínimos. En varias categorías el tiempo cambia según la pieza pese más o menos de 1,5 kg.\n\nEste detalle de peso explica por qué no conviene convertir las palabras en una escala universal de meses. La clasificación legal marca mínimos de salida de fábrica; no describe por completo la tecnología ni el estado sensorial de cada queso.'),
array('Qué cambia en textura al madurar','Durante la maduración se pierde humedad y cambian las proteínas. En términos generales, un queso pasa de una pasta más elástica y húmeda a una estructura más firme, friable o granulosa, aunque el resultado depende mucho de la familia de queso. También pueden aparecer cristales y una sensación más quebradiza en piezas largas.\n\nLa corteza suele ganar protagonismo y la diferencia entre centro y periferia puede hacerse más visible. Por eso el corte de una cuña aporta pistas útiles: color, ojos, humedad y textura cuentan una historia que el nombre de la categoría no resume por sí solo.'),
array('Qué cambia en aroma y sabor','Los quesos jóvenes suelen mostrar notas lácticas directas y sabores menos persistentes. Con la maduración aumentan los compuestos derivados de la transformación de proteínas y grasas, y pueden aparecer notas de frutos secos, caldo, mantequilla evolucionada, especias o sensaciones más picantes, según el tipo.\n\nIntensidad no equivale necesariamente a calidad. Un tierno bien elaborado puede ser excelente y un añejo mal conservado puede resultar desequilibrado. La maduración debe leerse como estilo, no como podio.'),
array('Qué maduración elegir según el uso','Para bocadillos, cocina cotidiana o consumidores que prefieren sabores suaves, tierno y semicurado suelen ser versátiles. Un curado aporta más carácter sin llegar siempre al impacto de las maduraciones largas. Viejo y añejo suelen funcionar mejor en porciones pequeñas, tablas, rallado o maridajes donde se busca persistencia.\n\nTambién importa cuánto queso vas a consumir. Una pieza muy intensa puede cundir más en una tabla porque se sirven porciones menores, mientras que un semicurado puede ser más fácil para consumo diario.'),
array('Errores habituales al comparar maduraciones','El primer error es comparar quesos de tecnologías distintas solo por los meses. El segundo es asumir que más seco significa automáticamente más curado: una mala conservación también puede secar un queso. El tercero es ignorar el tamaño y la leche.\n\nLa mejor comparación es dentro de una misma familia o productor, donde el cambio de maduración se observa sobre una base más parecida. Ahí sí resulta especialmente útil probar un semicurado y un curado de la misma casa para entender qué aporta el tiempo.')
),
'sections_en'=>array(
array('What Spanish regulations actually say','Royal Decree 1113/2006 distinguishes fresh cheese, pasteurised white cheese and ripened cheese. Within ripened cheese it allows optional ageing descriptors that correspond to minimum maturation periods. For several categories the minimum changes depending on whether the cheese weighs more or less than 1.5 kg.\n\nThat weight distinction is why these terms should not be reduced to one universal month scale. They set minimum legal thresholds at release rather than describing the entire cheesemaking technology or sensory condition.'),
array('How texture changes during ageing','As cheese matures it generally loses moisture and its proteins change. A flexible, moist paste can become firmer, more crumbly or granular, although the exact direction depends on cheese family. Long ageing may also produce crystals and a more brittle bite.\n\nThe rind can become more influential and differences between the centre and outer paste may increase. Looking at a cut wedge—colour, openings, moisture and structure—therefore tells you more than the ageing word alone.'),
array('How aroma and flavour evolve','Young cheeses tend to show direct lactic notes and shorter persistence. As maturation progresses, the breakdown of proteins and fats can generate nutty, brothy, buttery, spicy or more piquant notes depending on style.\n\nIntensity is not a synonym for quality. A beautifully made young cheese can be excellent, while a badly stored long-aged cheese can be unbalanced. Age is best understood as style rather than hierarchy.'),
array('Choosing an age for the occasion','For sandwiches, everyday eating and people who prefer gentler flavours, young and semi-aged cheeses are usually versatile. Aged cheese brings more character, while very long-aged styles often work best in smaller portions, structured boards, grating or pairings where persistence is desirable.\n\nConsumption rate matters too. An intense cheese can go further on a board because portions are smaller, whereas semi-aged cheese may be easier for daily use.'),
array('Common mistakes when comparing ageing','The first mistake is comparing completely different cheese technologies only by months. The second is assuming that dryness automatically proves long ageing, because poor storage can also dry cheese. The third is ignoring weight and milk type.\n\nThe clearest comparison is usually within one producer or cheese family, where changing age can be tasted against a similar base recipe.')
),
'practical_es'=>'Si dudas entre dos maduraciones del mismo queso, piensa en intensidad, textura y ritmo de consumo. Para uso diario suele compensar una opción intermedia; para una tabla o consumo pausado, una maduración más larga puede aportar más contraste.',
'practical_en'=>'When choosing between two ages of the same cheese, think about intensity, texture and how quickly you will eat it. A middle age often suits everyday use; longer maturation can add contrast to a board or slower consumption.',
'sources'=>array('https://www.boe.es/eli/es/rd/2006/09/29/1113')
),
array(
'pos'=>4,
'title'=>'Queso de oveja, cabra o vaca: qué cambia y cómo elegir',
'slug'=>'queso-oveja-cabra-vaca-diferencias-como-elegir',
'en_title'=>'Sheep, goat or cow cheese: what changes and how to choose',
'en_slug'=>'sheep-goat-cow-cheese-differences-how-choose',
'excerpt'=>'Diferencias entre quesos de oveja, cabra y vaca: composición de la leche, textura, intensidad, maduración y usos para elegir mejor.',
'en_excerpt'=>'Differences between sheep, goat and cow cheeses: milk composition, texture, intensity, ageing and practical uses to help you choose.',
'lead_es'=>'La especie animal importa, pero no funciona como una receta de sabor. Un queso de cabra puede ser fresco y delicado o largo e intenso; uno de vaca puede ser mantecoso o extremadamente potente; uno de oveja puede ir de cremoso a duro y picante. La leche crea un punto de partida y la elaboración decide gran parte del resultado.',
'lead_en'=>'Animal species matters, but it does not work like a fixed flavour recipe. Goat cheese can be fresh and delicate or long-aged and assertive; cow’s milk can produce buttery or extremely powerful cheeses; sheep’s milk can range from creamy to hard and piquant. Milk creates the starting point, while cheesemaking determines much of the result.',
'facts_es'=>array(array('Vaca','Gran diversidad de estilos y perfiles, desde frescos hasta largas maduraciones.'),array('Oveja','Leche rica en sólidos, muy adecuada para quesos de pasta concentrada y maduración.'),array('Cabra','Amplísimo rango, con frescos delicados y curados intensos.'),array('Mezcla','Combina leches en proporciones variables; no es una categoría inferior.')),
'facts_en'=>array(array('Cow','Extremely broad range from fresh styles to long-aged cheeses.'),array('Sheep','Milk rich in solids, well suited to concentrated, aged cheeses.'),array('Goat','Very broad spectrum from delicate fresh cheese to assertive aged styles.'),array('Mixed milk','Combines species in varying proportions; not an inferior category.')),
'sections_es'=>array(
array('La leche cambia la materia prima, no dicta el queso final','Las leches de distintas especies tienen proporciones diferentes de grasa, proteína y otros componentes, y sus glóbulos grasos y proteínas presentan particularidades que influyen en coagulación y textura. En quesería, esas diferencias afectan al rendimiento y a la forma en que se diseña el proceso.\n\nSin embargo, fermentos, cuajo, corte de cuajada, prensado, salado, mohos y maduración pueden modificar radicalmente el resultado. Por eso es más preciso hablar de tendencias que de reglas absolutas.'),
array('Quesos de oveja: concentración y capacidad de maduración','La leche de oveja suele aportar una elevada concentración de sólidos, algo muy valioso para quesos que buscan cuerpo y rendimiento. En España está detrás de estilos emblemáticos como el Manchego DOP. En maduraciones medias y largas puede ofrecer texturas densas y sabores muy persistentes.\n\nEso no significa que todos los quesos de oveja sean fuertes. La edad y la tecnología siguen mandando. Un queso joven de oveja puede resultar mucho más accesible que un curado de vaca de corteza lavada.'),
array('Quesos de cabra: mucho más que un sabor “caprino”','El estereotipo de que todo queso de cabra sabe igual es poco útil. Los frescos pueden ser blancos, húmedos y de acidez limpia; en maduración pueden desarrollar cortezas, texturas y perfiles muy complejos. La intensidad depende de la elaboración y del tiempo, además de la leche.\n\nPara iniciarse, un rulo fresco o un semicurado de perfil limpio suele ser más amable. Para una tabla con contraste, un cabra más maduro puede aportar una dimensión distinta a quesos de oveja y vaca.'),
array('Quesos de vaca: la familia más amplia','La enorme diversidad internacional de quesos de vaca demuestra que la especie no predetermina intensidad. Con esta leche se elaboran pastas cocidas, blandas, azules, cortezas lavadas, frescos, quesos de montaña y largas maduraciones.\n\nEn una compra, la palabra “vaca” debería ser el comienzo de la descripción, no el final. Conviene añadir maduración, tipo de pasta y corteza para anticipar de verdad qué vas a encontrar.'),
array('Cómo elegir entre oveja, cabra y vaca','Si buscas una tabla equilibrada, combinar especies es una forma sencilla de crear contraste, siempre que también varíen texturas y maduraciones. Para cocinar, prioriza comportamiento: capacidad de fundido, humedad, salinidad y potencia. Para comer solo, manda el gusto personal y la intensidad deseada.\n\nLos quesos de mezcla son especialmente interesantes cuando el productor utiliza cada leche para construir equilibrio. No deben interpretarse como un “resto” de varias leches, sino como una formulación con identidad propia cuando están bien elaborados.')
),
'sections_en'=>array(
array('Milk changes the raw material but does not dictate the final cheese','Milks from different species vary in fat, protein and other components, and their fat globules and proteins behave differently during cheesemaking. These differences influence coagulation, yield and texture.\n\nYet cultures, rennet, curd cutting, pressing, salting, moulds and ageing can transform the result dramatically. It is therefore more accurate to speak in tendencies rather than absolute flavour rules.'),
array('Sheep’s-milk cheese: concentration and ageing potential','Sheep’s milk is generally rich in solids, which is valuable for cheeses designed to develop body and concentration. In Spain it underpins major styles such as Manchego PDO. Medium and long ageing can produce dense textures and persistent flavours.\n\nThat does not mean every sheep’s cheese is strong. Age and technology remain decisive; a young sheep’s cheese can be gentler than a powerful washed-rind cow’s cheese.'),
array('Goat cheese: far more than one “goaty” flavour','The idea that all goat cheese tastes the same is not useful. Fresh examples can be white, moist and cleanly acidic, while maturation can create complex rinds, textures and aromas. Intensity depends on method and age as much as on milk.\n\nFor beginners, a fresh log or clean semi-aged cheese is accessible. On a board, a more mature goat cheese can provide a distinctive contrast with sheep and cow styles.'),
array('Cow’s-milk cheese: the broadest family','The extraordinary global diversity of cow’s-milk cheese proves that species does not predetermine intensity. Cow’s milk can make cooked-curd, soft, blue, washed-rind, fresh, alpine and very long-aged cheeses.\n\nOn a product page, “cow’s milk” should be the beginning of the description, not the end. Add age, paste type and rind to predict the eating experience.'),
array('How to choose between sheep, goat and cow','For a balanced board, mixing species is an easy route to contrast, especially when textures and ages differ too. For cooking, prioritise behaviour: melting, moisture, salt and strength. For eating on its own, personal preference and desired intensity matter most.\n\nMixed-milk cheeses can be particularly interesting when a producer uses each milk deliberately to build balance rather than simply combining leftovers.')
),
'practical_es'=>'No compres solo por la especie. Para comparar bien, añade siempre dos preguntas: ¿qué maduración tiene? y ¿qué tipo de pasta/corteza es? Esas tres capas juntas predicen mucho mejor el queso que “oveja, cabra o vaca” por separado.',
'practical_en'=>'Do not buy by species alone. Always add two questions: how aged is it, and what paste/rind style is it? Those three layers predict the cheese much better than “sheep, goat or cow” on its own.',
'sources'=>array('https://www.boe.es/eli/es/rd/2006/09/29/1113','https://www.mapa.gob.es/es/ganaderia/temas/zootecnia/razas-ganaderas/razas/catalogo-razas/ovino/manchega-negra/usos_sistema')
),
array(
'pos'=>5,
'title'=>'Queso de leche cruda o pasteurizada: diferencias, elaboración, sabor y seguridad',
'slug'=>'queso-leche-cruda-o-pasteurizada-diferencias-sabor-seguridad',
'en_title'=>'Raw-milk vs pasteurised-milk cheese: production, flavour and safety differences',
'en_slug'=>'raw-milk-vs-pasteurised-cheese-production-flavour-safety',
'excerpt'=>'Qué cambia entre un queso de leche cruda y uno de leche pasteurizada, cómo funciona la pasteurización y por qué el tratamiento térmico no define por sí solo la calidad.',
'en_excerpt'=>'What changes between raw-milk and pasteurised-milk cheese, how pasteurisation works and why heat treatment alone does not define quality.',
'lead_es'=>'“Leche cruda” y “leche pasteurizada” describen cómo se ha tratado la leche antes de elaborar el queso. Son datos relevantes, pero se utilizan mal cuando se convierten en una clasificación automática de calidad. Hay grandes quesos en ambos grupos y el resultado depende de higiene, materia prima, fermentos, tecnología, maduración y conservación.',
'lead_en'=>'“Raw milk” and “pasteurised milk” describe how milk was treated before cheesemaking. They are meaningful facts, but they become misleading when turned into an automatic quality ranking. Excellent cheeses exist in both groups, and the final result depends on hygiene, raw material, cultures, technology, ageing and storage.',
'facts_es'=>array(array('Leche cruda','No ha recibido un tratamiento térmico equivalente a pasteurización antes de elaborar el queso.'),array('Pasteurización','La normativa europea contempla combinaciones como 72 °C durante 15 s o 63 °C durante 30 min, o tratamientos equivalentes.'),array('Calidad','Ninguno de los dos métodos garantiza por sí solo un queso mejor.'),array('Compra','Leer etiqueta, productor, maduración y conservación.')),
'facts_en'=>array(array('Raw milk','Milk that has not received a heat treatment equivalent to pasteurisation before cheesemaking.'),array('Pasteurisation','EU rules include combinations such as 72 °C for 15 s or 63 °C for 30 min, or equivalent treatments.'),array('Quality','Neither method automatically guarantees a better cheese.'),array('Buying','Read label, producer, ageing and storage information.')),
'sections_es'=>array(
array('Qué significa pasteurizar la leche','La pasteurización aplica una combinación controlada de tiempo y temperatura para reducir microorganismos patógenos. La normativa europea establece tratamientos de referencia y permite equivalentes que alcancen el efecto requerido. No es lo mismo que esterilizar: el objetivo tecnológico y la intensidad son diferentes.\n\nEn una quesería, este paso estandariza parte de la microbiota inicial. Después, los cultivos, el cuajo y el proceso de elaboración vuelven a construir un ecosistema que evolucionará durante la maduración.'),
array('Qué significa elaborar con leche cruda','En un queso de leche cruda, la leche no ha recibido antes una pasteurización equivalente. Esto conserva una microbiota inicial más diversa y hace especialmente importantes la calidad higiénica de la leche, el control del proceso y el cumplimiento de criterios microbiológicos. La normativa europea establece controles específicos para quesos elaborados con leche cruda.\n\n“Cruda” no significa “sin control”. En producción profesional el queso sigue sometido a requisitos sanitarios, trazabilidad y condiciones de elaboración.'),
array('¿La leche cruda sabe siempre más?','No. Puede favorecer perfiles complejos porque conserva más diversidad microbiana y enzimática, pero el sabor final depende de muchos factores. Un pasteurizado bien elaborado y afinado puede ser extraordinariamente complejo, mientras que una mala leche cruda no se convierte en buen queso por no calentarse.\n\nLa comparación útil debe hacerse entre productos concretos, idealmente del mismo estilo. Si todo lo demás cambia a la vez—leche, productor, edad y corteza—atribuir las diferencias solo a la pasteurización es simplificar demasiado.'),
array('Seguridad alimentaria y maduración','La seguridad no depende de una única palabra en la etiqueta. Importan la higiene de la leche, el proceso, la actividad de agua, el pH, la sal, la maduración, el frío y la ausencia de contaminación posterior. La UE fija criterios microbiológicos distintos para determinadas categorías de queso y obliga a los operadores a aplicar controles.\n\nPara el consumidor, la regla práctica es respetar conservación y fecha del producto y seguir las recomendaciones oficiales aplicables a su situación personal.'),
array('Cómo elegir entre leche cruda y pasteurizada','Si te interesa explorar estilos tradicionales, un queso de leche cruda puede aportar una experiencia muy ligada a productor y territorio. Si buscas regularidad o determinados estilos frescos, la leche pasteurizada es habitual y perfectamente compatible con alta calidad.\n\nNo uses este dato como filtro único. Lee también especie de leche, maduración, DOP, tipo de pasta, corteza, productor y condiciones de conservación. Esa combinación explica mucho más del queso real.')
),
'sections_en'=>array(
array('What pasteurising milk means','Pasteurisation uses a controlled time-and-temperature combination to reduce pathogenic microorganisms. EU rules establish reference treatments and allow equivalent processes that achieve the required effect. It is not the same as sterilisation; the technological purpose and intensity are different.\n\nIn a dairy, pasteurisation standardises part of the starting microbiota. Cultures, rennet and cheesemaking then build a new microbial and biochemical environment that continues to evolve during maturation.'),
array('What raw-milk cheesemaking means','In raw-milk cheese, the milk has not received an equivalent pasteurisation step before cheesemaking. This preserves a more diverse initial microbiota and makes milk hygiene, process control and microbiological compliance especially important. EU legislation establishes specific microbiological criteria for raw-milk cheeses.\n\n“Raw” does not mean “uncontrolled”. Professional production remains subject to food-safety requirements, traceability and process controls.'),
array('Does raw milk always taste stronger or better?','No. Raw milk can support complex profiles because more native microbial and enzymatic diversity remains, but final flavour depends on many factors. A well-made pasteurised cheese can be highly complex, while poor raw milk does not become great cheese merely because it was not heated.\n\nThe useful comparison is between specific cheeses, ideally within one style. If producer, milk species, age and rind all change, attributing flavour differences only to pasteurisation is too simplistic.'),
array('Food safety and ageing','Safety never depends on one label word alone. Milk hygiene, processing, water activity, pH, salt, ageing, refrigeration and protection from later contamination all matter. EU rules set microbiological criteria for specific cheese categories and require food businesses to maintain controls.\n\nFor consumers, the practical rule is to respect storage instructions and use-by information and follow any official advice relevant to their own circumstances.'),
array('How to choose between raw and pasteurised cheese','If you enjoy exploring traditional styles, a raw-milk cheese can offer a strong connection to producer and place. If you value consistency or are buying fresh styles, pasteurised milk is common and fully compatible with high quality.\n\nDo not use milk treatment as the only filter. Species, age, PDO, paste, rind, producer and storage together explain much more about the cheese.')
),
'practical_es'=>'Usa “leche cruda/pasteurizada” como un dato de elaboración, no como una nota de calidad. Si quieres comparar de verdad, busca dos quesos de estilo y maduración parecidos y observa cómo cambia el perfil.',
'practical_en'=>'Treat “raw/pasteurised” as a production fact, not a quality score. For a meaningful comparison, taste cheeses of similar style and age and then observe how the profile differs.',
'sources'=>array('https://eur-lex.europa.eu/legal-content/EN/TXT/?uri=CELEX:02004R0853-20240509','https://eur-lex.europa.eu/legal-content/EN/ALL/?print=true&uri=CELEX:32005R2073','https://www.boe.es/eli/es/rd/2006/09/29/1113')
),
array(
'pos'=>6,
'title'=>'Cómo conservar queso correctamente: nevera, envoltorio, temperatura y errores habituales',
'slug'=>'como-conservar-queso-correctamente-nevera-envoltorio-temperatura',
'en_title'=>'How to store cheese properly: fridge, wrapping, temperature and common mistakes',
'en_slug'=>'how-to-store-cheese-properly-fridge-wrapping-temperature',
'excerpt'=>'Guía práctica para conservar queso abierto o en cuña sin resecarlo ni favorecer humedad excesiva: nevera, envoltorio, recipientes y servicio.',
'en_excerpt'=>'Practical guide to storing opened cheese or wedges without drying them out or trapping excess moisture: fridge, wrapping, containers and serving.',
'lead_es'=>'Conservar queso consiste en equilibrar dos problemas opuestos: que pierda demasiada humedad y se reseque, o que quede atrapado en un ambiente excesivamente húmedo que favorezca deterioro superficial. El punto de equilibrio cambia con un fresco, un blando, un azul o un curado, por lo que no existe un único envoltorio perfecto para todos.',
'lead_en'=>'Storing cheese means balancing two opposite problems: excessive moisture loss that dries the cheese, and too much trapped humidity that encourages surface spoilage. The right balance differs for fresh, soft, blue and hard cheeses, so there is no single perfect wrapping method for every style.',
'facts_es'=>array(array('Frío','Los quesos que requieren refrigeración deben mantenerse en nevera siguiendo su etiqueta.'),array('Humedad','Evitar tanto el resecado como la condensación persistente.'),array('Corte','Proteger bien la superficie cortada.'),array('Servicio','Sacar solo la cantidad que se va a consumir y volver a refrigerar el resto.')),
'facts_en'=>array(array('Cold','Cheeses requiring refrigeration should stay refrigerated according to label instructions.'),array('Humidity','Avoid both excessive drying and persistent condensation.'),array('Cut surface','Protect the exposed cut face carefully.'),array('Serving','Take out only what you plan to eat and return the remainder to refrigeration.')),
'sections_es'=>array(
array('Por qué el queso se estropea o se reseca en la nevera','La nevera ralentiza el crecimiento microbiano, pero también es un ambiente que puede secar una cuña si queda expuesta. A la vez, un envoltorio completamente estanco puede atrapar condensación en determinados quesos. El objetivo es limitar el intercambio de aire sin crear una cámara húmeda permanente.\n\nLos quesos frescos y blandos son más sensibles por su mayor humedad. Los curados toleran mejor pequeñas variaciones, pero pueden perder aroma y elasticidad si pasan semanas abiertos y mal protegidos.'),
array('Cómo envolver una cuña abierta','La prioridad es cubrir la cara de corte y reducir el contacto con aire. Papel específico para queso o sistemas que permitan una protección ajustada suelen funcionar bien; en casa también puede combinarse un envoltorio limpio con un recipiente, vigilando que no se acumule agua.\n\nSi cambias el envoltorio cuando está húmedo o sucio, reduces olores y contaminación cruzada. Lo importante no es una “regla de papel” universal, sino mantener una superficie limpia, protegida y sin condensación excesiva.'),
array('Dónde colocarlo dentro de la nevera','Evita zonas sometidas a cambios frecuentes de temperatura, como una puerta muy utilizada. Un cajón o área relativamente estable ayuda a mantener condiciones más constantes y además protege el queso de olores intensos de otros alimentos.\n\nNo todos los frigoríficos tienen la misma humedad, así que conviene observar el producto. Si la cuña se cuartea, está perdiendo demasiada humedad; si el envase permanece mojado, necesita mejor gestión de condensación.'),
array('Piezas enteras, cuñas, rallado y queso fresco','Una pieza entera suele evolucionar más lentamente que una cuña porque tiene menos superficie cortada expuesta. El queso rallado o loncheado presenta mucha más superficie y por tanto se deteriora más rápido. Los frescos deben tratarse como productos especialmente perecederos y conservarse exactamente como indique el fabricante.\n\nComprar un formato acorde al ritmo de consumo suele ser más importante que buscar trucos para mantener durante semanas una cantidad demasiado grande.'),
array('Atemperar para servir sin comprometer el resto','Muchos quesos expresan mejor aroma y textura cuando no están recién salidos del frío, pero eso no significa dejar toda la pieza horas fuera repetidamente. Corta la porción que vas a consumir y deja que esa cantidad pierda parte del frío mientras el resto permanece protegido en la nevera.\n\nEste hábito mejora el servicio y reduce ciclos innecesarios de calentamiento y enfriamiento de la pieza completa.')
),
'sections_en'=>array(
array('Why cheese dries out or spoils in the fridge','Refrigeration slows microbial growth, but a fridge can also dry an exposed wedge. At the opposite extreme, completely airtight wrapping can trap condensation around some cheeses. The aim is to limit air exchange without creating a permanently wet micro-environment.\n\nFresh and soft cheeses are more sensitive because they contain more moisture. Hard aged cheeses tolerate variation better but can still lose aroma and texture after weeks of poor storage.'),
array('How to wrap an opened wedge','Protect the cut face and reduce direct air contact. Cheese paper or systems that provide close protection while managing moisture work well; at home, clean wrapping combined with a container can also work if condensation is monitored.\n\nChanging damp or dirty wrapping reduces odours and cross-contamination. The practical goal is a clean, protected surface without persistent moisture.'),
array('Where to keep cheese in the refrigerator','Avoid areas with frequent temperature swings such as a heavily used door. A relatively stable drawer or shelf can provide more consistent conditions and also shield cheese from strong food odours.\n\nFridges differ in humidity, so observe the cheese. Cracking and hardening indicate excessive drying, while a constantly wet wrapper suggests poor condensation control.'),
array('Whole cheeses, wedges, grated cheese and fresh cheese','A whole cheese usually changes more slowly than a wedge because less cut surface is exposed. Grated and sliced cheese has far more surface area and generally deteriorates faster. Fresh cheese should be treated as highly perishable and stored exactly as the manufacturer instructs.\n\nBuying a format that matches your consumption rate is often more effective than trying to preserve an oversized amount for weeks.'),
array('Bringing cheese to serving temperature without warming the whole piece','Many cheeses show better aroma and texture once the chill has softened, but that does not mean repeatedly leaving the whole cheese out for hours. Cut the amount you plan to serve and let only that portion warm slightly while the rest stays wrapped and refrigerated.\n\nThis improves eating quality and reduces unnecessary warming and cooling cycles for the main piece.')
),
'practical_es'=>'Compra formatos que puedas terminar en un plazo razonable. Una cuña bien envuelta y estable en frío suele conservarse mejor que una pieza enorme que se abre, se calienta y se vuelve a guardar muchas veces.',
'practical_en'=>'Buy formats you can finish at a reasonable pace. A well-wrapped wedge kept at a stable cold temperature usually stores better than an oversized piece repeatedly opened, warmed and returned to the fridge.',
'sources'=>array('https://www.fsis.usda.gov/food-safety/safe-food-handling-and-preparation/emergencies/keep-your-food-safe-during-emergencies','https://www.fsis.usda.gov/food-safety/safe-food-handling-and-preparation/food-safety-basics/molds-food-are-they-dangerous')
),
array(
'pos'=>7,
'title'=>'¿Se puede congelar el queso? Qué tipos lo toleran mejor y cómo hacerlo',
'slug'=>'se-puede-congelar-queso-tipos-como-hacerlo',
'en_title'=>'Can you freeze cheese? Which types freeze best and how to do it',
'en_slug'=>'can-you-freeze-cheese-which-types-freeze-best-how',
'excerpt'=>'Qué ocurre al congelar queso, qué tipos mantienen mejor su calidad, cuáles cambian más de textura y cómo congelar porciones útiles.',
'en_excerpt'=>'What freezing does to cheese, which styles retain quality best, which change texture most and how to freeze useful portions.',
'lead_es'=>'Sí, muchos quesos pueden congelarse, pero “se puede” no significa “quedará igual”. La congelación es sobre todo una herramienta para evitar desperdicio. Los quesos duros y los que después se usarán para cocinar suelen tolerarla mejor; en quesos blandos o muy húmedos el cambio de textura puede ser mucho más evidente.',
'lead_en'=>'Yes, many cheeses can be frozen, but “can be frozen” does not mean “will be unchanged”. Freezing is primarily a waste-reduction tool. Hard cheeses and cheeses destined for cooking generally tolerate it better, while soft or high-moisture cheeses can show much more obvious texture changes.',
'facts_es'=>array(array('Mejor comportamiento','Quesos duros, porciones para rallar o cocinar.'),array('Más cambio','Quesos blandos y semiblandos pueden perder textura.'),array('Clave','Congelar en porciones pequeñas y bien protegidas.'),array('Descongelación','Preferiblemente controlada en refrigeración.')),
'facts_en'=>array(array('Best performance','Hard cheeses and portions intended for grating or cooking.'),array('More change','Soft and semi-soft cheeses can lose texture.'),array('Key','Freeze in small, well-protected portions.'),array('Thawing','Preferably thaw under refrigeration.')),
'sections_es'=>array(
array('Qué le ocurre al queso al congelarse','El agua presente en la matriz del queso forma cristales de hielo. Al descongelar, parte de esa estructura no vuelve exactamente a su estado anterior, por lo que puede aparecer una pasta más quebradiza, arenosa o con separación de humedad. Cuanto más agua libre contiene el queso, más visible puede ser el cambio.\n\nLa congelación ralentiza enormemente procesos de deterioro, pero no mejora un queso que ya estaba pasado ni recupera aromas perdidos.'),
array('Qué quesos suelen congelar mejor','Los quesos duros y semiduros tienden a soportar mejor la congelación desde el punto de vista práctico, especialmente si después se rallan, funden o incorporan a recetas. Incluso cuando pierden algo de elasticidad, esa diferencia puede pasar desapercibida en cocina.\n\nEl queso ya rallado también puede ser cómodo para congelar en pequeñas cantidades, siempre que se proteja bien del aire y se eviten grandes bloques apelmazados.'),
array('Qué quesos cambian más','Los quesos frescos, blandos y de alta humedad son más propensos a perder una textura agradable al descongelar. Un queso cremoso puede separar agua, y una pasta blanda puede volverse granulosa. Esto no significa necesariamente que sea inseguro si se ha manejado correctamente, sino que la calidad sensorial puede caer mucho.\n\nSi el objetivo es comerlo solo, conviene evitar congelar un queso delicado que aprecias por su textura original.'),
array('Cómo congelar queso con sentido práctico','Divide antes de congelar. Porciones pequeñas permiten descongelar solo lo que necesitas y reducen el número de ciclos. Envuelve bien para limitar deshidratación y olores del congelador, etiqueta la fecha y piensa en el uso futuro: cuña para cocinar, dados para gratinar o rallado para recetas.\n\nCongelar una rueda grande entera suele ser menos práctico porque obliga a descongelar mucha cantidad de golpe y aumenta el riesgo de desperdicio posterior.'),
array('Cómo descongelarlo y aprovecharlo','La descongelación en nevera permite un cambio de temperatura gradual. Una vez descongelado, evalúa textura y olor y úsalo pronto. Si ha quedado más quebradizo, destínalo a gratinados, salsas, rellenos o rallado en lugar de exigirle la textura de una cuña recién cortada.\n\nLa mejor congelación es la que tiene un plan de uso. Congelar “por si acaso” sin porcionar ni etiquetar suele terminar en queso olvidado.')
),
'sections_en'=>array(
array('What freezing does to cheese','Water in the cheese matrix forms ice crystals. When thawed, the structure does not always return to its original state, so the paste may become more crumbly, grainy or prone to moisture separation. The more free water a cheese contains, the more obvious the change can be.\n\nFreezing slows deterioration dramatically, but it cannot improve cheese that was already stale or restore lost aromas.'),
array('Which cheeses usually freeze best','Hard and semi-hard cheeses tend to tolerate freezing better in practical terms, especially when they will later be grated, melted or cooked. Even if elasticity decreases, that difference may be barely noticeable in a recipe.\n\nPre-grated cheese can also be convenient to freeze in small amounts, provided it is well protected from air and not frozen as one huge compact block.'),
array('Which cheeses change the most','Fresh, soft and high-moisture cheeses are more likely to lose an attractive texture after thawing. Creamy cheese can separate water and a soft paste can become grainy. This does not automatically mean the cheese is unsafe when handled correctly; it means sensory quality can decline substantially.\n\nIf you plan to eat the cheese on its own, avoid freezing a delicate style whose main appeal is its original texture.'),
array('How to freeze cheese sensibly','Portion before freezing. Small packs let you thaw only what you need and reduce repeated temperature cycles. Wrap tightly to limit dehydration and freezer odours, label the date and decide the future use in advance: wedge for cooking, cubes for gratins or grated cheese for recipes.\n\nFreezing a very large wheel is usually less practical because it forces you to thaw too much at once.'),
array('How to thaw and use it well','Thawing in the refrigerator allows a gradual temperature change. Once thawed, assess texture and smell and use the cheese promptly. If it has become more crumbly, redirect it to gratins, sauces, fillings or grating instead of expecting the texture of a freshly cut wedge.\n\nThe best freezing strategy begins with a use plan; unlabelled “just in case” cheese often becomes forgotten cheese.')
),
'practical_es'=>'Congela queso para resolver un excedente, no como método estándar para almacenar piezas de calidad durante meses. Porcionar antes y decidir el uso posterior marca más diferencia que cualquier truco.',
'practical_en'=>'Freeze cheese to manage surplus rather than as the default way to store high-quality cheese for months. Portioning first and deciding how you will use it later matters more than any trick.',
'sources'=>array('https://www.fsis.usda.gov/food-safety/safe-food-handling-and-preparation/emergencies/a-consumers-guide-food-safety-severe','https://www.fsis.usda.gov/food-safety/safe-food-handling-and-preparation/emergencies/keep-your-food-safe-during-emergencies')
),
array(
'pos'=>8,
'title'=>'Cómo cortar y servir queso: temperatura, cuchillos, cortes y presentación',
'slug'=>'como-cortar-servir-queso-temperatura-cuchillos-presentacion',
'en_title'=>'How to cut and serve cheese: temperature, knives, cuts and presentation',
'en_slug'=>'how-to-cut-serve-cheese-temperature-knives-cuts-presentation',
'excerpt'=>'Cómo servir queso para que exprese mejor su textura y aroma: atemperado, cuchillos, cortes según la forma de la pieza y presentación.',
'en_excerpt'=>'How to serve cheese so texture and aroma show at their best: warming slightly, knives, cuts for different shapes and presentation.',
'lead_es'=>'Un queso excelente puede decepcionar si se sirve helado, reseco o cortado de forma que unas personas reciban toda la corteza y otras solo el centro. Servir bien no requiere ceremonial: basta con controlar temperatura, corte, utensilios y cantidades para que cada porción sea representativa de la pieza.',
'lead_en'=>'Excellent cheese can disappoint when served fridge-cold, dried out or cut so that some people receive only rind while others get only centre paste. Good service does not require ceremony; temperature, cutting, utensils and sensible portions are enough to make each serving representative of the cheese.',
'facts_es'=>array(array('Temperatura','Atemperar la porción que se va a comer, no toda la pieza durante horas.'),array('Corte','Intentar repartir corteza y centro de forma equilibrada.'),array('Cuchillos','Separar utensilios cuando los perfiles son muy distintos, especialmente azules.'),array('Cantidad','Cortar poco a poco para evitar que todo se seque en mesa.')),
'facts_en'=>array(array('Temperature','Let the portion being eaten warm slightly rather than leaving the whole cheese out for hours.'),array('Cut','Share rind and centre fairly where appropriate.'),array('Knives','Use separate utensils for very different styles, especially blue cheese.'),array('Quantity','Cut progressively so the whole cheese does not dry on the table.')),
'sections_es'=>array(
array('Por qué la temperatura cambia tanto la percepción','El frío endurece la grasa y reduce la volatilidad de muchos compuestos aromáticos. Por eso un queso recién sacado de la nevera puede parecer más duro, menos aromático y menos persistente de lo que realmente es. Atemperar no significa calentar: significa dejar que la porción de servicio pierda el frío más intenso.\n\nEl tiempo necesario depende de tamaño, textura y temperatura ambiente. Una loncha fina cambia antes que una cuña gruesa. La mejor señal es sensorial: cuando la pasta recupera su textura característica y aparecen los aromas, está listo.'),
array('Cómo cortar cuñas y ruedas','En una cuña, intenta que cada porción conserve una relación razonable entre centro y zona próxima a la corteza. Si cortas únicamente en paralelo a la corteza, unas porciones quedarán compuestas casi solo por el exterior y otras solo por el corazón.\n\nEn ruedas pequeñas puede funcionar el corte radial. En bloques rectangulares, lonchas o bastones. Los quesos cilíndricos altos y las piezas irregulares requieren adaptar el patrón. La meta no es estética perfecta, sino repartir el queso de manera justa.'),
array('Qué cuchillo utilizar','Una hoja fina reduce adherencia en pastas blandas; cuchillos cortos y firmes ayudan con quesos duros. Para azules o quesos muy aromáticos conviene un utensilio separado para evitar arrastrar sabor al resto. Un hilo puede ser útil en determinadas pastas muy blandas.\n\nMás importante que comprar diez cuchillos es mantener una hoja limpia, cortar con estabilidad y no aplastar la pieza. Un buen cuchillo de chef puede resolver muchos quesos si se usa con cuidado.'),
array('Corteza: repartirla no siempre significa comerla','En quesos con corteza comestible, una porción que incluye parte del exterior permite entender cómo cambia el perfil desde el centro. Pero existen recubrimientos o cortezas que no se destinan al consumo. No debe asumirse que todo lo visible es comestible.\n\nConsulta la etiqueta o al productor cuando haya duda. En una tabla, retirar discretamente un recubrimiento no comestible antes de servir puede facilitar mucho la experiencia.'),
array('Presentación y ritmo de servicio','No hace falta llenar una tabla enorme con todo ya cortado. Servir piezas parcialmente enteras y cortar a medida mantiene mejor la humedad y ofrece contexto visual. Deja espacio entre quesos, coloca los más cremosos en zonas donde puedan cortarse sin contaminar otros y añade acompañamientos sin cubrir las piezas.\n\nSi hay varios quesos, ordenarlos de menor a mayor intensidad ayuda a que los más potentes no saturen el paladar al principio.')
),
'sections_en'=>array(
array('Why temperature changes perception so much','Cold firms milk fat and reduces the volatility of many aroma compounds. Cheese straight from the refrigerator can therefore seem harder, less aromatic and less persistent than it really is. Bringing it towards serving temperature does not mean heating it; it means letting the serving portion lose its deepest chill.\n\nThe time required depends on size, texture and room temperature. A thin slice changes faster than a thick wedge. Sensory cues are more useful than a rigid stopwatch.'),
array('How to cut wedges and wheels','With a wedge, try to give each portion a reasonable balance of centre and area near the rind. Cutting only parallel to the rind leaves some people with almost all exterior and others with only the centre.\n\nSmall wheels often suit radial cuts, rectangular blocks can become slices or batons, and tall cylinders or irregular cheeses need adapted patterns. The goal is fair distribution rather than geometric perfection.'),
array('Choosing a knife','A thin blade reduces sticking with softer pastes; short sturdy knives help with hard cheese. Blue or strongly aromatic cheese benefits from a separate utensil to avoid transferring flavour. Wire can be useful for some very soft styles.\n\nOwning ten specialised knives matters less than using a clean, stable blade and avoiding crushing. A good chef’s knife handles many cheeses when used carefully.'),
array('Rind: sharing it does not always mean eating it','For cheeses with edible rinds, including some exterior in each portion can show how flavour changes across the paste. But some coatings are not intended for eating, so visible “rind” should not automatically be assumed edible.\n\nCheck the label or producer guidance when uncertain. Removing a non-edible coating before serving can make a board much easier for guests.'),
array('Presentation and serving rhythm','You do not need to pre-cut an entire large board. Leaving cheeses partly whole and cutting as needed helps retain moisture and gives visual context. Leave space between cheeses, position creamy styles where they can be served without smearing neighbours, and keep accompaniments from covering the cheese itself.\n\nWhen several cheeses are served, moving from gentler to more intense styles helps preserve palate sensitivity.')
),
'practical_es'=>'Para mejorar una tabla sin gastar más, sirve menos cantidad de cada queso, mejor atemperada y mejor cortada. La experiencia suele mejorar más por esos tres detalles que por añadir muchas referencias.',
'practical_en'=>'To improve a cheese board without spending more, serve smaller amounts of each cheese at a better temperature and cut them more thoughtfully. Those three details often matter more than adding more varieties.',
'sources'=>array('https://www.boe.es/eli/es/rd/2006/09/29/1113')
),
array(
'pos'=>9,
'title'=>'Cómo preparar una tabla de quesos: cantidades, orden y acompañamientos',
'slug'=>'como-preparar-tabla-quesos-cantidades-orden-acompanamientos',
'en_title'=>'How to build a cheese board: quantities, order and accompaniments',
'en_slug'=>'how-to-build-cheese-board-quantities-order-accompaniments',
'excerpt'=>'Cómo preparar una tabla de quesos equilibrada sin comprar de más: número de quesos, cantidades orientativas, contraste, orden y acompañamientos.',
'en_excerpt'=>'How to build a balanced cheese board without overbuying: number of cheeses, practical quantities, contrast, serving order and accompaniments.',
'lead_es'=>'Una buena tabla no se construye acumulando el mayor número posible de quesos. Se construye con contraste y proporción: diferentes leches, texturas y maduraciones, pero con suficiente espacio para entender cada pieza. Con cuatro o cinco quesos bien elegidos suele haber más recorrido que con diez opciones casi iguales.',
'lead_en'=>'A good cheese board is not built by piling on the maximum number of cheeses. It is built through contrast and proportion: different milks, textures and ages, with enough space to understand each cheese. Four or five well-chosen cheeses often create more interest than ten near-identical options.',
'facts_es'=>array(array('Número práctico','3–5 quesos suelen bastar para una tabla doméstica equilibrada.'),array('Cantidad','Depende de si es aperitivo, postre o comida; evita tratar una cifra como universal.'),array('Contraste','Combinar leche, textura, intensidad y maduración.'),array('Orden','De suave a intenso cuando se degustan varios.')),
'facts_en'=>array(array('Practical number','3–5 cheeses are usually enough for a balanced home board.'),array('Quantity','Depends on whether cheese is a snack, course or meal; no single number fits all occasions.'),array('Contrast','Mix milk, texture, intensity and age.'),array('Order','Taste from gentler to stronger styles.')),
'sections_es'=>array(
array('Cuántos quesos poner','Tres quesos permiten construir un contraste claro: por ejemplo, uno blando, uno de pasta firme y uno más intenso. Con cuatro o cinco puedes añadir otra leche, un azul o una maduración diferente. A partir de ahí aumenta el riesgo de redundancia y de que sobren muchas cuñas abiertas.\n\nSi la tabla forma parte de una comida abundante, menos suele ser más. Si es el centro de la cena, puedes ampliar variedad y cantidad. El contexto manda.'),
array('Cómo calcular cantidades sin convertirlo en una fórmula rígida','La ración depende de lo que se sirva antes y después, del número de acompañamientos y de la intensidad de los quesos. Un queso potente se consume en porciones menores que uno suave. Por eso es más útil partir de una cantidad moderada y poder reponer que llenar la mesa al principio.\n\nPara compras online, el formato importa: varias cuñas pequeñas permiten más variedad con menos excedente que ruedas o bloques grandes.'),
array('El método más fácil para crear contraste','Elige primero una pasta y una intensidad. Después evita repetir el mismo perfil. Una combinación sencilla puede incluir un queso joven y cremoso, uno de oveja semicurado, uno de cabra con personalidad y un curado o azul más intenso. No hace falta cumplir una lista fija.\n\nLa clave es que cada queso aporte una razón para estar en la tabla: otra textura, otra leche, otra corteza o una maduración distinta.'),
array('Acompañamientos que ayudan en vez de tapar','Pan neutro o crackers sencillos limpian el paladar sin competir. Fruta fresca, frutos secos y fruta deshidratada aportan contraste de textura y dulzor. Membrillo y miel pueden funcionar con determinados quesos, pero conviene servirlos aparte para que cada persona decida.\n\nEvita que salsas muy intensas cubran todos los quesos. El acompañamiento debe ampliar la experiencia, no convertir cinco piezas diferentes en el mismo bocado dulce.'),
array('Orden, temperatura y presentación','Saca porciones con antelación suficiente para que pierdan el frío intenso, pero mantén el resto en nevera. Ordena de suave a intenso y separa cuchillos en quesos azules o muy cremosos. Deja etiquetas o una nota sencilla si hay DOP, leche o productor que merezca explicación.\n\nUna tabla con huecos suele resultar más elegante y práctica que una superficie completamente cubierta. El espacio permite cortar, distinguir y servir sin mezclarlo todo.')
),
'sections_en'=>array(
array('How many cheeses to serve','Three cheeses can create clear contrast: for example, one soft, one firm and one more intense. Four or five lets you add another milk, a blue or a different age. Beyond that, redundancy increases and you are more likely to end up with many open leftovers.\n\nIf the board is part of a large meal, less is usually better. If cheese is the centre of dinner, both variety and quantity can increase. Context matters.'),
array('How to estimate quantity without turning it into a rigid formula','Portion size depends on what comes before and after, how many accompaniments are served and how intense the cheeses are. Strong cheese is eaten in smaller portions than mild cheese. Starting moderately and replenishing is often better than filling the board at once.\n\nFor online shopping, format matters: several small wedges create more variety with less surplus than large wheels or blocks.'),
array('The easiest way to create contrast','Choose one texture and intensity, then avoid repeating it. A simple mix might include a young creamy cheese, a semi-aged sheep’s cheese, a characterful goat cheese and a stronger aged or blue cheese. There is no mandatory checklist.\n\nEach cheese should earn its place by contributing another texture, milk, rind or maturity level.'),
array('Accompaniments that support rather than cover','Neutral bread or simple crackers reset the palate. Fresh fruit, nuts and dried fruit add texture and sweetness. Quince paste and honey can work beautifully with selected cheeses, but serving them separately allows guests to control the combination.\n\nAvoid powerful sauces that make every cheese taste like the same sweet bite. Accompaniments should expand the experience, not hide it.'),
array('Order, temperature and presentation','Let serving portions lose their deepest chill while keeping the remainder refrigerated. Taste from mild to strong and use separate knives for blue or very creamy cheese. Simple labels can help when PDO, milk or producer deserves explanation.\n\nA board with empty space is often more elegant and more functional than one completely covered with food; space makes cutting and serving easier.')
),
'practical_es'=>'Antes de comprar, escribe cuatro huecos: suave/blando, medio/firme, distinto por leche o corteza, e intenso. Rellena esos huecos y para. Es una forma muy eficaz de evitar comprar seis quesos que terminan sabiendo demasiado parecidos.',
'practical_en'=>'Before shopping, write four slots: mild/soft, medium/firm, something different by milk or rind, and strong. Fill those slots and stop. It is an effective way to avoid buying six cheeses that end up tasting too similar.',
'sources'=>array('https://www.boe.es/eli/es/rd/2006/09/29/1113')
),
array(
'pos'=>10,
'title'=>'Cómo saber si un queso está en mal estado: moho, olor, textura y cuándo descartarlo',
'slug'=>'como-saber-queso-mal-estado-moho-olor-textura',
'en_title'=>'How to tell if cheese has gone bad: mould, smell, texture and when to discard it',
'en_slug'=>'how-to-tell-cheese-gone-bad-mould-smell-texture-discard',
'excerpt'=>'Cómo distinguir mohos propios del queso de deterioro no deseado, qué hacer con queso duro o blando y qué señales de olor, textura y conservación importan.',
'en_excerpt'=>'How to distinguish intended cheese mould from unwanted spoilage, what to do with hard or soft cheese and which smell, texture and storage signs matter.',
'lead_es'=>'El moho no significa lo mismo en todos los quesos. En un azul, un Brie o determinados quesos de corteza enmohecida forma parte de la elaboración; en un queso donde no debería estar puede ser una señal de deterioro. La respuesta correcta depende sobre todo del tipo de queso, su humedad y de si ese moho pertenece o no al proceso previsto.',
'lead_en'=>'Mould does not mean the same thing in every cheese. In blue cheese, Brie and many mould-ripened rinds it is part of production; in a cheese where it should not be present it may indicate spoilage. The correct response depends mainly on cheese type, moisture and whether the mould belongs to the intended process.',
'facts_es'=>array(array('Moho previsto','En azules y determinadas cortezas forma parte del queso.'),array('Queso duro','USDA indica que un punto de moho no previsto puede recortarse con un margen amplio alrededor y debajo.'),array('Queso blando','Ante moho no previsto, la recomendación es desecharlo.'),array('Regla práctica','Si hay olor, textura o aspecto anormal y dudas razonables, no arriesgar.')),
'facts_en'=>array(array('Intended mould','In blue and mould-ripened cheeses it is part of the product.'),array('Hard cheese','USDA says an unwanted mould spot may be cut away with a generous margin around and below it.'),array('Soft cheese','Unintended mould is a reason to discard soft cheese.'),array('Practical rule','If smell, texture or appearance is abnormal and you are genuinely unsure, do not take the risk.')),
'sections_es'=>array(
array('Primero: distinguir moho del queso y moho sobre el queso','Penicillium y otros cultivos se utilizan deliberadamente en numerosas familias. Un azul está diseñado para desarrollar vetas; un Brie o Camembert utiliza una flora superficial característica. Ver moho en estos casos no equivale a deterioro.\n\nLa pregunta correcta es si ese crecimiento coincide con el estilo del queso y con su aspecto normal. Un color, olor o textura muy diferente de lo habitual merece más precaución que la mera presencia de una corteza enmohecida prevista.'),
array('Qué hacer si aparece moho no previsto en queso duro','El USDA diferencia los quesos duros de los blandos porque el moho penetra con más dificultad en una matriz densa. Su recomendación permite cortar al menos una pulgada alrededor y por debajo del punto de moho, evitando que el cuchillo toque la zona contaminada, y volver a envolver el queso con material limpio.\n\nEste criterio no debe extrapolarse a queso rallado, loncheado o desmenuzado, donde existe mucha más superficie y mayor posibilidad de contaminación distribuida.'),
array('Por qué el queso blando requiere más prudencia','En quesos blandos y húmedos, un crecimiento no previsto puede extenderse por debajo de la superficie visible y coexistir con otros microorganismos. Por eso la recomendación de seguridad es desechar quesos blandos cuando aparece un moho que no forma parte de su elaboración.\n\nLo mismo se aplica con especial prudencia a quesos frescos, cremas de queso y formatos muy manipulados. “Quitar la parte verde” no es una estrategia equivalente a recortar un curado duro.'),
array('Olor, textura y exudados: señales que deben leerse juntas','Muchos quesos maduros tienen aromas potentes que pueden sorprender a quien no conoce el estilo. Un olor intenso no significa automáticamente deterioro. Lo preocupante es un cambio anormal respecto al perfil habitual, especialmente si aparece junto con textura viscosa no prevista, hinchazón del envase, líquidos extraños o decoloraciones nuevas.\n\nComparar con el aspecto original y con la información del productor es más útil que aplicar una regla como “si huele fuerte, está malo”.' ),
array('Cómo reducir problemas una vez abierto','Manipula el queso con manos y cuchillos limpios, cambia envoltorios sucios o húmedos, evita el contacto con alimentos crudos y mantén el frío indicado. Compra formatos que puedas consumir antes de que una cuña pase demasiado tiempo abierta.\n\nCuando un queso se conserva mal, el problema no siempre empieza con un gran parche visible. Pérdida de aroma, superficie reseca o condensación constante son señales de que conviene mejorar el sistema de almacenamiento incluso antes de que exista un riesgo evidente.')
),
'sections_en'=>array(
array('First distinguish mould in the cheese from mould on the cheese','Penicillium and other cultures are deliberately used in many cheese families. Blue cheese is designed to develop internal mould, while Brie and Camembert use characteristic surface flora. Seeing mould in those cheeses does not automatically mean spoilage.\n\nThe useful question is whether the growth matches the intended style and normal appearance. A new colour, smell or texture that is very different from the cheese’s usual profile deserves more caution than an expected mould-ripened rind.'),
array('What to do with unintended mould on hard cheese','USDA distinguishes hard from soft cheese because mould has more difficulty penetrating a dense matrix. Its guidance allows a hard cheese to be trimmed at least one inch around and below the mould spot, keeping the knife out of the mould itself, then rewrapping the remaining cheese cleanly.\n\nThis should not be extrapolated to grated, sliced or crumbled cheese, where far more surface area is exposed and contamination may be distributed.'),
array('Why soft cheese needs more caution','In soft, moist cheese, unintended mould can extend beneath the visible surface and may coexist with other microorganisms. Food-safety guidance therefore recommends discarding soft cheese when mould appears that is not part of its normal production.\n\nFresh cheese, cream cheese and highly handled formats deserve similar caution. Simply scooping away a green patch is not equivalent to trimming a hard aged cheese.'),
array('Smell, texture and liquid: read signs together','Many mature cheeses have powerful aromas that surprise people unfamiliar with the style. Strong smell alone does not prove spoilage. More concerning is an abnormal change from the cheese’s usual profile, especially when combined with unexpected slime, swollen packaging, unusual liquid or new discolouration.\n\nComparing with the original appearance and producer guidance is more reliable than a rule such as “strong smell means bad cheese”.'),
array('Reducing problems after opening','Handle cheese with clean hands and knives, replace dirty or damp wrapping, avoid contact with raw-food juices and maintain the required refrigeration. Buy formats you can finish before a wedge spends too long open.\n\nPoor storage does not always begin with a dramatic mould patch. Lost aroma, severe drying or constant condensation are earlier signs that the storage system needs improvement.')
),
'practical_es'=>'Antes de decidir, identifica el tipo de queso. En un azul o una corteza florida el moho puede ser normal; en un fresco o blando, un moho no previsto es una señal mucho más seria. No apliques la misma regla a todos.',
'practical_en'=>'Identify the cheese type before deciding what to do. Mould may be normal in blue or bloomy-rind cheese; unintended mould on fresh or soft cheese is much more serious. Do not apply one rule to every cheese.',
'sources'=>array('https://www.fsis.usda.gov/food-safety/safe-food-handling-and-preparation/food-safety-basics/molds-food-are-they-dangerous','https://ask.fsis.usda.gov/article/Es-seguro-comer-un-alimento-que-contiene-moho')
)
);

function emdo_cheese01_e( string $s ): string { return esc_html( $s ); }

function emdo_cheese01_category(): WP_Term {
    $term = get_category_by_slug( 'quesos' );
    if ( ! $term instanceof WP_Term ) {
        $created = wp_insert_term( 'Quesos', 'category', array( 'slug'=>'quesos', 'description'=>'Guías de compra, conservación, elaboración y cultura del queso.' ) );
        if ( is_wp_error( $created ) ) { throw new RuntimeException( $created->get_error_message() ); }
        $term = get_term( (int) $created['term_id'], 'category' );
    }
    if ( ! $term instanceof WP_Term ) { throw new RuntimeException( 'Could not resolve Quesos category.' ); }
    update_term_meta( $term->term_id, '_en_US_name', 'Cheese' );
    update_term_meta( $term->term_id, '_en_US_slug', 'cheese' );
    update_term_meta( $term->term_id, '_en_US_description', 'Buying guides, storage advice, cheesemaking and cheese culture.' );
    update_term_meta( $term->term_id, '_en_US_published', '1' );
    return $term;
}

function emdo_cheese01_image( int $category_id ): int {
    $ids = get_posts( array('post_type'=>'post','post_status'=>'publish','posts_per_page'=>10,'fields'=>'ids','category__in'=>array($category_id)) );
    foreach ( $ids as $id ) { $thumb=(int)get_post_thumbnail_id($id); if($thumb>0){return $thumb;} }
    $fallbacks = array('tipos-de-queso-guia-leche-maduracion-pasta-corteza-elaboracion','nutrientes-legumbres-proteinas-fibra-hierro-vitaminas-minerales','que-significa-aceite-oliva-virgen-extra');
    foreach($fallbacks as $slug){$p=get_page_by_path($slug,OBJECT,'post');if($p instanceof WP_Post){$thumb=(int)get_post_thumbnail_id($p->ID);if($thumb>0){return $thumb;}}}
    return 0;
}

function emdo_cheese01_related( array $a, string $lang ): string {
    global $articles;
    $is_es='es'===$lang;
    $out='<ul>';
    $n=0;
    foreach($articles as $other){
        if((int)$other['pos']===(int)$a['pos']){continue;}
        $url=$is_es?('/'.(string)$other['slug'].'/'):('/en/'.(string)$other['en_slug'].'/');
        $label=$is_es?(string)$other['title']:(string)$other['en_title'];
        $out.='<li><a href="'.esc_url($url).'">'.emdo_cheese01_e($label).'</a></li>';
        if(++$n>=5){break;}
    }
    return $out.'</ul>';
}

function emdo_cheese01_render( array $a, string $lang ): string {
    $is_es='es'===$lang;
    $lead=$is_es?$a['lead_es']:$a['lead_en'];
    $facts=$is_es?$a['facts_es']:$a['facts_en'];
    $sections=$is_es?$a['sections_es']:$a['sections_en'];
    $practical=$is_es?$a['practical_es']:$a['practical_en'];
    $out='<p>'.emdo_cheese01_e($lead).'</p>';
    $out.=$is_es?'<p>Esta guía está planteada para resolver la intención de búsqueda completa, no solo para dar una definición rápida. Veremos qué significa cada término, qué cambia realmente en el queso, cómo leer una etiqueta y cómo utilizar esa información al comprar, conservar o servir.</p>':'<p>This guide is designed to answer the full search intent rather than provide a one-line definition. It explains what the terms mean, what truly changes in the cheese, how to read labels and how to use that information when buying, storing or serving.</p>';
    $out.=$is_es?'<h2>Resumen rápido</h2>':'<h2>Quick summary</h2>';
    $out.='<table><tbody>';
    foreach($facts as $row){$out.='<tr><th>'.emdo_cheese01_e((string)$row[0]).'</th><td>'.emdo_cheese01_e((string)$row[1]).'</td></tr>';}
    $out.='</tbody></table>';
    foreach($sections as $sec){
        $out.='<h2>'.emdo_cheese01_e((string)$sec[0]).'</h2>';
        $paras=preg_split('/\n\n+/',(string)$sec[1]);
        foreach($paras as $p){if(trim($p)!==''){$out.='<p>'.emdo_cheese01_e(trim($p)).'</p>';}}
    }
    $out.=$is_es?'<h2>Cómo aplicar esta información al comprar</h2>':'<h2>How to use this when buying cheese</h2>';
    $out.='<p>'.emdo_cheese01_e($practical).'</p>';
    $out.=$is_es
      ? '<p>El precio por kilo puede servir para comparar formatos parecidos, pero no resume leche, tiempo de maduración, rendimiento, DOP, elaboración ni estado de conservación. Compara productos equivalentes y lee la ficha completa antes de sacar conclusiones por una sola cifra.</p>'
      : '<p>Price per kilo is useful for similar formats, but it does not summarise milk, ageing, yield, PDO status, production method or storage condition. Compare like with like and read the complete product information before judging cheese by one number.</p>';
    $out.=$is_es?'<h2>Errores frecuentes</h2><ul><li>Tratar una sola palabra de la etiqueta como una nota absoluta de calidad.</li><li>Comparar quesos de tecnologías muy distintas solo por precio o meses de maduración.</li><li>Ignorar formato, conservación y ritmo de consumo.</li><li>Dar por supuesto que “artesano”, “tradicional” o un nombre geográfico equivalen siempre a una certificación oficial.</li></ul>':'<h2>Common mistakes</h2><ul><li>Using one label word as an absolute quality score.</li><li>Comparing very different cheese technologies only by price or months of ageing.</li><li>Ignoring format, storage and consumption rate.</li><li>Assuming “artisan”, “traditional” or a place name always equals official certification.</li></ul>';
    $out.=$is_es?'<h2>Preguntas rápidas</h2>':'<h2>Quick questions</h2>';
    $out.=$is_es
      ? '<h3>¿Más curación significa siempre mejor queso?</h3><p>No. Significa un estilo de maduración distinto. Calidad e intensidad no son sinónimos.</p><h3>¿La leche determina por completo el sabor?</h3><p>No. Es una base importante, pero elaboración, fermentos, humedad, corteza y maduración pueden cambiar radicalmente el perfil.</p><h3>¿Conviene comprar la pieza más grande?</h3><p>Solo si el ritmo de consumo lo justifica. Un formato más pequeño puede conservar mejor su calidad una vez abierto.</p>'
      : '<h3>Does longer ageing always mean better cheese?</h3><p>No. It means a different maturation style. Quality and intensity are not synonyms.</p><h3>Does milk completely determine flavour?</h3><p>No. Milk is important, but cultures, moisture, rind, technology and ageing can radically change the profile.</p><h3>Should I buy the largest format?</h3><p>Only if your consumption rate justifies it. A smaller format may retain quality better after opening.</p>';
    $out.=$is_es?'<h2>Guías relacionadas</h2>':'<h2>Related guides</h2>';
    $out.=emdo_cheese01_related($a,$lang);
    $out.=$is_es?'<h2>Conclusión</h2>':'<h2>Bottom line</h2>';
    $out.=$is_es
      ? '<p>Entender el queso requiere mirar el conjunto: leche, elaboración, maduración, textura, corteza, origen y conservación. Cuantas más de esas piezas puedas leer juntas, menos dependerás de etiquetas ambiguas y mejor podrás elegir según el uso y tu gusto.</p>'
      : '<p>Understanding cheese means reading the whole picture: milk, production, ageing, texture, rind, origin and storage. The more of those pieces you can connect, the less you depend on vague labels and the easier it becomes to choose for your taste and intended use.</p>';
    $out.=$is_es?'<h2>Fuentes y referencias</h2><p>Se han priorizado normativa, organismos oficiales y fuentes de seguridad alimentaria. Cuando una DOP tiene pliego propio, ese pliego vigente es la referencia principal para sus requisitos.</p>':'<h2>Sources and references</h2><p>Regulations, official bodies and food-safety sources have been prioritised. Where a PDO has its own specification, the current specification is the primary reference for certification requirements.</p>';
    $out.='<ul>';foreach((array)$a['sources'] as $src){$host=wp_parse_url((string)$src,PHP_URL_HOST);$out.='<li><a href="'.esc_url((string)$src).'" rel="noopener noreferrer">'.emdo_cheese01_e((string)$host).'</a></li>';}$out.='</ul>';
    return $out;
}

function emdo_cheese01_meta_title(string $s): string { if(function_exists('mb_strlen')&&mb_strlen($s,'UTF-8')>62){return rtrim(mb_substr($s,0,59,'UTF-8')).'…';} return $s; }
function emdo_cheese01_meta_description(string $s): string { if(function_exists('mb_strlen')&&mb_strlen($s,'UTF-8')>158){return rtrim(mb_substr($s,0,155,'UTF-8')).'…';} return $s; }

function emdo_cheese01_upsert(array $a, WP_Term $term, int $image_id): int {
    $slug=(string)$a['slug'];
    $existing=get_page_by_path($slug,OBJECT,'post');
    if($existing instanceof WP_Post){$marker=(string)get_post_meta($existing->ID,'_emdo_cheese_batch01',true);if(EMDO_CHEESE_BATCH01_MARKER!==$marker){throw new RuntimeException('Refusing to overwrite existing non-batch post: '.$slug);}}
    $sample=get_posts(array('post_type'=>'post','post_status'=>'publish','posts_per_page'=>1,'fields'=>'ids','category__in'=>array((int)$term->term_id)));
    $author=!empty($sample)?(int)get_post_field('post_author',(int)$sample[0]):1;if($author<=0){$author=1;}
    $postarr=array('post_type'=>'post','post_status'=>'publish','post_title'=>(string)$a['title'],'post_name'=>$slug,'post_excerpt'=>(string)$a['excerpt'],'post_content'=>emdo_cheese01_render($a,'es'),'post_author'=>$author,'post_category'=>array((int)$term->term_id),'comment_status'=>'closed','ping_status'=>'closed');
    if($existing instanceof WP_Post){$postarr['ID']=(int)$existing->ID;$result=wp_update_post(wp_slash($postarr),true);}else{$result=wp_insert_post(wp_slash($postarr),true);}
    if(is_wp_error($result)||(int)$result<=0){throw new RuntimeException('Failed to publish '.$slug);}
    $id=(int)$result;
    update_post_meta($id,'_emdo_cheese_batch01',EMDO_CHEESE_BATCH01_MARKER);
    update_post_meta($id,'_emdo_editorial_position',(string)(int)$a['pos']);
    update_post_meta($id,'_emdo_seo_title',emdo_cheese01_meta_title((string)$a['title']));
    update_post_meta($id,'_emdo_seo_description',emdo_cheese01_meta_description((string)$a['excerpt']));
    update_post_meta($id,'_en_US_post_title',(string)$a['en_title']);
    update_post_meta($id,'_en_US_post_name',(string)$a['en_slug']);
    update_post_meta($id,'_en_US_post_excerpt',(string)$a['en_excerpt']);
    update_post_meta($id,'_en_US_post_content',emdo_cheese01_render($a,'en'));
    update_post_meta($id,'_en_US_seo_title',emdo_cheese01_meta_title((string)$a['en_title']));
    update_post_meta($id,'_en_US_seo_description',emdo_cheese01_meta_description((string)$a['en_excerpt']));
    update_post_meta($id,'_en_US_ready','1');update_post_meta($id,'_en_US_published','1');
    if($image_id>0){set_post_thumbnail($id,$image_id);} return $id;
}

$term=emdo_cheese01_category();
$image_id=emdo_cheese01_image((int)$term->term_id);
$published=array();
foreach($articles as $a){
    $id=emdo_cheese01_upsert($a,$term,$image_id);
    $es_words=str_word_count(wp_strip_all_tags((string)get_post_field('post_content',$id)));
    $en_words=str_word_count(wp_strip_all_tags((string)get_post_meta($id,'_en_US_post_content',true)));
    if('publish'!==get_post_status($id)||(string)get_post_meta($id,'_en_US_published',true)!=='1'){throw new RuntimeException('Bilingual verification failed for '.$a['slug']);}
    if($es_words<700||$en_words<620){throw new RuntimeException('Article too short '.$a['slug'].' ES='.$es_words.' EN='.$en_words);}
    $published[]=array('position'=>(int)$a['pos'],'id'=>$id,'slug'=>(string)$a['slug'],'en_slug'=>(string)$a['en_slug'],'category'=>$term->name,'es_words'=>$es_words,'en_words'=>$en_words,'image_id'=>(int)get_post_thumbnail_id($id));
}
echo "EMDO_CHEESE_BATCH01_BEGIN\n";
echo wp_json_encode(array('marker'=>EMDO_CHEESE_BATCH01_MARKER,'count'=>count($published),'category_id'=>(int)$term->term_id,'category'=>$term->name,'image_id'=>$image_id,'posts'=>$published),JSON_UNESCAPED_SLASHES|JSON_UNESCAPED_UNICODE)."\n";
echo "EMDO_CHEESE_BATCH01_END\n";
