<?php
if (!defined('ABSPATH')) { exit; }
function emdop6_words($html){$text=trim(preg_replace('/\s+/u',' ',wp_strip_all_tags(strip_shortcodes($html))));if($text==='')return 0;preg_match_all('/[\p{L}\p{M}]+(?:[’\x{27}’-][\p{L}\p{M}]+)*/u',$text,$m);return count($m[0]);}
function emdop6_cat($name,$slug,$en_name,$en_slug,$fallback=''){$term=get_term_by('slug',$slug,'category');if(!$term&&$fallback)$term=get_term_by('name',$fallback,'category');if(!$term)$term=get_term_by('name',$name,'category');if(!$term){$made=wp_insert_term($name,'category',array('slug'=>$slug));if(is_wp_error($made))throw new Exception($made->get_error_message());$term=get_term((int)$made['term_id'],'category');}update_term_meta($term->term_id,'_en_US_name',$en_name);update_term_meta($term->term_id,'_en_US_slug',$en_slug);update_term_meta($term->term_id,'_en_US_published','1');return (int)$term->term_id;}
function emdop6_existing($key,$slug){$ids=get_posts(array('post_type'=>'post','post_status'=>'any','posts_per_page'=>1,'fields'=>'ids','meta_key'=>'_emdo_authority_key','meta_value'=>$key));if($ids)return (int)$ids[0];$p=get_page_by_path($slug,OBJECT,'post');return $p?(int)$p->ID:0;}
$dir=(string)getenv('EMDO_PRIORITY_BATCH06_DIR');if(!$dir||!is_dir($dir))throw new Exception('Priority batch 06 data directory missing');$files=glob(trailingslashit($dir).'*.php');sort($files,SORT_NATURAL);if(count($files)!==5)throw new Exception('Expected five article files');
$guide=emdop6_cat('Guías y consejos','guias-y-consejos','Guides and advice','guides-and-advice');
$cats=array('ham'=>emdop6_cat('Jamones y paletas','jamones-y-paletas','Hams and shoulders','hams-and-shoulders'),'pulses'=>emdop6_cat('Legumbres','legumbres','Pulses','pulses'),'cured'=>emdop6_cat('Embutidos y curados','embutidos-y-curados','Cured meats','cured-meats','Embutidos y curados'),'meat'=>emdop6_cat('Carnes','carnes','Meat','meat'));
$product_slugs=array('ham'=>'jamones-paletas','pulses'=>'legumbres','cured'=>'embutidos-curados','meat'=>'carnes');
$default=(int)get_option('emdo_default_blog_featured_attachment_id',0);if($default<=0||get_post_type($default)!=='attachment')throw new Exception('Central provisional image missing');$default_hash=(string)get_option('emdo_default_blog_featured_hash','');$admins=get_users(array('role'=>'administrator','number'=>1,'fields'=>'ID'));$author=$admins?(int)$admins[0]:1;$rows=array();
foreach($files as $file){
  $a=require $file;
  foreach(array('key','priority','slug','en_slug','topic','title','en_title','excerpt','en_excerpt','content','en_content','min_es','min_en') as $f){if(!isset($a[$f])||$a[$f]==='')throw new Exception(basename($file).' missing '.$f);}
  if(!isset($cats[$a['topic']]))throw new Exception('Unexpected topic '.$a['topic']);
  if((int)$a['priority']<26||(int)$a['priority']>30)throw new Exception('Unexpected priority '.(int)$a['priority']);
  $product=$product_slugs[$a['topic']];$content=str_replace('__PRODUCT_CAT__',$product,$a['content']);$en=str_replace('__PRODUCT_CAT__',$product,$a['en_content']);
  if($a['key']==='priority-26-ham-gift-guide'){
    $es='<h2>Cómo repartir el presupuesto del regalo</h2><p>Cuando el presupuesto es limitado, suele ser mejor elegir un formato que el destinatario vaya a aprovechar por completo que sobredimensionar la pieza. Varios sobres de una categoría superior pueden ser un regalo más redondo que una pieza grande de categoría inferior si la persona valora especialmente calidad y comodidad. Para una familia que disfruta cortando jamón, en cambio, una pieza completa aporta una experiencia que el loncheado no reproduce.</p><p>También conviene reservar parte del presupuesto para presentación, transporte y, si hace falta, jamonero o cuchillo. El precio del producto no es el único coste que determina si el regalo será práctico.</p><h2>Conservación y fecha de entrega</h2><p>Si el regalo se compra con antelación, revisa las instrucciones del productor. Una pieza entera sin empezar suele requerir un lugar fresco, seco y alejado de fuentes de calor, mientras que los sobres loncheados pueden exigir refrigeración según su etiquetado. En Navidad u otra fecha concreta, es preferible que llegue con margen suficiente pero no semanas antes sin necesidad.</p>';
    $ee='<h2>How to allocate the gift budget</h2><p>When budget is limited, choosing a format the recipient will actually finish is usually better than simply buying the largest possible piece. Several packs from a higher category may be a better gift than a large lower-category ham when quality and convenience matter most. For a family that enjoys carving, however, a whole piece can create an experience sliced packs cannot reproduce.</p><p>Remember presentation, transport and, when needed, a ham stand or carving knife. The price of the ham itself is not the only cost that determines whether the gift will be practical.</p><h2>Storage and delivery date</h2><p>If the gift is bought in advance, follow the producer instructions. An unopened whole piece normally needs a cool, dry location away from heat, while sliced packs may require refrigeration according to the label. For Christmas or another fixed occasion, delivery should leave enough margin without forcing unnecessary storage for weeks.</p>';
    $content=str_replace('<h2>Jamones y paletas</h2>',$es.'<h2>Jamones y paletas</h2>',$content);$en=str_replace('<h2>Hams and shoulders</h2>',$ee.'<h2>Hams and shoulders</h2>',$en);
  }
  if($a['key']==='priority-27-pulses-less-gas'){
    $es='<h2>¿Qué legumbres suelen sentar mejor?</h2><p>No todas las personas reaccionan igual a todas las legumbres. Las lentejas, porciones pequeñas de garbanzos o legumbres muy bien cocidas pueden resultar más fáciles para algunas personas que un plato grande de alubias. La variedad, el tamaño de la ración y el resto de ingredientes influyen. Por eso es más útil observar la tolerancia individual que clasificar una legumbre como “digestiva” y otra como “indigesta”.</p><h2>El contexto del plato también importa</h2><p>Un plato de legumbres acompañado de gran cantidad de otras fuentes de fibra, verduras crucíferas o una comida muy copiosa puede generar más sensación de hinchazón que la misma cantidad de legumbre en una preparación sencilla. Comer despacio, masticar bien y no aumentar de golpe varias fuentes de fibra ayuda a identificar qué cantidad se tolera mejor.</p><p>La adaptación también necesita continuidad: comer una ración enorme una vez al mes no produce el mismo patrón que incorporar cantidades moderadas varias veces por semana.</p>';
    $ee='<h2>Which pulses are often easier to tolerate?</h2><p>People do not react identically to every pulse. Lentils, smaller portions of chickpeas or very thoroughly cooked beans may feel easier for some people than a large serving of another variety. Variety, portion size and the rest of the meal all matter. It is therefore more useful to observe individual tolerance than to label one pulse as universally easy and another as universally difficult.</p><h2>The rest of the meal matters too</h2><p>A serving of pulses combined with very large amounts of other high-fibre foods, cruciferous vegetables or an unusually heavy meal can create more bloating than the same portion in a simpler dish. Eating slowly, chewing well and avoiding several sudden increases in fibre at the same time makes it easier to identify a comfortable amount.</p><p>Adaptation also depends on consistency. A huge bowl once a month is not the same pattern as moderate servings several times each week.</p>';
    $content=str_replace('<h2>Legumbres</h2>',$es.'<h2>Legumbres</h2>',$content);$en=str_replace('<h2>Pulses</h2>',$ee.'<h2>Pulses</h2>',$en);
  }
  if($a['key']==='priority-28-salchichon-vs-fuet'){
    $es='<h2>Qué mirar en la etiqueta</h2><p>Para comparar dos piezas de verdad, revisa porcentaje de carne, especie, ingredientes, tipo de tripa, peso y condiciones de conservación. En un salchichón ibérico también interesa comprobar la denominación que identifica la materia prima. Dos productos con aspecto parecido pueden tener formulaciones y tiempos de curación muy distintos.</p><h2>Fuet o salchichón ibérico: ¿cuál es más intenso?</h2><p>No existe una regla absoluta, pero un salchichón ibérico bien curado suele buscar una expresión más marcada de la grasa y la materia prima, mientras que muchos fuets priorizan un perfil fácil, ligeramente fermentado y de consumo cotidiano. El calibre también cambia la percepción: una loncha grande y fina de salchichón no se comporta en boca igual que una rodaja pequeña y más gruesa de fuet.</p><p>La mejor comparación es probarlos a temperatura de servicio similar y con cortes adecuados a cada formato.</p>';
    $ee='<h2>What should you check on the label?</h2><p>To compare two products properly, look at meat content, species, ingredients, casing, weight and storage instructions. On Iberian salchichón, the legal product description also helps identify the raw material. Two sausages that look similar can use very different formulations and curing periods.</p><h2>Fuet or Iberian salchichón: which tastes stronger?</h2><p>There is no absolute rule, but a well-cured Iberian salchichón often places greater emphasis on the character of the fat and raw material, while many fuets aim for an approachable, lightly fermented everyday profile. Diameter also changes perception: a broad thin slice of salchichón behaves differently in the mouth from a smaller, thicker slice of fuet.</p><p>The fairest comparison is to serve both at a similar temperature and slice each one in a way that suits its format.</p>';
    $content=str_replace('<h2>Embutidos y curados</h2>',$es.'<h2>Embutidos y curados</h2>',$content);$en=str_replace('<h2>Cured meats</h2>',$ee.'<h2>Cured meats</h2>',$en);
  }
  if($a['key']==='priority-29-marinating-beef-time'){
    $es='<h2>El grosor cambia más de lo que parece</h2><p>No conviene aplicar el mismo tiempo a tiras de un centímetro y a una pieza gruesa de varios centímetros. Cuanto menor es el grosor, mayor proporción de la carne queda cerca de la superficie y mayor es el efecto relativo de sal y ácido. En piezas finas, una marinada agresiva necesita menos tiempo; en piezas gruesas, alargar el proceso no garantiza que los aromas lleguen al centro.</p><h2>Errores frecuentes al marinar</h2><ul><li>Usar demasiado ácido pensando que ablandará sin límite.</li><li>Marinar a temperatura ambiente.</li><li>Cocinar la carne empapada y después preguntarse por qué no dora.</li><li>Reutilizar directamente como salsa el líquido que tocó carne cruda.</li><li>Añadir tanta azúcar a la marinada que se quema antes de que la carne alcance el punto deseado.</li></ul><p>Una marinada equilibrada debe apoyar el sabor del corte, no ocultarlo ni dificultar su cocción.</p>';
    $ee='<h2>Thickness matters more than it seems</h2><p>The same timing should not be used for one-centimetre strips and a thick steak. The thinner the piece, the greater the proportion of meat close to the surface and the stronger the relative effect of salt and acid. Thin pieces need less time in an aggressive marinade. With thick pieces, leaving them longer still does not guarantee that aromatic compounds will reach the centre.</p><h2>Common marinating mistakes</h2><ul><li>Using excessive acid because more is assumed to mean more tender.</li><li>Marinating at room temperature.</li><li>Cooking meat while its surface is dripping wet and then getting poor browning.</li><li>Using raw-meat marinade directly as a finished sauce.</li><li>Adding so much sugar that the exterior burns before the beef reaches the desired doneness.</li></ul><p>A balanced marinade should support the flavour of the cut rather than hide it or make cooking more difficult.</p>';
    $content=str_replace('<h2>Carnes</h2>',$es.'<h2>Carnes</h2>',$content);$en=str_replace('<h2>Meat</h2>',$ee.'<h2>Meat</h2>',$en);
  }
  if($a['key']==='priority-30-discard-soaking-water'){
    $es='<h2>Cómo cambia el caldo al usar agua nueva</h2><p>Empezar con agua limpia permite controlar mejor el aspecto y la intensidad del caldo. Si después queremos un plato espeso, podemos conseguirlo con la propia cocción, triturando una pequeña parte de las legumbres o reduciendo el líquido. No necesitamos conservar el agua de remojo para obtener un guiso con cuerpo.</p><h2>Remojos largos y temperatura</h2><p>Cuando el remojo dura toda la noche y la cocina está muy caliente, es razonable hacerlo en la nevera para evitar fermentaciones no deseadas. El objetivo es hidratar la semilla, no dejar que el agua desarrolle olores ácidos, espuma o actividad evidente. Si el líquido presenta un olor claramente anómalo o signos de alteración, no conviene aprovecharlo.</p><p>Este criterio es especialmente útil en verano, cuando la temperatura ambiente puede ser alta durante muchas horas seguidas.</p>';
    $ee='<h2>How does fresh water change the broth?</h2><p>Starting with clean water makes the colour and intensity of the cooking liquid easier to control. If a thick stew is desired, body can still be created through cooking, by blending a small portion of the pulses or by reducing the liquid. Keeping soaking water is not necessary to produce a rich, substantial broth.</p><h2>Long soaking and temperature</h2><p>When pulses soak overnight and the kitchen is warm, refrigeration is a sensible way to avoid unwanted fermentation. The goal is to hydrate the seed, not to allow the water to develop sour odours, foam or obvious activity. If soaking liquid develops a clearly abnormal smell or signs of spoilage, it should not be reused.</p><p>This matters especially in summer when room temperature may remain high for many consecutive hours.</p>';
    $content=str_replace('<h2>Legumbres</h2>',$es.'<h2>Legumbres</h2>',$content);$en=str_replace('<h2>Pulses</h2>',$ee.'<h2>Pulses</h2>',$en);
  }
  $wes=emdop6_words($content);$wen=emdop6_words($en);if($wes<(int)$a['min_es']||$wen<(int)$a['min_en'])throw new Exception($a['key'].' too short ES='.$wes.'/'.(int)$a['min_es'].' EN='.$wen.'/'.(int)$a['min_en']);
  $existing=emdop6_existing($a['key'],$a['slug']);$new=$existing<=0;$post=array('post_type'=>'post','post_status'=>'publish','post_author'=>$author,'post_title'=>wp_strip_all_tags($a['title']),'post_name'=>sanitize_title($a['slug']),'post_excerpt'=>wp_strip_all_tags($a['excerpt']),'post_content'=>$content);if($existing)$post['ID']=$existing;$res=$existing?wp_update_post($post,true):wp_insert_post($post,true);if(is_wp_error($res))throw new Exception($a['key'].': '.$res->get_error_message());$id=(int)$res;
  wp_set_post_categories($id,array($guide,$cats[$a['topic']]),false);update_post_meta($id,'_emdo_authority_key',$a['key']);update_post_meta($id,'_emdo_priority_plan','38');update_post_meta($id,'_emdo_priority_order',(string)$a['priority']);update_post_meta($id,'_emdo_priority_batch','6');update_post_meta($id,'_en_US_post_title',wp_strip_all_tags($a['en_title']));update_post_meta($id,'_en_US_post_name',sanitize_title($a['en_slug']));update_post_meta($id,'_en_US_post_excerpt',wp_strip_all_tags($a['en_excerpt']));update_post_meta($id,'_en_US_post_content',$en);update_post_meta($id,'_en_US_ready','1');update_post_meta($id,'_en_US_published','1');update_post_meta($id,'_emdo_editorial_updated',gmdate('c'));
  $current=(int)get_post_thumbnail_id($id);$marked=(string)get_post_meta($id,'_emdo_uses_default_featured',true)==='1';if($new||$marked||$current<=0){update_post_meta($id,'_thumbnail_id',$default);update_post_meta($id,'_emdo_uses_default_featured','1');update_post_meta($id,'_emdo_editorial_image_approved_id',$default);update_post_meta($id,'_emdo_editorial_cover_asset_id','emdo-blog-default-featured');update_post_meta($id,'_emdo_editorial_cover_brand_safe','1');update_post_meta($id,'_emdo_default_featured_hash',$default_hash);}clean_post_cache($id);
  $rows[]=array('key'=>$a['key'],'priority'=>(int)$a['priority'],'id'=>$id,'status'=>get_post_status($id),'slug'=>get_post_field('post_name',$id),'en_slug'=>sanitize_title($a['en_slug']),'thumbnail_id'=>(int)get_post_thumbnail_id($id),'provisional'=>(string)get_post_meta($id,'_emdo_uses_default_featured',true),'words_es'=>$wes,'words_en'=>$wen,'min_es'=>(int)$a['min_es'],'min_en'=>(int)$a['min_en'],'topic'=>$a['topic'],'product_category'=>$product,'has_products_es'=>strpos($content,'[products')!==false,'has_products_en'=>strpos($en,'[products')!==false);
}
usort($rows,function($a,$b){return $a['priority']<=>$b['priority'];});echo wp_json_encode(array('batch'=>'priority-06','default'=>$default,'posts'=>$rows),JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES|JSON_PRETTY_PRINT).PHP_EOL;