<?php
/**
 * Runtime stability for WCFM vendor stores 0.10.275.
 *
 * - Keeps the retired native ordering select from being resurrected by the
 *   historical 0.10.270 repair observer after the custom mobile popover mounts.
 * - Adds an iOS/touch fallback that activates the same ordering button without
 *   depending on a synthetic click generated by the browser.
 * - Makes vendor pagination fetches bypass intermediary/browser caches so the
 *   continuous loader cannot receive page 1 again while requesting page 2+.
 *
 * @package ElMercadoDeOrigen
 */

if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

add_action(
	'wp_footer',
	static function (): void {
		if ( is_admin() ) {
			return;
		}
		?>
		<script id="elmercado-vendor-runtime-stability-010275">
		(() => {
			'use strict';
			if (!document.body || !document.body.classList.contains('wcfmmp-store-page')) return;

			const mobile = window.matchMedia('(max-width: 991px)');
			const orderingSelector = '.emo-catalog-toolbar-shared-010229 .woocommerce-ordering';
			let lockQueued = false;

			const setImportant = (node, name, value) => node?.style?.setProperty(name, value, 'important');

			const lockNativeSelect = (form) => {
				if (!mobile.matches || !(form instanceof Element)) return;
				const select = form.querySelector('select');
				const button = form.querySelector('.mdo-vendor-order-button');
				if (!(select instanceof HTMLSelectElement) || !(button instanceof HTMLButtonElement)) return;

				form.style.setProperty('pointer-events', 'auto', 'important');
				form.style.setProperty('position', 'relative', 'important');
				form.style.setProperty('z-index', '40', 'important');
				form.style.setProperty('overflow', 'visible', 'important');
				button.style.setProperty('pointer-events', 'auto', 'important');
				button.style.setProperty('position', 'relative', 'important');
				button.style.setProperty('z-index', '42', 'important');

				select.setAttribute('aria-hidden', 'true');
				select.tabIndex = -1;
				[
					['position','absolute'],['left','0'],['top','0'],['width','1px'],['height','1px'],
					['min-width','1px'],['min-height','1px'],['max-width','1px'],['max-height','1px'],
					['margin','0'],['padding','0'],['border','0'],['opacity','0'],['visibility','hidden'],
					['pointer-events','none'],['overflow','hidden'],['clip-path','inset(50%)'],['z-index','-1']
				].forEach(([name,value]) => setImportant(select,name,value));

				if (button.dataset.mdoTouchFallback010275 !== '1') {
					button.dataset.mdoTouchFallback010275 = '1';
					button.addEventListener('touchend', (event) => {
						if (!mobile.matches) return;
						event.preventDefault();
						event.stopPropagation();
						button.click();
					}, { capture: true, passive: false });
				}
			};

			const lockAll = () => {
				lockQueued = false;
				document.querySelectorAll(orderingSelector).forEach(lockNativeSelect);
			};

			const queueLock = () => {
				if (lockQueued) return;
				lockQueued = true;
				requestAnimationFrame(lockAll);
			};

			lockAll();
			window.addEventListener('load', lockAll, { once: true });
			window.addEventListener('pageshow', lockAll, { passive: true });
			mobile.addEventListener?.('change', queueLock);
			setTimeout(lockAll, 300);
			setTimeout(lockAll, 1100);
			setTimeout(lockAll, 2400);

			new MutationObserver((mutations) => {
				for (const mutation of mutations) {
					if (mutation.type === 'childList') { queueLock(); return; }
					if (mutation.type === 'attributes') {
						const target = mutation.target;
						if (target instanceof Element && (target.matches(`${orderingSelector} select`) || target.matches(`${orderingSelector} .mdo-vendor-order-button`))) {
							queueLock(); return;
						}
					}
				}
			}).observe(document.body, { childList: true, subtree: true, attributes: true, attributeFilter: ['style','class','aria-hidden'] });

			/*
			 * The catalog loader is defined later by the child theme. Wrapping fetch
			 * here therefore affects its page requests without replacing the loader.
			 */
			if (!window.__mdoVendorFetchNoStore010275) {
				window.__mdoVendorFetchNoStore010275 = true;
				const nativeFetch = window.fetch.bind(window);
				window.fetch = (input, init = {}) => {
					try {
						const raw = typeof input === 'string' || input instanceof URL ? input : input?.url;
						const url = new URL(raw, window.location.href);
						const here = new URL(window.location.href);
						const currentStoreBase = here.pathname.replace(/\/page\/\d+\/?$/i, '/').replace(/\/+$/, '/');
						const requestedStoreBase = url.pathname.replace(/\/page\/\d+\/?$/i, '/').replace(/\/+$/, '/');
						const isVendorPageRequest = url.origin === here.origin && requestedStoreBase === currentStoreBase && (/\/page\/\d+\/?$/i.test(url.pathname) || [...url.searchParams.keys()].some(key => ['paged','product-page','product_page','page'].includes(key)));
						if (isVendorPageRequest) {
							url.searchParams.set('_mdo_scroll', `${Date.now()}-${Math.random().toString(36).slice(2,8)}`);
							const headers = new Headers(init?.headers || (input instanceof Request ? input.headers : undefined));
							headers.set('Cache-Control', 'no-cache, no-store, max-age=0');
							headers.set('Pragma', 'no-cache');
							return nativeFetch(url.href, { ...init, cache: 'no-store', headers });
						}
					} catch (_) {}
					return nativeFetch(input, init);
				};
			}
		})();
		</script>
		<?php
	},
	PHP_INT_MAX
);
