<?php
if ( ! defined( 'ABSPATH' ) ) { exit; }
$lang=MDO_Promotions::language(); get_header();
while(have_posts()): the_post(); $id=get_the_ID(); $m=MDO_Promotions::localized($id,$lang); $status=MDO_Promotions::status($id); $supplier=MDO_Promotions::supplier($id); $cta=MDO_Promotions::cta_url($id,$lang); $products=MDO_Promotions::product_ids($id); $img=MDO_Promotions::image_html($id,'large'); ?>
<!-- Especiales v2 -->
<!-- Dos hamburguesas de vaca madurada de regalo -->
<main class="mdo-promotions mdo-promo-single" id="main"><section class="mdo-promo-hero"><div class="mdo-promotions__shell mdo-promo-hero__grid"><div class="mdo-promo-hero__content">
<?php if($m['eyebrow']): ?><p class="mdo-promotions__kicker"><?php echo esc_html($m['eyebrow']); ?></p><?php endif; ?><h1><?php echo esc_html($m['title']); ?></h1>
<?php if($supplier): ?><p class="mdo-promo-hero__producer"><?php echo esc_html(MDO_Promotions::text('with',$lang).' '.(string)$supplier['name']); ?></p><?php endif; ?>
<?php if($m['summary']): ?><p class="mdo-promo-hero__summary"><?php echo esc_html($m['summary']); ?></p><?php endif; ?>
<?php if('expired'===$status): ?><div class="mdo-promo-notice"><strong><?php echo esc_html(MDO_Promotions::text('expired',$lang)); ?></strong> <?php echo esc_html(MDO_Promotions::text('expired_more',$lang)); ?></div><a class="mdo-promo-button" href="<?php echo esc_url(MDO_Promotions::archive_url($lang)); ?>"><?php echo esc_html(MDO_Promotions::text('current',$lang)); ?></a>
<?php elseif('scheduled'===$status): ?><div class="mdo-promo-notice"><?php echo esc_html(MDO_Promotions::text('scheduled',$lang).' '.MDO_Promotions::format_date($m['start'],$lang)); ?>.</div>
<?php else: ?><?php if($m['end']): ?><p class="mdo-promo-hero__date"><?php echo esc_html(MDO_Promotions::text('until',$lang).' '.MDO_Promotions::format_date($m['end'],$lang)); ?></p><?php endif; ?><?php if($cta): ?><a class="mdo-promo-button" href="<?php echo esc_url($cta); ?>"><?php echo esc_html($m['cta_label']?:MDO_Promotions::text('buy',$lang)); ?></a><?php endif; ?><?php endif; ?>
</div><?php if($img): ?><div class="mdo-promo-hero__media"><?php echo $img; // phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped ?></div><?php endif; ?></div></section>
<section class="mdo-promo-detail"><div class="mdo-promotions__shell mdo-promo-detail__grid"><div class="mdo-promo-detail__main">
<?php if($m['benefit']): ?><section class="mdo-promo-section"><h2><?php echo esc_html(MDO_Promotions::text('how',$lang)); ?></h2><p><?php echo nl2br(esc_html($m['benefit'])); ?></p></section><?php endif; ?>
<?php if(trim($m['content'])): ?><section class="mdo-promo-section mdo-promo-section--content"><?php echo wp_kses_post(wpautop($m['content'])); ?></section><?php endif; ?>
<?php if($products&&function_exists('wc_get_product')): ?><section class="mdo-promo-section"><h2><?php echo esc_html(MDO_Promotions::text('related',$lang)); ?></h2><?php echo do_shortcode('[products ids="'.esc_attr(implode(',',$products)).'" columns="3" orderby="post__in"]'); // phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped ?></section><?php endif; ?>
<?php if($m['conditions']): ?><section class="mdo-promo-section mdo-promo-conditions"><h2><?php echo esc_html(MDO_Promotions::text('conditions',$lang)); ?></h2><p><?php echo nl2br(esc_html($m['conditions'])); ?></p></section><?php endif; ?>
</div><aside class="mdo-promo-detail__aside"><?php if($m['coupon']&&'active'===$status): ?><div class="mdo-promo-coupon"><span><?php echo esc_html(MDO_Promotions::text('code',$lang)); ?></span><strong><?php echo esc_html($m['coupon']); ?></strong><button type="button" class="mdo-promo-copy" data-copy="<?php echo esc_attr($m['coupon']); ?>" data-label="<?php echo esc_attr(MDO_Promotions::text('copy',$lang)); ?>" data-copied="<?php echo esc_attr(MDO_Promotions::text('copied',$lang)); ?>"><?php echo esc_html(MDO_Promotions::text('copy',$lang)); ?></button></div><?php endif; ?><a class="mdo-promo-back" href="<?php echo esc_url(MDO_Promotions::archive_url($lang)); ?>"><?php echo esc_html(MDO_Promotions::text('back',$lang)); ?></a></aside></div></section></main>
<?php if($m['coupon']&&'active'===$status): ?><script>(function(){var b=document.querySelector('.mdo-promo-copy');if(!b)return;b.addEventListener('click',function(){var c=b.dataset.copy||'',l=b.dataset.label||'',d=b.dataset.copied||'';if(navigator.clipboard&&navigator.clipboard.writeText){navigator.clipboard.writeText(c).then(function(){b.textContent=d;setTimeout(function(){b.textContent=l;},1800);});}});})();</script><?php endif; ?>
<?php endwhile; get_footer(); ?>
