<?php
/**
 * Plugin Name: MDO English SEO Routes
 * Description: Stable English slugs, hreflang and SEO routes without changing Spanish WooCommerce URLs.
 * Version: 1.0.0
 */
if (!defined('ABSPATH')) exit;

function mdoer_prod(){
 $h=isset($_SERVER['HTTP_HOST'])?strtolower(preg_replace('/:\\d+$/','',(string)$_SERVER['HTTP_HOST'])):'';
 if(!$h) $h=strtolower((string)wp_parse_url((string)get_option('home'),PHP_URL_HOST));
 return in_array($h,['elmercadodeorigen.com','www.elmercadodeorigen.com'],true);
}
function mdoer_en(){if(!mdoer_prod()||is_admin())return false;$p=(string)wp_parse_url(wp_unslash($_SERVER['REQUEST_URI']??''),PHP_URL_PATH);return (bool)preg_match('#^/en(?:/|$)#i',$p);}
function mdoer_text($v){$v=html_entity_decode((string)$v,ENT_QUOTES|ENT_HTML5,'UTF-8');$v=preg_replace('#</?span\\b[^>]*>#iu','',$v);return trim(preg_replace('/\\s+/u',' ',wp_strip_all_tags((string)$v,true)));}
function mdoer_en_slug($id){return sanitize_title((string)get_post_meta((int)$id,'_en_US_post_name',true));}
function mdoer_en_pub($id){return '1'===(string)get_post_meta((int)$id,'_en_US_published',true);}
function mdoer_post_by_en_slug($slug,$types=['page','post','product']){global $wpdb;$in=implode(',',array_fill(0,count($types),'%s'));$sql=$wpdb->prepare("SELECT p.ID FROM {$wpdb->posts} p JOIN {$wpdb->postmeta} s ON s.post_id=p.ID AND s.meta_key='_en_US_post_name' JOIN {$wpdb->postmeta} u ON u.post_id=p.ID AND u.meta_key='_en_US_published' AND u.meta_value='1' WHERE p.post_status='publish' AND p.post_type IN ($in) AND s.meta_value=%s ORDER BY p.ID ASC LIMIT 1",...array_merge($types,[$slug]));$id=(int)$wpdb->get_var($sql);return $id?get_post($id):null;}
function mdoer_post_by_native_slug($slug,$types=['page','post','product']){global $wpdb;$in=implode(',',array_fill(0,count($types),'%s'));$sql=$wpdb->prepare("SELECT ID FROM {$wpdb->posts} WHERE post_status='publish' AND post_type IN ($in) AND post_name=%s ORDER BY ID ASC LIMIT 1",...array_merge($types,[$slug]));$id=(int)$wpdb->get_var($sql);return $id?get_post($id):null;}
function mdoer_term_row($taxonomy,$slug,$english=true){global $wpdb;$field=$english?'tm.meta_value':'t.slug';$join=$english?"JOIN {$wpdb->termmeta} tm ON tm.term_id=t.term_id AND tm.meta_key='_en_US_slug' JOIN {$wpdb->termmeta} pub ON pub.term_id=t.term_id AND pub.meta_key='_en_US_published' AND pub.meta_value='1'":'';$sql=$wpdb->prepare("SELECT t.term_id,t.slug FROM {$wpdb->terms} t JOIN {$wpdb->term_taxonomy} tt ON tt.term_id=t.term_id $join WHERE tt.taxonomy=%s AND $field=%s LIMIT 1",$taxonomy,$slug);return $wpdb->get_row($sql,ARRAY_A);}
function mdoer_en_url($post){if(!$post instanceof WP_Post)return'';$front=(int)get_option('page_on_front');$shop=(int)get_option('woocommerce_shop_page_id');if($post->ID===$front)return home_url('/en/');if($post->ID===$shop)return home_url('/en/shop/');if(!mdoer_en_pub($post->ID)||!($s=mdoer_en_slug($post->ID)))return'';if($post->post_type==='product')return home_url('/en/product/'.$s.'/');return home_url('/en/'.$s.'/');}
function mdoer_term_en_url($term){if(!$term instanceof WP_Term)return'';$s=sanitize_title((string)get_term_meta($term->term_id,'_en_US_slug',true));if(!$s||'1'!==(string)get_term_meta($term->term_id,'_en_US_published',true))return'';$b=['product_cat'=>'product-category','product_tag'=>'product-tag','category'=>'category','post_tag'=>'tag'][$term->taxonomy]??'';return $b?home_url('/en/'.$b.'/'.$s.'/'):'';}
function mdoer_native_post_url($post){$GLOBALS['mdoer_native']=1;try{$u=(string)get_permalink($post);}finally{$GLOBALS['mdoer_native']=0;}return $u;}
function mdoer_native_term_url($term){$GLOBALS['mdoer_native']=1;try{$u=get_term_link($term);}finally{$GLOBALS['mdoer_native']=0;}return is_wp_error($u)?'':(string)$u;}

add_action('parse_request',function($wp){if(!mdoer_prod())return;$p=trim((string)wp_parse_url($_SERVER['REQUEST_URI']??'',PHP_URL_PATH),'/');if(!str_starts_with($p,'en/'))return;$set=function($q)use($wp){foreach(['error','name','pagename','attachment'] as $k)unset($wp->query_vars[$k]);$wp->query_vars=array_merge($wp->query_vars,$q);};if(preg_match('#^en/shop(?:/page/(\\d+))?$#',$p,$m)){$q=['post_type'=>'product'];if(!empty($m[1]))$q['paged']=(int)$m[1];$set($q);return;}if(preg_match('#^en/product/([^/]+)$#',$p,$m)){if($o=mdoer_post_by_en_slug(rawurldecode($m[1]),['product']))$set(['post_type'=>'product','p'=>$o->ID]);return;}foreach(['product-category'=>'product_cat','product-tag'=>'product_tag','category'=>'category','tag'=>'post_tag'] as $base=>$tax){if(preg_match('#^en/'.preg_quote($base,'#').'/([^/]+)(?:/page/(\\d+))?$#',$p,$m)){if($r=mdoer_term_row($tax,rawurldecode($m[1]),true)){$q=[$tax==='category'?'category_name':($tax==='post_tag'?'tag':$tax)=>$r['slug']];if(!empty($m[2]))$q['paged']=(int)$m[2];$set($q);}return;}}
 if(preg_match('#^en/([^/]+)$#',$p,$m)){if($o=mdoer_post_by_en_slug(rawurldecode($m[1]),['page','post']))$set([$o->post_type==='page'?'page_id':'p'=>$o->ID]);}
},0);

add_filter('redirect_canonical',fn($r)=>mdoer_en()?false:$r,PHP_INT_MAX);
foreach(['page_link','post_link','post_type_link'] as $hook)add_filter($hook,function($url,$obj=null){if(!empty($GLOBALS['mdoer_native'])||!mdoer_en())return$url;$p=$obj instanceof WP_Post?$obj:get_post((int)$obj);return $p?(mdoer_en_url($p)?:$url):$url;},9999,2);
add_filter('term_link',function($url,$term){if(!empty($GLOBALS['mdoer_native'])||!mdoer_en())return$url;$u=mdoer_term_en_url($term);return$u?:$url;},9999,2);

function mdoer_preferred(){if(is_front_page())return['es'=>home_url('/'),'en'=>home_url('/en/')];if(function_exists('is_shop')&&is_shop()){$p=get_post((int)get_option('woocommerce_shop_page_id'));return$p?['es'=>mdoer_native_post_url($p),'en'=>home_url('/en/shop/')]:['es'=>'','en'=>''];}if(is_singular()&&($p=get_queried_object()) instanceof WP_Post)return['es'=>mdoer_native_post_url($p),'en'=>mdoer_en_url($p)];if((is_category()||is_tag()||(function_exists('is_product_taxonomy')&&is_product_taxonomy()))&&($t=get_queried_object()) instanceof WP_Term)return['es'=>mdoer_native_term_url($t),'en'=>mdoer_term_en_url($t)];return['es'=>'','en'=>''];}
add_filter('aioseo_canonical_url',function($u){$x=mdoer_preferred();return mdoer_en()&&$x['en']?$x['en']:$u;},9999);
add_filter('get_canonical_url',function($u){$x=mdoer_preferred();return mdoer_en()&&$x['en']?$x['en']:$u;},9999);
add_filter('aioseo_title',function($title){if(!mdoer_en())return$title;if(function_exists('is_shop')&&is_shop())return'Shop | El Mercado de Origen';$o=get_queried_object();if($o instanceof WP_Post){$t=mdoer_text(get_post_meta($o->ID,'_en_US_post_title',true));if($t&&!in_array(strtolower($t),['home','inicio'],true))return stripos($t,'El Mercado de Origen')!==false?$t:$t.' | El Mercado de Origen';}if($o instanceof WP_Term){$t=mdoer_text(get_term_meta($o->term_id,'_en_US_name',true));if($t)return$t.' | El Mercado de Origen';}return$title;},9999);
add_filter('aioseo_description',function($d){if(!mdoer_en())return$d;if(function_exists('is_shop')&&is_shop())return'Shop products selected for their origin, quality and the producers behind them at El Mercado de Origen.';$o=get_queried_object();if($o instanceof WP_Post){$x=mdoer_text(get_post_meta($o->ID,'_en_US_post_excerpt',true));if(!$x)$x=mdoer_text(strip_shortcodes((string)get_post_meta($o->ID,'_en_US_post_content',true)));if($x)return wp_html_excerpt($x,155,'…');}if($o instanceof WP_Term){$x=mdoer_text(get_term_meta($o->term_id,'_en_US_description',true));if($x)return wp_html_excerpt($x,155,'…');}return$d;},9999);

add_action('wp_head',function(){$x=mdoer_preferred();if(!$x['es']||!$x['en'])return;echo '<link rel="alternate" hreflang="es-ES" href="'.esc_url($x['es']).'" data-mdo-hreflang="1">\n';echo '<link rel="alternate" hreflang="en" href="'.esc_url($x['en']).'" data-mdo-hreflang="1">\n';echo '<link rel="alternate" hreflang="x-default" href="'.esc_url($x['es']).'" data-mdo-hreflang="1">\n';},2);
add_action('wp_head',function(){echo '<style id="mdo-hide-lang-ui">.trp-language-switcher-container,.trp-language-switcher,#trp-floater-ls,.trp-floater-ls,.elmercado-falang-switcher,.falang-language-switcher,[class*="falang-language-switcher"],li.menu-item-language,li.lang-item{display:none!important;visibility:hidden!important;pointer-events:none!important}</style>';},PHP_INT_MAX);

function mdoer_rewrite_url($u){if(!$u||preg_match('#^(?:mailto:|tel:|javascript:|#)#i',$u))return$u;$p=wp_parse_url(html_entity_decode($u,ENT_QUOTES|ENT_HTML5,'UTF-8'));if($p===false)return$u;if(isset($p['host'])&&!in_array(strtolower($p['host']),['elmercadodeorigen.com','www.elmercadodeorigen.com'],true))return$u;$path=trailingslashit($p['path']??'/');$new='';if(preg_match('#^/en/tienda(?:/page/(\\d+))?/$#',$path,$m))$new='/en/shop/'.(!empty($m[1])?'page/'.$m[1].'/':'');elseif(preg_match('#^/en/(?:producto|product)/([^/]+)/$#',$path,$m)){if($o=mdoer_post_by_native_slug(rawurldecode($m[1]),['product']))if($s=mdoer_en_slug($o->ID))$new='/en/product/'.$s.'/';}elseif(preg_match('#^/en/(categoria-producto|product-category)/([^/]+)/$#',$path,$m)){if($r=mdoer_term_row('product_cat',rawurldecode($m[2]),false)){$s=sanitize_title((string)get_term_meta((int)$r['term_id'],'_en_US_slug',true));if($s)$new='/en/product-category/'.$s.'/';}}elseif(preg_match('#^/en/([^/]+)/$#',$path,$m)){if($o=mdoer_post_by_native_slug(rawurldecode($m[1]),['page','post']))$new=(string)wp_parse_url(mdoer_en_url($o),PHP_URL_PATH);}if(!$new)return$u;$out=(isset($p['host'])||isset($p['scheme']))?home_url($new):$new;if(!empty($p['query']))$out.='?'.$p['query'];if(!empty($p['fragment']))$out.='#'.$p['fragment'];return$out;}
function mdoer_html($html){if(!mdoer_prod())return$html;$html=preg_replace_callback("#<link\\b[^>]*\\bhreflang=(\"|')[^\"']+\\1[^>]*>#iu",fn($m)=>str_contains($m[0],'data-mdo-hreflang=')?$m[0]:'',$html);if(!mdoer_en())return$html;$html=preg_replace_callback("#\\b(href|action|content)=(\"|')([^\"']+)\\2#iu",fn($m)=>$m[1].'='.$m[2].esc_attr(mdoer_rewrite_url($m[3])).$m[2],$html);$x=mdoer_preferred();if($x['en']){$html=preg_replace("#<link\\b[^>]*\\brel=(\"|')canonical\\1[^>]*>#iu",'',$html);$html=str_ireplace('</head>','<link rel="canonical" href="'.esc_url($x['en']).'" data-mdo-canonical="1">\n</head>',$html);}return$html;}
add_action('template_redirect',function(){if(!is_admin()&&!wp_doing_ajax()&&!is_feed()&&!is_robots())ob_start('mdoer_html');},-900);

add_action('template_redirect',function(){if(!mdoer_en()||wp_doing_ajax())return;$req=trailingslashit((string)wp_parse_url($_SERVER['REQUEST_URI']??'',PHP_URL_PATH));$x=mdoer_preferred();if(!$x['en'])return;$want=trailingslashit((string)wp_parse_url($x['en'],PHP_URL_PATH));if($req!==$want&&($req==='/en/tienda/'||str_starts_with($req,'/en/producto/')||preg_match('#^/en/[^/]+/$#',$req))) {wp_safe_redirect($x['en'],301,'MDO-English-Routing');exit;}},-1000);

function mdoer_sitemap(){global$wpdb;$a=[home_url('/en/'),home_url('/en/shop/')];$ids=$wpdb->get_col("SELECT DISTINCT p.ID FROM {$wpdb->posts} p JOIN {$wpdb->postmeta} s ON s.post_id=p.ID AND s.meta_key='_en_US_post_name' AND s.meta_value<>'' JOIN {$wpdb->postmeta} u ON u.post_id=p.ID AND u.meta_key='_en_US_published' AND u.meta_value='1' WHERE p.post_status='publish' AND p.post_type IN ('page','post','product')");$skip=array_map('intval',[get_option('woocommerce_cart_page_id'),get_option('woocommerce_checkout_page_id'),get_option('woocommerce_myaccount_page_id')]);foreach($ids as$id){$p=get_post((int)$id);if(!$p||in_array((int)$id,$skip,true)||(int)$id===(int)get_option('woocommerce_shop_page_id'))continue;if($u=mdoer_en_url($p))$a[]=$u;}foreach(get_terms(['taxonomy'=>['product_cat','category'],'hide_empty'=>false]) as$t)if($t instanceof WP_Term)if($u=mdoer_term_en_url($t))$a[]=$u;return array_values(array_unique($a));}
add_action('template_redirect',function(){if(!mdoer_prod()||'/english-sitemap.xml'!==(string)wp_parse_url($_SERVER['REQUEST_URI']??'',PHP_URL_PATH))return;nocache_headers();header('Content-Type: application/xml; charset=UTF-8');echo '<?xml version="1.0" encoding="UTF-8"?><urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">';foreach(mdoer_sitemap() as$u)echo'<url><loc>'.esc_url($u).'</loc></url>';echo'</urlset>';exit;},-2000);
add_filter('aioseo_sitemap_indexes',function($x){if(mdoer_prod())$x[]=['loc'=>home_url('/english-sitemap.xml'),'lastmod'=>gmdate(DATE_W3C),'count'=>count(mdoer_sitemap())];return$x;},9999);
add_filter('robots_txt',function($o,$pub){if(!$pub||!mdoer_prod())return$o;$l='Sitemap: '.home_url('/english-sitemap.xml');return str_contains($o,$l)?$o:rtrim($o)."\n$l\n";},9999,2);
