<?php
/**
 * Plugin Name: MDO - Blog discovery loader 0.10.266
 * Description: Loads the blog discovery module and improves desktop pagination density.
 * Version: 0.10.266
 */

if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

add_action(
	'after_setup_theme',
	static function (): void {
		$module = get_stylesheet_directory() . '/inc/blog-discovery-010263.php';
		if ( ! function_exists( 'elmercado_blog_filter_state_010263' ) && is_readable( $module ) ) {
			require_once $module;
		}
	},
	1
);

/** Whether the current request is one of the public blog archive views. */
function mdo_is_blog_archive_request_010266(): bool {
	if ( is_home() || is_category() ) {
		return true;
	}

	return function_exists( 'mdo_english_journal_page_010262' ) && mdo_english_journal_page_010262() > 0;
}

/**
 * Show a denser page-number range on desktop while leaving mobile pagination
 * deliberately compact. For a reasonable number of pages, expose every page.
 * Once the archive grows beyond that, keep two edge pages and four neighbours
 * on each side of the current page.
 *
 * @param string $html Pagination HTML generated by WordPress.
 * @param array  $args paginate_links() arguments.
 */
function mdo_expand_blog_pagination_010266( string $html, array $args ): string {
	if ( is_admin() || wp_is_mobile() || ! mdo_is_blog_archive_request_010266() ) {
		return $html;
	}

	$total = isset( $args['total'] ) ? max( 1, (int) $args['total'] ) : 1;
	if ( $total <= 1 ) {
		return $html;
	}

	$args['show_all'] = $total <= 15;
	$args['end_size'] = 2;
	$args['mid_size'] = 4;

	remove_filter( 'paginate_links_output', 'mdo_expand_blog_pagination_010266', 20 );
	$expanded = paginate_links( $args );
	add_filter( 'paginate_links_output', 'mdo_expand_blog_pagination_010266', 20, 2 );

	return is_string( $expanded ) && '' !== $expanded ? $expanded : $html;
}
add_filter( 'paginate_links_output', 'mdo_expand_blog_pagination_010266', 20, 2 );
