<?php
/**
 * Bootstrap del tema hijo.
 *
 * @package ElMercadoDeOrigen
 */

if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

define( 'ELMERCADO_THEME_VERSION', '0.10.197' );
define( 'ELMERCADO_THEME_PATH', get_stylesheet_directory() );
define( 'ELMERCADO_THEME_URL', get_stylesheet_directory_uri() );

$elmercado_modules = array(
	'inc/setup.php',
	'inc/woocommerce.php',
	'inc/polish.php',
	'inc/performance.php',
	'inc/home-cache.php',
	'inc/final-performance.php',
	'inc/header-finish.php',
	'inc/home-navigation.php',
	'inc/home-refresh.php',
	'inc/home-header-normalize.php',
	'inc/legacy-runtime-cleanup-01093.php',
	'inc/editorial-system.php',
	'inc/editorial-performance.php',
	'inc/editorial-finish.php',
	'inc/commerce-experience.php',
	'inc/performance-release.php',
	'inc/semantic-polish.php',
	'inc/global-finish.php',
	'inc/professional-finish.php',
	'inc/header-search-finish.php',
	'inc/vendor-store-finish.php',
	'inc/premium-qa.php',
	'inc/premium-visual-finish.php',
	'inc/vendor-home-final.php',
	'inc/vendor-home-verification.php',
	'inc/vendor-home-verification-two.php',
	'inc/vendor-home-verification-three.php',
	'inc/accessibility-contrast-final.php',
	'inc/storefront-final-pass.php',
	'inc/premium-storefront-polish.php',
	'inc/visual-correction-093.php',
	'inc/minicart-final-control.php',
	'inc/layout-consistency-096.php',
	'inc/layout-consistency-098.php',
	'inc/minicart-quantity-events-01093.php',
	'inc/product-card-carousel-finish.php',
	'inc/shop-producer-filter-final.php',
	'inc/home-mobile-header-final.php',
	'inc/runtime-stability-final.php',
	'inc/vendor-toolbar-mobile-final.php',
	'inc/storefront-second-review-final.php',
	'inc/cart-counter-visibility-final.php',
	'inc/mobile-catalog-interactions-final.php',
	'inc/catalog-continuous-loading-010176.php',
	'inc/header-unified-final.php',
	'inc/sitewide-visual-harmony-final.php',
	'inc/cart-toast-event-guard-01093.php',
	'inc/mobile-menu-visual-final.php',
	'inc/mobile-header-hitareas-final.php',
	'inc/mobile-visual-corrections-01023.php',
	'inc/mobile-visual-corrections-01024.php',
	'inc/comprehensive-review-01033.php',
	'inc/checkout-contrast-final-01035.php',
	'inc/checkout-stock-final-01036.php',
	'inc/store-vendor-layout-final-01037.php',
	'inc/layout-density-final-01039.php',
	'inc/vendor-flow-gap-final-01041.php',
	'inc/content-header-unification-01042.php',
	'inc/shop-filter-breakpoint-final-01044.php',
	'inc/premium-release-01045.php',
	'inc/premium-release-01046.php',
	'inc/premium-visual-system-01048.php',
	'inc/interaction-layer-01050.php',
	'inc/home-product-card-finish-01052.php',
	'inc/content-alignment-final-01053.php',
	'inc/home-carousel-inert-controls-01054.php',
	'inc/experience-polish-final-01055.php',
	'inc/transaction-focus-final-01056.php',
	'inc/transaction-tail-cleanup-01058.php',
	'inc/checkout-summary-column-01059.php',
	'inc/mobile-reading-checkout-01060.php',
	'inc/visual-coherence-01063.php',
	'inc/redundant-page-header-removal-01068.php',
	'inc/content-start-mobile-filter-01069.php',
	'inc/content-start-stability-01070.php',
	'inc/commerce-top-rhythm-01071.php',
	'inc/content-start-final-01072.php',
	'inc/page-start-filter-final-01074.php',
	'inc/visible-start-line-01080.php',
	'inc/filter-state-final-01083.php',
	'inc/filter-postapply-sync-01086.php',
	'inc/filter-toolbar-final-01087.php',
	'inc/blog-meta-visibility-final-01088.php',
	'inc/desktop-filter-visual-final-01089.php',
	'inc/desktop-filter-layout-final-01090.php',
	'inc/filter-price-init-final-01090.php',
	'inc/desktop-filter-sticky-final-01091.php',
	'inc/native-filter-trigger-guard-01094.php',
	'inc/user-feedback-pass-01095.php',
	'inc/native-filter-remove-01096.php',
	'inc/mobile-home-contrast-01097.php',
	'inc/home-rhythm-final-01099.php',
	'inc/user-request-polish-010100.php',
	'inc/user-request-review-010102.php',
	'inc/filtered-context-desktop-010102.php',
	'inc/visual-continuity-final-010110.php',
	'inc/home-palette-site-final-010117.php',
	'inc/home-hero-cart-balance-010119.php',
	'inc/cart-checkout-filter-refinement-010121.php',
	'inc/cart-checkout-state-cleanup-010123.php',
	'inc/checkout-stability-visual-final-010124.php',
	'inc/transaction-cascade-final-010126.php',
	'inc/checkout-legibility-final-010128.php',
	'inc/cart-checkout-shipping-final-010132.php',
	'inc/home-cart-visual-cleanup-010135.php',
	'inc/home-footer-gap-final-010136.php',
	'inc/checkout-clean-coupon-010137.php',
	'inc/mobile-shipping-calculator-final-010144.php',
	'inc/desktop-shipping-calculator-final-010145.php',
	'inc/home-final-copy-performance-010146.php',
	'inc/home-performance-second-pass-010147.php',
	'inc/home-inline-jquery-010148.php',
	'inc/home-voice-performance-final-010149.php',
	'inc/product-card-density-final-010162.php',
	'inc/product-card-footer-density-010163.php',
	'inc/product-card-footer-flow-010164.php',
	'inc/related-products-responsive-grid-010175.php',
	'inc/home-copy-definitive-010165.php',
	'inc/home-story-card-rhythm-010166.php',
	'inc/commerce-home-clarity-final-010168.php',
	'inc/user-feedback-home-product-010169.php',
	'inc/announcement-rotator-final-010171.php',
	'inc/cart-checkout-contact-cleanup-010185.php',
	'inc/category-specific-filters-010185.php',
	'inc/category-filter-design-010187.php',
	'inc/category-filter-display-fix-010189.php',
	'inc/active-filter-chips-010193.php',
	'inc/active-filter-clear-guard-010191.php',
	'inc/cart-shipping-copy-final-010192.php',
	'inc/catalog-core-filters-010193.php',
	'inc/vendor-filter-visual-fix-010194.php',
	'inc/catalog-filter-unification-010196.php',
	'inc/catalog-filter-final-010197.php',
);

foreach ( $elmercado_modules as $elmercado_module ) {
	$elmercado_module_path = ELMERCADO_THEME_PATH . '/' . $elmercado_module;
	if ( is_readable( $elmercado_module_path ) ) {
		require_once $elmercado_module_path;
	}
}

remove_action( 'wp_print_styles', 'elmercado_optimize_home_assets', 0 );
remove_action( 'wp_print_footer_scripts', 'elmercado_optimize_home_assets', 0 );
